/-
Copyright (c) 2026 Zayn Blore. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zayn Blore
-/
module

public import CsdLean4.CV.ModeLocality
public import CsdLean4.CV.FreeFieldFloquet

/-!
# CV-6: dynamical mode locality — support is invariant under free evolution

**Category:** CV (continuous variables — the multi-mode field).

`CV/ModeLocality.lean` proved the *kinematic* locality axiom: operators
supported on disjoint mode sets commute (`commute_of_disjointSupport`). This
module makes it **dynamical**: Heisenberg evolution by the free field's
stroboscopic step preserves mode support, so the commutation of disjoint
regions persists at every period.

* `heisenberg U A` — Heisenberg conjugation `U† A U`, with the algebra
  lemmas `heisenberg_one` / `heisenberg_mul`.
* `heisenberg_phaseDiagU_supportedOn` — the mechanism, for ANY mode-additive
  diagonal phase `f c = ∑ₖ g k (c k)`: conjugation multiplies the entry
  `A c d` by the phase `e^{-i (f d − f c)}`, and when `c, d` agree off `S`
  the phase difference collapses to the `S`-modes
  (`sum_sub_sum_of_agree`, `star_phase_mul_phase`) — so both `SupportedOn`
  fields survive.
* `heisenberg_freeFieldU_supportedOn` / `heisenberg_freeFieldU_pow_supportedOn`
  — the free field is mode-additive (`fieldEnergy c = ∑ₖ oscEnergy (c k)`),
  so one period — and hence every period — preserves support.
* ★★ `commute_heisenberg_freeFieldU_pow` — **dynamical locality**:
  observables of disjoint mode sets, evolved for any number of free-field
  periods, still commute. The Haag–Kastler kinematic axiom is stable under
  the free dynamics.

Honest scope: the free (mode-diagonal) drive only. An interacting drive can
spread support — since CV-8 that is a *bounded theorem*, not an open scope:
`CV/SupportSpreading.lean` confines it to the coupling-graph light cone and
witnesses it at `K = N = 2`. The norm pricing of the violation (CV-9, the
Duhamel route) is what is still not claimed here.

## References

`CV/ModeLocality.lean` (`SupportedOn`, `commute_of_disjointSupport`);
`CV/FreeFieldFloquet.lean` (`phaseDiagU`, `freeFieldU`, CV-5);
`CV/FieldModes.lean` (`fieldEnergy`); `specs/external-library-map.md` §H;
`specs/BACKLOG.md`; `specs/future-work.md`.
-/

@[expose] public section

open Matrix

namespace CSD.CV

variable {K N : ℕ}

/-! ### Heisenberg conjugation -/

/-- **Heisenberg conjugation** by a unitary: `A ↦ U† A U`, the observable
after one period of the dynamics generated by `U`. -/
noncomputable def heisenberg (U : Matrix.unitaryGroup (FieldConfig K N) ℂ)
    (A : Matrix (FieldConfig K N) (FieldConfig K N) ℂ) :
    Matrix (FieldConfig K N) (FieldConfig K N) ℂ :=
  star U.val * A * U.val

@[simp] lemma heisenberg_one
    (A : Matrix (FieldConfig K N) (FieldConfig K N) ℂ) :
    heisenberg 1 A = A := by
  rw [heisenberg,
    show ((1 : Matrix.unitaryGroup (FieldConfig K N) ℂ) : Matrix
      (FieldConfig K N) (FieldConfig K N) ℂ) = 1 from rfl,
    star_one, one_mul, mul_one]

/-- Conjugation by a product is iterated conjugation. -/
lemma heisenberg_mul (U V : Matrix.unitaryGroup (FieldConfig K N) ℂ)
    (A : Matrix (FieldConfig K N) (FieldConfig K N) ℂ) :
    heisenberg (U * V) A = heisenberg V (heisenberg U A) := by
  rw [heisenberg, heisenberg, heisenberg,
    show (U * V).val = U.val * V.val from rfl, star_mul]
  simp only [mul_assoc]

/-- Conjugation by a diagonal-phase unitary multiplies each entry by the
phase difference: `(U† A U) c d = e^{+i f(c)} · A c d · e^{-i f(d)}`. -/
lemma heisenberg_phaseDiagU_apply (f : FieldConfig K N → ℝ)
    (A : Matrix (FieldConfig K N) (FieldConfig K N) ℂ)
    (c d : FieldConfig K N) :
    heisenberg (phaseDiagU f) A c d
      = star (Complex.exp (-(Complex.I * f c))) * A c d
          * Complex.exp (-(Complex.I * f d)) := by
  rw [heisenberg]
  simp only [phaseDiagU_val, Matrix.star_eq_conjTranspose,
    Matrix.diagonal_conjTranspose, Matrix.mul_diagonal, Matrix.diagonal_mul,
    Pi.star_apply]

/-! ### Mode-additive phases and the phase-difference collapse -/

/-- Off-`S` agreement collapses a mode-additive difference to the `S`-modes:
the spectator terms cancel. -/
lemma sum_sub_sum_of_agree {S : Finset (Fin K)} (g : Fin K → Fin N → ℝ)
    {x y : FieldConfig K N} (h : ∀ k, k ∉ S → x k = y k) :
    (∑ k, g k (y k)) - (∑ k, g k (x k))
      = ∑ k ∈ S, (g k (y k) - g k (x k)) := by
  rw [← Finset.sum_sub_distrib]
  refine (Finset.sum_subset (Finset.subset_univ S) ?_).symm
  intro k _ hk
  rw [h k hk, sub_self]

/-- The conjugating phase pair of a mode-additive diagonal unitary depends
only on the `S`-modes when the configurations agree off `S`:
`e^{+i f(x)} · e^{-i f(y)} = e^{-i ∑_{k∈S} (g k (y k) − g k (x k))}`. -/
lemma star_phase_mul_phase {S : Finset (Fin K)} (g : Fin K → Fin N → ℝ)
    {x y : FieldConfig K N} (h : ∀ k, k ∉ S → x k = y k) :
    star (Complex.exp (-(Complex.I * ((∑ k, g k (x k) : ℝ) : ℂ))))
        * Complex.exp (-(Complex.I * ((∑ k, g k (y k) : ℝ) : ℂ)))
      = Complex.exp
          (-(Complex.I * ((∑ k ∈ S, (g k (y k) - g k (x k)) : ℝ) : ℂ))) := by
  rw [Complex.star_def, ← Complex.exp_conj, ← Complex.exp_add]
  congr 1
  rw [show (starRingEnd ℂ) (-(Complex.I * ((∑ k, g k (x k) : ℝ) : ℂ)))
      = Complex.I * ((∑ k, g k (x k) : ℝ) : ℂ) from by
    simp [Complex.conj_I, Complex.conj_ofReal]]
  rw [← sum_sub_sum_of_agree g h]
  push_cast
  ring

/-- **Mode-additive diagonal phases preserve mode support.** Conjugation
multiplies `A c d` by `e^{-i (f d − f c)}`; when the configurations agree off
`S` the phase difference lives on the `S`-modes alone, so both `SupportedOn`
fields survive. -/
theorem heisenberg_phaseDiagU_supportedOn {S : Finset (Fin K)}
    {A : Matrix (FieldConfig K N) (FieldConfig K N) ℂ}
    (g : Fin K → Fin N → ℝ) (hA : SupportedOn S A) :
    SupportedOn S
      (heisenberg (phaseDiagU (fun c => ∑ k, g k (c k))) A) := by
  constructor
  · intro c d k hk hcd
    rw [heisenberg_phaseDiagU_apply, hA.offDiag hk hcd, mul_zero, zero_mul]
  · intro c d c' d' h1 h2 h3 h4
    have hS : (∑ k ∈ S, (g k (d k) - g k (c k)))
        = ∑ k ∈ S, (g k (d' k) - g k (c' k)) :=
      Finset.sum_congr rfl fun k hk => by rw [h1 k hk, h2 k hk]
    rw [heisenberg_phaseDiagU_apply, heisenberg_phaseDiagU_apply,
      hA.indep h1 h2 h3 h4, mul_right_comm]
    conv_rhs => rw [mul_right_comm]
    rw [star_phase_mul_phase g h3, star_phase_mul_phase g h4, hS]

/-! ### The free field: support is invariant at every period -/

/-- **One free-field period preserves mode support** — the field energy is
mode-additive (`fieldEnergy c = ∑ₖ oscEnergy (c k)`). -/
theorem heisenberg_freeFieldU_supportedOn {S : Finset (Fin K)}
    {A : Matrix (FieldConfig K N) (FieldConfig K N) ℂ} (τ : ℝ)
    (hA : SupportedOn S A) :
    SupportedOn S (heisenberg (freeFieldU K N τ) A) := by
  have hf : (fun c : FieldConfig K N => τ * fieldEnergy c)
      = fun c : FieldConfig K N => ∑ k, τ * oscEnergy (c k) := by
    funext c
    rw [show fieldEnergy c = ∑ k, oscEnergy (c k) from rfl, Finset.mul_sum]
  rw [show freeFieldU K N τ
      = phaseDiagU (fun c : FieldConfig K N => τ * fieldEnergy c) from rfl,
    hf]
  exact heisenberg_phaseDiagU_supportedOn (fun _ n => τ * oscEnergy n) hA

/-- **Every free-field period preserves mode support**: the `n`-period
Heisenberg observable is still supported on `S`. -/
theorem heisenberg_freeFieldU_pow_supportedOn {S : Finset (Fin K)}
    {A : Matrix (FieldConfig K N) (FieldConfig K N) ℂ} (τ : ℝ) (n : ℕ)
    (hA : SupportedOn S A) :
    SupportedOn S (heisenberg (freeFieldU K N τ ^ n) A) := by
  induction n with
  | zero => rw [pow_zero, heisenberg_one]; exact hA
  | succ n ih =>
    rw [pow_succ, heisenberg_mul]
    exact heisenberg_freeFieldU_supportedOn τ ih

/-- Disjointly supported observables commute after one free-field period. -/
theorem commute_heisenberg_freeFieldU {S T : Finset (Fin K)}
    (hST : Disjoint S T)
    {A B : Matrix (FieldConfig K N) (FieldConfig K N) ℂ} (τ : ℝ)
    (hA : SupportedOn S A) (hB : SupportedOn T B) :
    heisenberg (freeFieldU K N τ) A * heisenberg (freeFieldU K N τ) B
      = heisenberg (freeFieldU K N τ) B * heisenberg (freeFieldU K N τ) A :=
  commute_of_disjointSupport hST (heisenberg_freeFieldU_supportedOn τ hA)
    (heisenberg_freeFieldU_supportedOn τ hB)

/-- ★★ **Dynamical locality**: observables of disjoint mode sets, evolved in
the Heisenberg picture for ANY number of free-field periods, still commute.
The kinematic Haag–Kastler axiom (`commute_of_disjointSupport`) is stable
under the free dynamics — locality is a feature of the evolution, not just
of the instant. -/
theorem commute_heisenberg_freeFieldU_pow {S T : Finset (Fin K)}
    (hST : Disjoint S T)
    {A B : Matrix (FieldConfig K N) (FieldConfig K N) ℂ} (τ : ℝ) (n : ℕ)
    (hA : SupportedOn S A) (hB : SupportedOn T B) :
    heisenberg (freeFieldU K N τ ^ n) A * heisenberg (freeFieldU K N τ ^ n) B
      = heisenberg (freeFieldU K N τ ^ n) B
          * heisenberg (freeFieldU K N τ ^ n) A :=
  commute_of_disjointSupport hST
    (heisenberg_freeFieldU_pow_supportedOn τ n hA)
    (heisenberg_freeFieldU_pow_supportedOn τ n hB)

end CSD.CV
