/-
Copyright (c) 2026 Zayn Blore. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zayn Blore
-/
module

public import CsdLean4.CV.FieldModes
public import CsdLean4.Incubator.QuantumChaos.FloquetInterface
public import Mathlib.Analysis.Normed.Algebra.MatrixExponential
public import Mathlib.Analysis.SpecialFunctions.Exponential

/-!
# CV-5: free-field stroboscopic dynamics (the CV pillar meets the Floquet interface)

**Category:** 3-Local (CV track; CSD-free construction).

The free field's Hamiltonian is **mode-diagonal** (`fieldHamiltonian = diagonal
(fieldEnergy ·)`), so its stroboscopic one-period evolution is an explicit
diagonal-phase unitary — no matrix-exponential machinery is needed to *build*
it, and the matrix exponential is recovered as a theorem:

* `phaseDiagU f` — the diagonal-phase unitary `diag (e^{-i f(x)})` over ANY
  finite index (generic; the kicked-Ising `phaseMat` is the same shape).
* `freeFieldU K N τ` — one stroboscopic period of the free field:
  phases `e^{-i τ E(c)}` at the field energies `E(c) = ∑ₖ oscEnergy (c k)`.
* ★ `freeFieldU_eq_exp` — legitimacy: the constructed step IS the matrix
  exponential `exp (-(iτ) • H_field)` (via `Matrix.exp_diagonal`), so
  "generated by the field Hamiltonian" is a theorem, not a reading.
* `freeFieldFloquet K N τ` — the field dynamics as a `FloquetEvolution`
  through the generic `ofUnitaryMatrix` seam: the whole §H interface API
  (exact information preservation at every period, induced projective
  dynamics, Loschmidt diagnostics) applies to the CV pillar verbatim.

The CSD-side closure (ontic lift on `KSigma`, record persistence) is
instantiated in `Empirical/CSD/QuantumChaos/FreeFieldClosure.lean`; the
locality consequence (mode-support preservation, dynamical commutation) is
CV-6 (`CV/DynamicalLocality.lean`). Honest scope: finite cutoff throughout
(`K` modes, `N` levels), free field only — interactions are outside this
module's claims.
-/

@[expose] public section

open Matrix NormedSpace

namespace CSD.CV

/-! ### The diagonal-phase unitary, generically -/

/-- Each diagonal phase entry annihilates its conjugate:
`conj (e^{-ir}) · e^{-ir} = 1`. -/
lemma exp_neg_I_mul_star_mul_self (r : ℝ) :
    star (Complex.exp (-(Complex.I * r))) * Complex.exp (-(Complex.I * r)) = 1 := by
  rw [Complex.star_def, ← Complex.exp_conj, ← Complex.exp_add]
  have : (starRingEnd ℂ) (-(Complex.I * r)) = Complex.I * r := by
    simp [Complex.conj_I, Complex.conj_ofReal]
  rw [this, add_neg_cancel, Complex.exp_zero]

/-- **The diagonal-phase unitary** `diag (e^{-i f(x)})` over any finite index:
the one-period evolution of any diagonal Hamiltonian with (real) spectrum
`f`. -/
noncomputable def phaseDiagU {ι : Type*} [Fintype ι] [DecidableEq ι]
    (f : ι → ℝ) : Matrix.unitaryGroup ι ℂ :=
  ⟨Matrix.diagonal (fun x => Complex.exp (-(Complex.I * f x))), by
    rw [Matrix.mem_unitaryGroup_iff', Matrix.star_eq_conjTranspose,
      Matrix.diagonal_conjTranspose, Matrix.diagonal_mul_diagonal,
      show (1 : Matrix ι ι ℂ) = Matrix.diagonal (fun _ => 1) from
        Matrix.diagonal_one.symm]
    congr 1
    funext x
    exact exp_neg_I_mul_star_mul_self (f x)⟩

@[simp] lemma phaseDiagU_val {ι : Type*} [Fintype ι] [DecidableEq ι]
    (f : ι → ℝ) :
    (phaseDiagU f).val
      = Matrix.diagonal (fun x => Complex.exp (-(Complex.I * f x))) := rfl

/-! ### The free-field stroboscopic step -/

variable {K N : ℕ}

/-- **One stroboscopic period of the free field**: diagonal phases
`e^{-i τ E(c)}` at the field energies. -/
noncomputable def freeFieldU (K N : ℕ) (τ : ℝ) :
    Matrix.unitaryGroup (FieldConfig K N) ℂ :=
  phaseDiagU (fun c => τ * fieldEnergy c)

/-- ★ **Legitimacy: the constructed step IS the matrix exponential of the
field Hamiltonian**, `freeFieldU K N τ = exp (-(iτ) • H_field)` — so
"generated by `H_field`" is a theorem of the construction, not a gloss. -/
theorem freeFieldU_eq_exp (K N : ℕ) (τ : ℝ) :
    (freeFieldU K N τ).val
      = exp ((-(Complex.I * τ)) • fieldHamiltonian K N) := by
  rw [freeFieldU, phaseDiagU_val,
    show fieldHamiltonian K N
      = Matrix.diagonal (fun c => ((fieldEnergy c : ℝ) : ℂ)) from rfl,
    ← Matrix.diagonal_smul, Matrix.exp_diagonal]
  congr 1
  funext c
  rw [Pi.exp_def]
  show Complex.exp (-(Complex.I * ((τ * fieldEnergy c : ℝ) : ℂ)))
      = exp ((-(Complex.I * τ)) • ((fieldEnergy c : ℝ) : ℂ))
  rw [← Complex.exp_eq_exp_ℂ, smul_eq_mul]
  congr 1
  push_cast
  ring

/-- **The free field as a Floquet evolution** — the §H interface applies to
the CV pillar verbatim: exact information preservation at every period,
induced projective dynamics, Loschmidt diagnostics. -/
noncomputable def freeFieldFloquet (K N : ℕ) (τ : ℝ) :
    _root_.QuantumChaos.FloquetEvolution (FieldSpace K N) :=
  _root_.QuantumChaos.FloquetEvolution.ofUnitaryMatrix (freeFieldU K N τ)

end CSD.CV
