/-
Copyright (c) 2026 Zayn Blore. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zayn Blore
-/
module

public import CsdLean4.CV.FreeFieldFloquet

/-!
# CV-7: the interacting drive (EFT Stage 3a)

**Category:** CV (continuous variables — the multi-mode field).

The first interacting object of the EFT chain. A **diagonal** (density–density)
interaction commutes with the free Hamiltonian, so the interacting stroboscopic
evolution is **exact** — one `phaseDiagU`, no Trotter step, no approximation to
apologize for — and its generation by the interacting Hamiltonian is a theorem:

* `densityCoupling k l g` — the pair potential `v c = g (c k) (c l)`: the
  interaction energy depends on the occupations of the two coupled modes (the
  kicked-Ising `phaseMat` is exactly this shape at `K = N = 2`).
* `interactionHamiltonian v` — `diagonal v`, Hermitian
  (`interactionHamiltonian_isHermitian`).
* `interactingU K N τ lam v` — one stroboscopic period of `H_free + lam·V`:
  diagonal phases `e^{-iτ(E(c) + lam·v(c))}`.
* ★ `interactingU_eq_exp` — legitimacy:
  `interactingU = exp (-(iτ) • (H_field + lam • V))` (via the generic
  `phaseDiagU_eq_exp`) — "generated by the interacting Hamiltonian" is a
  theorem of the construction.
* `interactingU_zero` — switching the coupling off recovers the free field.
* `interactingFloquet` — the §H2 `FloquetEvolution` instance: the interface
  API (exact information preservation, projective dynamics, Loschmidt
  diagnostics) applies to the interacting drive verbatim.

The locality consequences — support spreading bounded by the coupling-graph
light cone — are CV-8 (`CV/SupportSpreading.lean`); the CSD-side closure
instance is in `Empirical/CSD/QuantumChaos/FreeFieldClosure.lean`. Honest
scope: finite cutoff, diagonal interactions only — non-diagonal (hopping)
interactions have no closed-form step and enter through the Duhamel pricing
(CV-9), and nothing continuum is claimed.

## References

`CV/FreeFieldFloquet.lean` (CV-5, `phaseDiagU`, `phaseDiagU_eq_exp`);
`CV/SupportSpreading.lean` (CV-8); `specs/cv-stage3-plan.md` §3a;
`Incubator/QuantumChaos/KickedIsingPilot.lean` (`phaseMat`, the prototype);
`specs/external-library-map.md` §H; `specs/future-work.md` (row CV-7).
-/

@[expose] public section

open Matrix NormedSpace

namespace CSD.CV

variable {K N : ℕ}

/-! ### Diagonal interactions -/

/-- **The density–density pair coupling**: the interaction energy depends on
the occupations of modes `k` and `l` through `g`. -/
def densityCoupling (k l : Fin K) (g : Fin N → Fin N → ℝ) :
    FieldConfig K N → ℝ :=
  fun c => g (c k) (c l)

/-- **The interaction Hamiltonian** of a diagonal potential `v`: `diagonal v`
in the configuration basis. -/
noncomputable def interactionHamiltonian (v : FieldConfig K N → ℝ) :
    Matrix (FieldConfig K N) (FieldConfig K N) ℂ :=
  Matrix.diagonal (fun c => ((v c : ℝ) : ℂ))

/-- A diagonal real potential is a Hermitian interaction. -/
theorem interactionHamiltonian_isHermitian (v : FieldConfig K N → ℝ) :
    (interactionHamiltonian v).IsHermitian := by
  rw [Matrix.IsHermitian, interactionHamiltonian,
    Matrix.diagonal_conjTranspose]
  congr 1
  funext c
  simp [Complex.conj_ofReal]

/-! ### The interacting stroboscopic step -/

/-- **One stroboscopic period of the interacting field** `H_free + lam·V`:
diagonal phases `e^{-iτ(E(c) + lam·v(c))}`. Exact — a diagonal interaction
commutes with the free Hamiltonian, so no Trotter splitting is involved. -/
noncomputable def interactingU (K N : ℕ) (τ lam : ℝ)
    (v : FieldConfig K N → ℝ) :
    Matrix.unitaryGroup (FieldConfig K N) ℂ :=
  phaseDiagU (fun c => τ * (fieldEnergy c + lam * v c))

@[simp] lemma interactingU_val (τ lam : ℝ) (v : FieldConfig K N → ℝ) :
    (interactingU K N τ lam v).val
      = Matrix.diagonal (fun c => Complex.exp
          (-(Complex.I * ((τ * (fieldEnergy c + lam * v c) : ℝ) : ℂ)))) :=
  rfl

/-- Switching the coupling off recovers the free field. -/
theorem interactingU_zero (τ : ℝ) (v : FieldConfig K N → ℝ) :
    interactingU K N τ 0 v = freeFieldU K N τ := by
  rw [interactingU, freeFieldU]
  congr 1
  funext c
  rw [zero_mul, add_zero]

/-- ★ **Legitimacy: the interacting step IS the matrix exponential of the
interacting Hamiltonian**,
`interactingU K N τ lam v = exp (-(iτ) • (H_field + lam • V))` — so
"generated by `H_free + lam·V`" is a theorem of the construction, not a
gloss. -/
theorem interactingU_eq_exp (K N : ℕ) (τ lam : ℝ)
    (v : FieldConfig K N → ℝ) :
    (interactingU K N τ lam v).val
      = exp ((-(Complex.I * τ)) •
          (fieldHamiltonian K N + lam • interactionHamiltonian v)) := by
  rw [interactingU, phaseDiagU_eq_exp]
  congr 1
  rw [show fieldHamiltonian K N
      = Matrix.diagonal (fun c => ((fieldEnergy c : ℝ) : ℂ)) from rfl,
    interactionHamiltonian, ← Matrix.diagonal_smul, ← Matrix.diagonal_smul,
    Matrix.diagonal_add, ← Matrix.diagonal_smul]
  congr 1
  funext c
  show (-Complex.I) • ((τ * (fieldEnergy c + lam * v c) : ℝ) : ℂ)
      = (-(Complex.I * τ)) •
          (((fieldEnergy c : ℝ) : ℂ) + lam • ((v c : ℝ) : ℂ))
  simp only [smul_eq_mul, Complex.real_smul]
  push_cast
  ring

/-- **The interacting field as a Floquet evolution** — the §H interface
applies to the interacting drive verbatim. -/
noncomputable def interactingFloquet (K N : ℕ) (τ lam : ℝ)
    (v : FieldConfig K N → ℝ) :
    _root_.QuantumChaos.FloquetEvolution (FieldSpace K N) :=
  _root_.QuantumChaos.FloquetEvolution.ofUnitaryMatrix
    (interactingU K N τ lam v)

end CSD.CV
