/-
Copyright (c) 2026 Zayn Blore. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zayn Blore
-/
module

public import CsdLean4.Mathlib.Analysis.Matrix.DuhamelBound
public import CsdLean4.CV.SupportSpreading

/-!
# CV-17/CV-18: the Heisenberg flow and the linear Lieb-Robinson bound

**Category:** CV (continuous variables); the general lemmas are CSD-free
(`upstream-candidate(mathlib)`).

Stage 5's first two bricks. Everything is stated for a skew-Hermitian
generator `S`, which is `-i H` for Hermitian `H`, so that the propagators
are unitary and the L2 operator norm sees them as isometries.

* `heisenbergFlow S t A = exp (-t • S) * A * exp (t • S)` — the observable
  after time `t`; `norm_heisenbergFlow_le` (conjugation by unitaries does
  not grow the norm), `heisenbergFlow_zero`.
* ★ `hasDerivAt_heisenbergFlow` — `d/dt A(t) = [A(t), S]` (CV-17).
* `commutator_deriv_eq` — the interaction-picture split. Writing
  `S = S_X + T` with `S_X` the part of the generator that commutes with the
  probe `B`, the commutator `f(t) = [A(t), B]` obeys
  `f'(t) = [f(t), S_X] + [[A(t), T], B]`. The first term is a pure
  conjugation and carries no growth; all the growth is in `T`, the part of
  the generator that couples across the cut. Proved by the Jacobi
  cancellation `A·[S_X,B] - [S_X,B]·A = 0`.
* ★★ `norm_commutator_heisenbergFlow_le` — **the linear Lieb-Robinson
  bound**: if `[A, B] = 0` and `S_X` commutes with `B`, then
  `‖[A(t), B]‖ ≤ 4·|t|·‖T‖·‖A‖·‖B‖`. **Information cannot leave a region
  instantaneously**: the commutator grows at most linearly in time, at a
  rate set by the coupling across the cut alone, not by the total energy.
* `norm_commutator_freeFieldGen_le` — the CV instantiation: disjointly
  supported observables of the field, with `[A,B] = 0` supplied by CV-8's
  `commute_of_disjointSupport`.

⚠️ Honest scope: this is the **linear** bound. The exponential form
`e^{-μ(d - v|t|)}`, with a velocity and a distance, needs the iteration
over chains of interaction terms and the path count, which is CV-19 and is
gated research (`specs/eft-stage5-plan.md`). Nothing here claims a
velocity. No continuum (`ApproxCCR.no_exact_finite_ccr` stands).

## References

`Mathlib/Analysis/Matrix/DuhamelBound.lean` (the mean-value pattern and the
skew-generator lemmas); `CV/SupportSpreading.lean` (CV-8, the initial
condition); `specs/eft-stage5-plan.md` (rows CV-17, CV-18);
Lieb-Robinson (1972); Nachtergaele-Sims (2010).
-/

@[expose] public section

open scoped Matrix.Norms.L2Operator
open Matrix NormedSpace

namespace CSD.CV

variable {m : Type*} [Fintype m] [DecidableEq m] [Nonempty m]

/-! ### CV-17: the Heisenberg flow -/

/-- **The Heisenberg flow** generated by a skew-Hermitian `S = -iH`. -/
noncomputable def heisenbergFlow (S : Matrix m m ℂ) (t : ℝ)
    (A : Matrix m m ℂ) : Matrix m m ℂ :=
  exp ((-t) • S) * A * exp (t • S)

omit [Nonempty m] in
@[simp] lemma heisenbergFlow_zero (S A : Matrix m m ℂ) :
    heisenbergFlow S 0 A = A := by
  rw [heisenbergFlow]
  simp

/-- Conjugation by the unitary propagators does not grow the norm. -/
theorem norm_heisenbergFlow_le {S : Matrix m m ℂ} (hS : Sᴴ = -S) (t : ℝ)
    (A : Matrix m m ℂ) : ‖heisenbergFlow S t A‖ ≤ ‖A‖ := by
  have h1 : ‖exp ((-t) • S)‖ = 1 := Matrix.l2_opNorm_exp_smul_skew S hS (-t)
  have h2 : ‖exp (t • S)‖ = 1 := Matrix.l2_opNorm_exp_smul_skew S hS t
  calc ‖exp ((-t) • S) * A * exp (t • S)‖
      ≤ ‖exp ((-t) • S) * A‖ * ‖exp (t • S)‖ := norm_mul_le _ _
    _ ≤ ‖exp ((-t) • S)‖ * ‖A‖ * ‖exp (t • S)‖ := by
        gcongr
        exact norm_mul_le _ _
    _ = ‖A‖ := by rw [h1, h2, one_mul, mul_one]

omit [Nonempty m] in
/-- ★ **CV-17**: the Heisenberg flow solves `d/dt A(t) = [A(t), S]`. -/
theorem hasDerivAt_heisenbergFlow (S A : Matrix m m ℂ) (t : ℝ) :
    HasDerivAt (fun u => heisenbergFlow S u A)
      (heisenbergFlow S t A * S - S * heisenbergFlow S t A) t := by
  have hneg : HasDerivAt (fun u : ℝ => -u) (-1 : ℝ) t := hasDerivAt_neg t
  have hL : HasDerivAt (fun u : ℝ => exp ((-u) • S))
      ((-1 : ℝ) • (exp ((-t) • S) * S)) t :=
    (hasDerivAt_exp_smul_const S (-t)).scomp t hneg
  have hR : HasDerivAt (fun u : ℝ => exp (u • S)) (exp (t • S) * S) t :=
    hasDerivAt_exp_smul_const S t
  have hprod := (hL.mul_const A).mul hR
  have hcommL : exp ((-t) • S) * S = S * exp ((-t) • S) :=
    (((Commute.refl S).smul_left (-t)).exp_left).eq
  refine hprod.congr_deriv ?_
  rw [heisenbergFlow, neg_one_smul, neg_mul, neg_mul, hcommL]
  noncomm_ring

/-! ### The interaction-picture split -/

omit [Nonempty m] in
/-- **The split.** With `S = S_X + T` and `S_X` commuting with the probe
`B`, the commutator `[A(t), B]` obeys `f' = [f, S_X] + [[A(t), T], B]`:
the local part of the generator contributes only a conjugation, and all
growth comes from `T`, the part that couples across the cut. -/
theorem commutator_deriv_eq {S S_X T : Matrix m m ℂ} (A B : Matrix m m ℂ)
    (hsplit : S = S_X + T) (hcomm : S_X * B = B * S_X) (t : ℝ) :
    HasDerivAt (fun u => heisenbergFlow S u A * B - B * heisenbergFlow S u A)
      ((heisenbergFlow S t A * B - B * heisenbergFlow S t A) * S_X
        - S_X * (heisenbergFlow S t A * B - B * heisenbergFlow S t A)
        + ((heisenbergFlow S t A * T - T * heisenbergFlow S t A) * B
          - B * (heisenbergFlow S t A * T - T * heisenbergFlow S t A))) t := by
  set F := heisenbergFlow S t A with hF
  have hd := hasDerivAt_heisenbergFlow S A t
  have hprod := (hd.mul_const B).sub (hd.const_mul B)
  have hz : S_X * B - B * S_X = 0 := sub_eq_zero.mpr hcomm
  have hexpand : (F * S - S * F) * B - B * (F * S - S * F)
      - (((F * B - B * F) * S_X - S_X * (F * B - B * F))
        + ((F * T - T * F) * B - B * (F * T - T * F)))
      = F * (S_X * B - B * S_X) - (S_X * B - B * S_X) * F := by
    rw [hsplit]
    noncomm_ring
  have hkey : (F * S - S * F) * B - B * (F * S - S * F)
      = ((F * B - B * F) * S_X - S_X * (F * B - B * F))
        + ((F * T - T * F) * B - B * (F * T - T * F)) := by
    rw [← sub_eq_zero, hexpand, hz, mul_zero, zero_mul, sub_zero]
  exact hprod.congr_deriv hkey

/-! ### CV-18: the linear bound -/

/-- The conjugated commutator, whose derivative has no conjugation term. -/
private noncomputable def conjComm (S S_X : Matrix m m ℂ) (A B : Matrix m m ℂ)
    (t : ℝ) : Matrix m m ℂ :=
  exp (t • S_X)
    * (heisenbergFlow S t A * B - B * heisenbergFlow S t A)
    * exp ((-t) • S_X)

/-- ★★ **CV-18, the linear Lieb-Robinson bound.** If the observables
commute at time zero and the local part `S_X` of the generator commutes
with the probe `B`, then the commutator grows at most linearly in time, at
a rate set by `T` (the part of the generator coupling across the cut)
alone: `‖[A(t), B]‖ ≤ 4·|t|·‖T‖·‖A‖·‖B‖`. Information cannot leave a
region instantaneously. -/
theorem norm_commutator_heisenbergFlow_le {S S_X T : Matrix m m ℂ}
    {A B : Matrix m m ℂ} (hS : Sᴴ = -S) (hSX : S_Xᴴ = -S_X)
    (hsplit : S = S_X + T) (hcomm : S_X * B = B * S_X)
    (hAB : A * B = B * A) (t : ℝ) :
    ‖heisenbergFlow S t A * B - B * heisenbergFlow S t A‖
      ≤ 4 * |t| * ‖T‖ * ‖A‖ * ‖B‖ := by
  set g : ℝ → Matrix m m ℂ := conjComm S S_X A B with hg
  -- the derivative of the conjugated commutator is the pure leakage term
  have hderiv : ∀ s : ℝ, HasDerivAt g
      (exp (s • S_X)
        * ((heisenbergFlow S s A * T - T * heisenbergFlow S s A) * B
          - B * (heisenbergFlow S s A * T - T * heisenbergFlow S s A))
        * exp ((-s) • S_X)) s := by
    intro s
    set F := heisenbergFlow S s A with hFs
    set f := F * B - B * F with hfs
    set R := (F * T - T * F) * B - B * (F * T - T * F) with hRs
    have hP : HasDerivAt (fun u : ℝ => exp (u • S_X)) (exp (s • S_X) * S_X) s :=
      hasDerivAt_exp_smul_const S_X s
    have hnegs : HasDerivAt (fun u : ℝ => -u) (-1 : ℝ) s := hasDerivAt_neg s
    have hQ : HasDerivAt (fun u : ℝ => exp ((-u) • S_X))
        ((-1 : ℝ) • (exp ((-s) • S_X) * S_X)) s :=
      (hasDerivAt_exp_smul_const S_X (-s)).scomp s hnegs
    have hf := commutator_deriv_eq (S := S) (S_X := S_X) (T := T) A B
      hsplit hcomm s
    have hprod := ((hP.mul hf).mul hQ)
    simp only [Pi.mul_apply, neg_one_smul] at hprod
    have hcommP : exp (s • S_X) * S_X = S_X * exp (s • S_X) :=
      (((Commute.refl S_X).smul_left s).exp_left).eq
    have hcommQ : exp ((-s) • S_X) * S_X = S_X * exp ((-s) • S_X) :=
      (((Commute.refl S_X).smul_left (-s)).exp_left).eq
    refine hprod.congr_deriv ?_
    rw [mul_neg, hcommQ]
    simp only [hRs, neg_smul]
    noncomm_ring
  -- the derivative is bounded by the leakage rate
  have hbound : ∀ s : ℝ, ‖exp (s • S_X)
      * ((heisenbergFlow S s A * T - T * heisenbergFlow S s A) * B
        - B * (heisenbergFlow S s A * T - T * heisenbergFlow S s A))
      * exp ((-s) • S_X)‖ ≤ 4 * ‖T‖ * ‖A‖ * ‖B‖ := by
    intro s
    set F := heisenbergFlow S s A with hFs
    have hFn : ‖F‖ ≤ ‖A‖ := norm_heisenbergFlow_le hS s A
    have hFT : ‖F * T - T * F‖ ≤ 2 * ‖T‖ * ‖A‖ := by
      calc ‖F * T - T * F‖ ≤ ‖F * T‖ + ‖T * F‖ := norm_sub_le _ _
        _ ≤ ‖F‖ * ‖T‖ + ‖T‖ * ‖F‖ :=
            add_le_add (norm_mul_le _ _) (norm_mul_le _ _)
        _ ≤ ‖A‖ * ‖T‖ + ‖T‖ * ‖A‖ := by gcongr
        _ = 2 * ‖T‖ * ‖A‖ := by ring
    have hR : ‖(F * T - T * F) * B - B * (F * T - T * F)‖
        ≤ 4 * ‖T‖ * ‖A‖ * ‖B‖ := by
      calc ‖(F * T - T * F) * B - B * (F * T - T * F)‖
          ≤ ‖(F * T - T * F) * B‖ + ‖B * (F * T - T * F)‖ := norm_sub_le _ _
        _ ≤ ‖F * T - T * F‖ * ‖B‖ + ‖B‖ * ‖F * T - T * F‖ :=
            add_le_add (norm_mul_le _ _) (norm_mul_le _ _)
        _ ≤ (2 * ‖T‖ * ‖A‖) * ‖B‖ + ‖B‖ * (2 * ‖T‖ * ‖A‖) := by gcongr
        _ = 4 * ‖T‖ * ‖A‖ * ‖B‖ := by ring
    have hP1 : ‖exp (s • S_X)‖ = 1 := Matrix.l2_opNorm_exp_smul_skew S_X hSX s
    have hQ1 : ‖exp ((-s) • S_X)‖ = 1 :=
      Matrix.l2_opNorm_exp_smul_skew S_X hSX (-s)
    calc ‖exp (s • S_X) * ((F * T - T * F) * B - B * (F * T - T * F))
            * exp ((-s) • S_X)‖
        ≤ ‖exp (s • S_X) * ((F * T - T * F) * B - B * (F * T - T * F))‖
            * ‖exp ((-s) • S_X)‖ := norm_mul_le _ _
      _ ≤ ‖exp (s • S_X)‖ * ‖(F * T - T * F) * B - B * (F * T - T * F)‖
            * ‖exp ((-s) • S_X)‖ := by
          gcongr
          exact norm_mul_le _ _
      _ = ‖(F * T - T * F) * B - B * (F * T - T * F)‖ := by
          rw [hP1, hQ1, one_mul, mul_one]
      _ ≤ 4 * ‖T‖ * ‖A‖ * ‖B‖ := hR
  -- mean value inequality on [0, t]
  have hmvt := Convex.norm_image_sub_le_of_norm_hasDerivWithin_le
    (f := g)
    (f' := fun s => exp (s • S_X)
      * ((heisenbergFlow S s A * T - T * heisenbergFlow S s A) * B
        - B * (heisenbergFlow S s A * T - T * heisenbergFlow S s A))
      * exp ((-s) • S_X))
    (s := Set.uIcc (0 : ℝ) t) (C := 4 * ‖T‖ * ‖A‖ * ‖B‖)
    (fun s _ => (hderiv s).hasDerivWithinAt)
    (fun s _ => hbound s)
    (convex_uIcc 0 t) Set.left_mem_uIcc Set.right_mem_uIcc
  -- identify the endpoints: g 0 = [A, B] = 0, and ‖g t‖ = ‖[A(t), B]‖
  have hg0 : g 0 = 0 := by
    rw [hg, conjComm]
    simp [heisenbergFlow_zero, sub_eq_zero.mpr hAB]
  have hgt : ‖g t‖ = ‖heisenbergFlow S t A * B - B * heisenbergFlow S t A‖ := by
    set f := heisenbergFlow S t A * B - B * heisenbergFlow S t A with hft
    have hP1 : ‖exp (t • S_X)‖ = 1 := Matrix.l2_opNorm_exp_smul_skew S_X hSX t
    have hQ1 : ‖exp ((-t) • S_X)‖ = 1 :=
      Matrix.l2_opNorm_exp_smul_skew S_X hSX (-t)
    refine le_antisymm ?_ ?_
    · calc ‖g t‖ ≤ ‖exp (t • S_X) * f‖ * ‖exp ((-t) • S_X)‖ := by
            rw [hg, conjComm]; exact norm_mul_le _ _
        _ ≤ ‖exp (t • S_X)‖ * ‖f‖ * ‖exp ((-t) • S_X)‖ := by
            gcongr; exact norm_mul_le _ _
        _ = ‖f‖ := by rw [hP1, hQ1, one_mul, mul_one]
    · have hback : f = exp ((-t) • S_X) * g t * exp (t • S_X) := by
        rw [hg, conjComm,
          show exp ((-t) • S_X) * (exp (t • S_X) * f * exp ((-t) • S_X))
              * exp (t • S_X)
            = (exp ((-t) • S_X) * exp (t • S_X)) * f
              * (exp ((-t) • S_X) * exp (t • S_X)) from by noncomm_ring,
          ← Matrix.exp_add_of_commute _ _ (((Commute.refl S_X).smul_left (-t)).smul_right t),
          neg_smul, neg_add_cancel, exp_zero, one_mul, mul_one]
      calc ‖f‖ = ‖exp ((-t) • S_X) * g t * exp (t • S_X)‖ := by rw [← hback]
        _ ≤ ‖exp ((-t) • S_X) * g t‖ * ‖exp (t • S_X)‖ := norm_mul_le _ _
        _ ≤ ‖exp ((-t) • S_X)‖ * ‖g t‖ * ‖exp (t • S_X)‖ := by
            gcongr; exact norm_mul_le _ _
        _ = ‖g t‖ := by rw [hP1, hQ1, one_mul, mul_one]
  rw [hg0, sub_zero, hgt] at hmvt
  calc ‖heisenbergFlow S t A * B - B * heisenbergFlow S t A‖
      ≤ 4 * ‖T‖ * ‖A‖ * ‖B‖ * |t - 0| := hmvt
    _ = 4 * |t| * ‖T‖ * ‖A‖ * ‖B‖ := by rw [sub_zero]; ring

/-! ### The CV instantiation -/

/-- ★ **On the field**: for observables supported on disjoint mode sets, the
commutator after time `t` is bounded by the cut coupling alone. The
zero-time commutation hypothesis is supplied by CV-8's
`commute_of_disjointSupport`, so only the generator split has to be
provided. -/
theorem norm_commutator_field_le {K N : ℕ} [NeZero N]
    {S S_X T : Matrix (FieldConfig K N) (FieldConfig K N) ℂ}
    {R Y : Finset (Fin K)} {A B : Matrix (FieldConfig K N) (FieldConfig K N) ℂ}
    (hS : Sᴴ = -S) (hSX : S_Xᴴ = -S_X) (hsplit : S = S_X + T)
    (hcomm : S_X * B = B * S_X) (hRY : Disjoint R Y)
    (hA : SupportedOn R A) (hB : SupportedOn Y B) (t : ℝ) :
    ‖heisenbergFlow S t A * B - B * heisenbergFlow S t A‖
      ≤ 4 * |t| * ‖T‖ * ‖A‖ * ‖B‖ :=
  norm_commutator_heisenbergFlow_le hS hSX hsplit hcomm
    (commute_of_disjointSupport hRY hA hB) t

end CSD.CV
