/-
Copyright (c) 2026 Zayn Blore. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zayn Blore
-/
module

public import CsdLean4.Mathlib.Dynamics.CorrelationDecay
public import Mathlib.Analysis.Fourier.AddCircle
public import Mathlib.MeasureTheory.Group.Measure
public import Mathlib.MeasureTheory.Measure.Haar.Unique
public import Mathlib.MeasureTheory.Measure.Prod
public import Mathlib.MeasureTheory.Integral.Bochner.ContinuousLinearMap

/-!
# An **invertible** correlation-decay witness: Arnold's cat map on `T²`

**Category:** 1-Mathlib (CSD-free; staged as a Mathlib-upstream candidate).

`CorrelationDecayWitness.lean` shows `HasCorrelationDecay` is satisfiable, using the **doubling
endomorphism** on the circle. That witness is not invertible, and the gap is load-bearing for its
consumer: a symplectic `Σ`-flow *would* be invertible, so a non-invertible witness shows the
predicate is inhabited without showing it is inhabited by anything of the right kind
(`LF4/KahlerFibreMixing.lean`, honest-scope caveat (2)).

This file supplies the invertible witness: **Arnold's cat map** `(x,y) ↦ (2x+y, x+y)` on
`T² = (ℝ/ℤ)²`, a bijection, with the observable `catObs (x,y) = Re e^{2πix}`.

## Why the doubling map's proof does not transfer

`CorrelationDecayWitness` uses **no Fourier analysis**: it rotates by `2^{-(s+1)}`, which flips the
`s`-factor's sign and *fixes* the later factors because `2^t / 2^{s+1}` is an integer. That trick
needs the map to **kill** a torsion point, and a bijection cannot: `A^t ρ = 0 ⟹ ρ = 0`. So the
argument here is the standard character-orthogonality one instead, which the doubling witness
deliberately avoided.

## The construction

* `cat` is an `AddMonoidHom` (`catHom`), continuous and surjective, so it preserves Haar measure —
  `measurePreserving_cat`, from `AddMonoidHom.measurePreserving`. ⚠️ This is the step
  `MATHLIB-GAPS.md` recorded as the missing piece ("Haar invariance of a toral automorphism, which
  Mathlib does not provide"); that row was **factually wrong** and is corrected — the lemma is
  upstream, it is the `to_additive` twin of `MonoidHom.measurePreserving`.
* Characters `chi (m,n) (x,y) = e^{2πimx} e^{2πiny}` transport by the **transpose**
  `catZ (m,n) = (2m+n, m+n)` (`chi_cat`), so a correlation at lag `u` is an integral of characters
  indexed by `catZ^[u]`.
* A nontrivial character integrates to zero (`integral_chi_eq_zero`), by translating to a point
  where it takes the value `-1` (`fourier_add_half_inv_index`).
* The orbit `catZ^[u] (1,0)` has **both coordinates ≥ 1** for `u ≥ 1` (`catZ_orbit_pos`, a
  two-line `omega` induction on the Fibonacci-positive recursion), so it is never `±(1,0)` — which
  is exactly the non-degeneracy the four-term expansion needs.

## Honest scope

* **This is a witness, not a theorem about `Σ`.** It shows `HasCorrelationDecay` is inhabited by an
  *invertible* measure-preserving map; it does not show any `Σ`-flow is one. That separation is the
  same one `CorrelationDecayWitness` states, and `not_hasCorrelationDecay_of_compactGroup` still
  rules out the flows generated by a compact group.
* **Not ergodicity, and not mixing in general.** Only the single observable `catObs` is treated.
  `Ergodic cat` would need decay for *every* character (so `catZ^[u] v ≠ v` for arbitrary `v ≠ 0`,
  a genuine eigenvalue argument) plus `L²`-density of characters on `T²`; Mathlib's torus
  ergodicity is one-dimensional (`AddCircle.ergodic_zsmul`) and it has no definition of mixing at
  all. Not attempted here.
* **The concrete matrix only.** `[[2,1],[1,1]]` on the binary product, not a general hyperbolic
  `A ∈ GL_n(ℤ)`; the general case needs `Matrix.toLin` on `Fin n → AddCircle 1` and "no eigenvalue
  is a root of unity", which is a different and larger job.
* ⚠️ **Q12-d's mixing formulation was retired as mis-specified (2026-08-24)**, so this unblocks no
  live frontier item. What it does is discharge the invertibility caveat: the obstruction to a
  `Σ`-flow witness is the choice of map, not the ontic space.

Reference: Arnold–Avez, *Ergodic Problems of Classical Mechanics* (1968), §1.16 (the cat map).
In-corpus: `Mathlib/Dynamics/CorrelationDecay.lean` (the engine),
`CorrelationDecayWitness.lean` (the non-invertible sibling),
`CompactGroupNoMixing.lean` (what any witness must dodge).
-/

@[expose] public section

open MeasureTheory AddCircle Complex

namespace MeasureTheory

/-! ### The torus and its Haar measure -/

/-- The two-torus `(ℝ ⧸ ℤ)²`. ⚠️ Deliberately does **not** re-declare a `Circ` abbreviation:
`CorrelationDecayWitness.lean` already has one in this namespace, and two would collide. -/
abbrev Torus2 := AddCircle (1 : ℝ) × AddCircle (1 : ℝ)

instance instProbAddCircleOne :
    IsProbabilityMeasure (volume : Measure (AddCircle (1 : ℝ))) := ⟨by simp⟩

instance instProbTorus2 : IsProbabilityMeasure (volume : Measure Torus2) := by
  rw [Measure.volume_eq_prod]; infer_instance

instance instHaarTorus2 : (volume : Measure Torus2).IsAddHaarMeasure := by
  rw [Measure.volume_eq_prod]; infer_instance

/-! ### The cat map -/

/-- **Arnold's cat map** `(x,y) ↦ (2x + y, x + y)` on `T²`. -/
noncomputable def cat : Torus2 → Torus2 := fun p => ((2 : ℤ) • p.1 + p.2, p.1 + p.2)

lemma cat_add (a b : Torus2) : cat (a + b) = cat a + cat b := by
  refine Prod.ext ?_ ?_ <;> simp only [cat, Prod.fst_add, Prod.snd_add, smul_add] <;> abel

/-- The cat map as an additive monoid hom — the form `AddMonoidHom.measurePreserving` consumes. -/
noncomputable def catHom : Torus2 →+ Torus2 := AddMonoidHom.mk' cat cat_add

lemma continuous_cat : Continuous cat := by unfold cat; fun_prop

/-- The inverse `(x,y) ↦ (x − y, −x + 2y)`: `det [[2,1],[1,1]] = 1`. -/
noncomputable def catInv : Torus2 → Torus2 := fun q => (q.1 - q.2, -q.1 + (2 : ℤ) • q.2)

lemma cat_catInv (q : Torus2) : cat (catInv q) = q := by
  refine Prod.ext ?_ ?_ <;>
    simp only [cat, catInv, smul_sub, two_zsmul] <;> abel

lemma catInv_cat (p : Torus2) : catInv (cat p) = p := by
  refine Prod.ext ?_ ?_ <;>
    simp only [cat, catInv, smul_add, two_zsmul] <;> abel

lemma surjective_cat : Function.Surjective cat := fun q => ⟨catInv q, cat_catInv q⟩

lemma injective_cat : Function.Injective cat :=
  Function.LeftInverse.injective catInv_cat

/-- ★ **The cat map is a bijection** — the property the doubling witness lacks. -/
theorem bijective_cat : Function.Bijective cat := ⟨injective_cat, surjective_cat⟩

/-- ★ **The cat map preserves Haar measure.** A continuous surjective endomorphism of a compact
group preserves the Haar probability measure; `AddMonoidHom.measurePreserving` is exactly that. -/
theorem measurePreserving_cat :
    MeasurePreserving cat (volume : Measure Torus2) (volume : Measure Torus2) :=
  catHom.measurePreserving (μ := volume) (ν := volume) continuous_cat surjective_cat rfl

lemma measurable_cat : Measurable cat := continuous_cat.measurable

/-! ### Characters on `T²` -/

/-- The character `χ_(m,n)(x,y) = e^{2πimx} · e^{2πiny}`. -/
noncomputable def chi (v : ℤ × ℤ) : Torus2 → ℂ := fun p => fourier v.1 p.1 * fourier v.2 p.2

lemma continuous_chi (v : ℤ × ℤ) : Continuous (chi v) := by unfold chi; fun_prop

lemma norm_chi (v : ℤ × ℤ) (p : Torus2) : ‖chi v p‖ = 1 := by
  simp only [chi, norm_mul, fourier_apply, Circle.norm_coe, mul_one]

lemma integrable_chi (v : ℤ × ℤ) : Integrable (chi v) (volume : Measure Torus2) :=
  Integrable.of_bound (continuous_chi v).aestronglyMeasurable 1
    (ae_of_all _ (fun p => by rw [norm_chi]))

lemma chi_arg_add (v : ℤ × ℤ) (p q : Torus2) : chi v (p + q) = chi v p * chi v q := by
  simp only [chi, Prod.fst_add, Prod.snd_add, fourier_apply, smul_add,
    AddCircle.toCircle_add, Circle.coe_mul]
  ring

lemma chi_index_add (a b : ℤ × ℤ) (p : Torus2) : chi (a + b) p = chi a p * chi b p := by
  simp only [chi, Prod.fst_add, Prod.snd_add, fourier_add]; ring

lemma chi_index_neg (a : ℤ × ℤ) (p : Torus2) :
    chi (-a) p = (starRingEnd ℂ) (chi a p) := by
  simp only [chi, Prod.fst_neg, Prod.snd_neg, fourier_neg, map_mul]

/-- ★ **A nontrivial character integrates to zero.** Translate by a point where the character is
`-1`; Haar is translation-invariant, so the integral equals its own negative. -/
theorem integral_chi_eq_zero {v : ℤ × ℤ} (hv : v ≠ 0) :
    ∫ p, chi v p ∂(volume : Measure Torus2) = 0 := by
  obtain ⟨a, ha⟩ : ∃ a : Torus2, chi v a = -1 := by
    rcases eq_or_ne v.1 0 with h1 | h1
    · have h2 : v.2 ≠ 0 := fun h2 => hv (Prod.ext h1 h2)
      refine ⟨(0, ((1 / 2 / (v.2 : ℝ) : ℝ) : AddCircle (1 : ℝ))), ?_⟩
      simp only [chi, h1, fourier_zero]
      have := fourier_add_half_inv_index (T := (1:ℝ)) h2 one_pos (0 : AddCircle (1 : ℝ))
      rw [zero_add] at this
      rw [one_mul]
      simpa using this
    · refine ⟨(((1 / 2 / (v.1 : ℝ) : ℝ) : AddCircle (1 : ℝ)), 0), ?_⟩
      simp only [chi]
      have := fourier_add_half_inv_index (T := (1:ℝ)) h1 one_pos (0 : AddCircle (1 : ℝ))
      rw [zero_add] at this
      simp only [fourier_eval_zero, mul_one] at this ⊢
      simpa using this
  have hmp : MeasurePreserving (fun x : Torus2 => x + a) volume volume :=
    measurePreserving_add_right volume a
  have h1 : ∫ p, chi v (p + a) ∂(volume : Measure Torus2)
      = ∫ p, chi v p ∂(volume : Measure Torus2) := by
    calc ∫ p, chi v (p + a) ∂(volume : Measure Torus2)
        = ∫ y, chi v y ∂((volume : Measure Torus2).map (fun x : Torus2 => x + a)) :=
          (integral_map hmp.measurable.aemeasurable
            (by rw [hmp.map_eq]; exact (continuous_chi v).aestronglyMeasurable)).symm
      _ = ∫ p, chi v p ∂(volume : Measure Torus2) := by rw [hmp.map_eq]
  rw [integral_congr_ae (ae_of_all _ (fun p => chi_arg_add v p a)), ha] at h1
  simp only [mul_neg_one, integral_neg] at h1
  linear_combination -h1 / 2

/-- The trivial character is `1`. -/
lemma chi_zero (p : Torus2) : chi 0 p = 1 := by simp [chi]

/-! ### Transport: characters move by the transpose matrix -/

/-- The transpose action on character indices. -/
def catZ : ℤ × ℤ → ℤ × ℤ := fun v => (2 * v.1 + v.2, v.1 + v.2)

/-- Argument-additivity at a general index. ⚠️ Named apart from
`CorrelationDecayWitness.fourier_arg_add`, which is the index-`1` special case in this same
namespace; Mathlib itself has only index-additivity (`fourier_add`). -/
lemma fourier_arg_add_index (n : ℤ) (x y : AddCircle (1 : ℝ)) :
    fourier n (x + y) = fourier n x * fourier n y := by
  rw [fourier_apply, fourier_apply, fourier_apply, smul_add, AddCircle.toCircle_add,
    Circle.coe_mul]

lemma fourier_zsmul_arg (m k : ℤ) (x : AddCircle (1 : ℝ)) :
    fourier m (k • x) = fourier (m * k) x := by
  rw [fourier_apply, fourier_apply, smul_smul]

/-- ★ **The transport rule** `χ_v ∘ cat = χ_{catZ v}`. -/
lemma chi_cat (v : ℤ × ℤ) (p : Torus2) : chi v (cat p) = chi (catZ v) p := by
  obtain ⟨m, n⟩ := v
  obtain ⟨x, y⟩ := p
  simp only [chi, cat, catZ, fourier_arg_add_index, fourier_zsmul_arg, fourier_add,
    mul_comm m (2 : ℤ)]
  ring

lemma chi_cat_iterate (v : ℤ × ℤ) (u : ℕ) (p : Torus2) :
    chi v (cat^[u] p) = chi (catZ^[u] v) p := by
  induction u generalizing p with
  | zero => simp
  | succ k ih =>
      rw [Function.iterate_succ_apply, ih, Function.iterate_succ_apply']
      exact chi_cat _ _

/-- ★ **Orbit positivity.** Both coordinates of `catZ^[u+1] (1,0)` are `≥ 1`: the recursion is
Fibonacci-positive, so no eigenvalue theory is needed for the concrete matrix. -/
lemma catZ_orbit_pos : ∀ u : ℕ, 1 ≤ (catZ^[u+1] (1,0)).1 ∧ 1 ≤ (catZ^[u+1] (1,0)).2 := by
  intro u
  induction u with
  | zero => norm_num [catZ]
  | succ k ih =>
      rw [Function.iterate_succ_apply']
      obtain ⟨h1, h2⟩ := ih
      constructor <;> simp only [catZ] <;> omega

/-- The orbit never returns to `±(1,0)` after the first step — the non-degeneracy the four-term
expansion needs. -/
lemma catZ_orbit_ne (u : ℕ) :
    catZ^[u+1] (1,0) ≠ (1,0) ∧ catZ^[u+1] (1,0) ≠ (-1,0) := by
  obtain ⟨h1, h2⟩ := catZ_orbit_pos u
  constructor <;> intro hc <;> rw [hc] at h2 <;> simp at h2

/-! ### The observable and its correlations -/

/-- The observable `catObs (x,y) = Re e^{2πix}` — the same function the doubling witness uses,
read on the first coordinate. -/
noncomputable def catObs : Torus2 → ℝ := fun p => (chi (1,0) p).re

lemma measurable_catObs : Measurable catObs :=
  (Complex.measurable_re.comp (continuous_chi _).measurable)

lemma abs_catObs_le_one (p : Torus2) : |catObs p| ≤ 1 := by
  have h := norm_chi (1,0) p
  have := Complex.abs_re_le_norm (chi (1,0) p)
  rw [h] at this
  simpa [catObs] using this

lemma integrable_catObs : Integrable catObs (volume : Measure Torus2) :=
  Integrable.of_bound measurable_catObs.aestronglyMeasurable 1
    (ae_of_all _ (fun p => by simpa using abs_catObs_le_one p))

lemma integrable_catObs_iterate (u : ℕ) :
    Integrable (fun p => catObs (cat^[u] p)) (volume : Measure Torus2) :=
  Integrable.of_bound
    (measurable_catObs.comp (measurable_cat.iterate u)).aestronglyMeasurable 1
    (ae_of_all _ (fun p => by simpa using abs_catObs_le_one _))

lemma integrable_catObs_pair (u : ℕ) :
    Integrable (fun p => catObs p * catObs (cat^[u] p)) (volume : Measure Torus2) :=
  Integrable.of_bound
    ((measurable_catObs.mul
      (measurable_catObs.comp (measurable_cat.iterate u))).aestronglyMeasurable) 1
    (ae_of_all _ (fun p => by
      have h1 := abs_catObs_le_one p
      have h2 := abs_catObs_le_one (cat^[u] p)
      have : |catObs p * catObs (cat^[u] p)| ≤ 1 := by
        rw [abs_mul]; nlinarith [abs_nonneg (catObs p), abs_nonneg (catObs (cat^[u] p))]
      simpa using this))

/-- The four-term expansion of a product of real parts. -/
lemma re_mul_re (z w : ℂ) :
    z.re * w.re
      = ((z * w + z * (starRingEnd ℂ) w + (starRingEnd ℂ) z * w
          + (starRingEnd ℂ) z * (starRingEnd ℂ) w) / 4).re := by
  simp
  ring

/-- The mean of the observable is zero. -/
lemma integral_catObs : ∫ p, catObs p ∂(volume : Measure Torus2) = 0 := by
  have hv : ((1, 0) : ℤ × ℤ) ≠ 0 := by
    intro h; simpa using congrArg Prod.fst h
  have h : ∫ p, catObs p ∂(volume : Measure Torus2)
      = RCLike.re (∫ p, chi (1,0) p ∂(volume : Measure Torus2)) := by
    rw [← integral_re (integrable_chi (1,0))]
    rfl
  rw [h, integral_chi_eq_zero hv]
  simp

/-- The real part of a character integrates to `1` at the trivial index and `0` otherwise. -/
lemma integral_chi_re (z : ℤ × ℤ) :
    ∫ p, (chi z p).re ∂(volume : Measure Torus2) = if z = 0 then 1 else 0 := by
  have hre : ∫ p, (chi z p).re ∂(volume : Measure Torus2)
      = RCLike.re (∫ p, chi z p ∂(volume : Measure Torus2)) := by
    rw [← integral_re (integrable_chi z)]; rfl
  rw [hre]
  by_cases hz : z = 0
  · subst hz
    simp [chi_zero]
  · rw [integral_chi_eq_zero hz, if_neg hz]
    simp

/-- The lag-`u` orbit index of the base character `(1,0)`. -/
def catIdx (u : ℕ) : ℤ × ℤ := catZ^[u] (1, 0)

/-- The four-character expansion of the lag-`u` integrand. -/
lemma catObs_mul_iterate (u : ℕ) (p : Torus2) :
    catObs p * catObs (cat^[u] p)
      = ((chi ((1,0) + catIdx u) p).re + (chi ((1,0) + -catIdx u) p).re
          + (chi (-(1,0) + catIdx u) p).re + (chi (-(1,0) + -catIdx u) p).re) / 4 := by
  have hshift : catObs (cat^[u] p) = (chi (catIdx u) p).re := by
    rw [catObs, chi_cat_iterate]; rfl
  rw [catObs, hshift, re_mul_re]
  rw [chi_index_add, chi_index_add, chi_index_add, chi_index_add]
  rw [chi_index_neg, chi_index_neg]
  simp [Complex.add_re]

/-- Additivity of the integral over a four-term real sum, in the shape the expansion produces. -/
lemma integral_four (f₁ f₂ f₃ f₄ : Torus2 → ℝ)
    (h₁ : Integrable f₁ (volume : Measure Torus2))
    (h₂ : Integrable f₂ (volume : Measure Torus2))
    (h₃ : Integrable f₃ (volume : Measure Torus2))
    (h₄ : Integrable f₄ (volume : Measure Torus2)) :
    ∫ p, (f₁ p + f₂ p + f₃ p + f₄ p) ∂(volume : Measure Torus2)
      = (∫ p, f₁ p ∂(volume : Measure Torus2)) + (∫ p, f₂ p ∂(volume : Measure Torus2))
        + (∫ p, f₃ p ∂(volume : Measure Torus2)) + (∫ p, f₄ p ∂(volume : Measure Torus2)) := by
  have e₁₂ := integral_add h₁ h₂
  have e₁₂₃ := integral_add (h₁.add h₂) h₃
  have e₁₂₃₄ := integral_add ((h₁.add h₂).add h₃) h₄
  simp only [Pi.add_apply] at e₁₂ e₁₂₃ e₁₂₃₄
  rw [e₁₂₃₄, e₁₂₃, e₁₂]

/-- ★ **The correlations vanish at every nonzero lag**, and equal `1/2` at lag zero. -/
theorem integral_catObs_pair (u : ℕ) :
    ∫ p, catObs p * catObs (cat^[u] p) ∂(volume : Measure Torus2)
      = if u = 0 then 1/2 else 0 := by
  have hint : ∀ z : ℤ × ℤ, Integrable (fun p => (chi z p).re) (volume : Measure Torus2) :=
    fun z => (integrable_chi z).re
  rw [integral_congr_ae (ae_of_all _ (catObs_mul_iterate u))]
  rw [integral_div]
  rw [integral_four _ _ _ _ (hint _) (hint _) (hint _) (hint _)]
  rw [integral_chi_re, integral_chi_re, integral_chi_re, integral_chi_re]
  rcases Nat.eq_zero_or_pos u with hu | hu
  · subst hu
    simp only [catIdx, Function.iterate_zero, id_eq]
    norm_num
  · obtain ⟨k, rfl⟩ : ∃ k, u = k + 1 := ⟨u - 1, by omega⟩
    -- ⚠️ state the positivity with `catIdx` as the ATOM: `catZ^[k+1] (1,0)` is defeq but not
    -- syntactically equal, and `omega` matches atoms syntactically.
    have hs : 1 ≤ (catIdx (k+1)).2 := (catZ_orbit_pos k).2
    have hA : ((1,0) + catIdx (k+1) : ℤ × ℤ) ≠ 0 := by
      intro h; have h' := congrArg Prod.snd h; simp at h'; omega
    have hB : ((1,0) + -catIdx (k+1) : ℤ × ℤ) ≠ 0 := by
      intro h; have h' := congrArg Prod.snd h; simp at h'; omega
    have hC : (-(1,0) + catIdx (k+1) : ℤ × ℤ) ≠ 0 := by
      intro h; have h' := congrArg Prod.snd h; simp at h'; omega
    have hD : (-(1,0) + -catIdx (k+1) : ℤ × ℤ) ≠ 0 := by
      intro h; have h' := congrArg Prod.snd h; simp at h'; omega
    rw [if_neg hA, if_neg hB, if_neg hC, if_neg hD, if_neg (by omega : ¬(k+1 = 0))]
    norm_num

/-! ### ★★ The witness -/

/-- The finitely-supported decay envelope: `1/2` at lag zero, `0` afterwards. -/
noncomputable def catEnv : ℕ → ℝ := fun u => if u = 0 then 1/2 else 0

/-- ★★ **An INVERTIBLE map satisfies `HasCorrelationDecay`.** Arnold's cat map on `T²`, with the
observable `Re e^{2πix}`, has vanishing correlations at every nonzero lag. Unlike the doubling
witness this map is a bijection (`bijective_cat`), so the predicate is inhabited by a map of the
kind a symplectic `Σ`-flow could be. -/
theorem cat_hasCorrelationDecay :
    HasCorrelationDecay (volume : Measure Torus2) cat catObs catEnv := by
  refine HasCorrelationDecay.of_measurePreserving measurePreserving_cat measurable_catObs ?_
  intro u
  rw [integral_catObs_pair, integral_catObs]
  simp only [catEnv]
  by_cases hu : u = 0 <;> simp [hu]

/-- ★ **The witness is not the trivial constant observable**: `⟨f²⟩ = 1/2 ≠ 0 = ⟨f⟩²`. -/
theorem cat_nontrivial :
    ∫ p, catObs p * catObs p ∂(volume : Measure Torus2)
      ≠ (∫ p, catObs p ∂(volume : Measure Torus2)) ^ 2 := by
  have h0 := integral_catObs_pair 0
  simp only [Function.iterate_zero, id_eq] at h0
  rw [h0, integral_catObs]
  norm_num

end MeasureTheory
