/-
Copyright (c) 2026 Zayn Blore. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zayn Blore
-/
module

public import CsdLean4.Mathlib.Dynamics.CorrelationDecay
public import CsdLean4.Mathlib.Topology.Algebra.CompactRecurrence

/-!
# No flow generated by a compact group has decaying correlations

**Category:** 1-Mathlib. No CSD content.

Two facts the corpus already owns, joined:

* `HasCorrelationDecay.integral_mul_self_eq_of_recurrent` — a correlation that keeps returning to
  its lag-zero value cannot decay to `⟨f⟩²`;
* `exists_le_pow_mem_of_compactSpace` — the powers of any element of a compact group keep returning
  to the identity.

★★ `not_hasCorrelationDecay_of_compactGroup` is the consequence: **for a flow of the form `Ψ U`,
where `Ψ` turns powers of `U` into iterates and `U` lives in a compact group, correlation decay is
impossible for any observable of nonzero variance** — provided only that the correlation function
`V ↦ ∫ f(x)·f(Ψ V x)` is continuous at `1`.

## Why it is stated with a bare `Ψ`, not a `MulAction`

The two flows this is applied to are an action of the unitary group and a *shift on a torus*. The
second is additive and is not registered as an `AddAction` anywhere, so demanding an action
typeclass would exclude it. All the argument uses is `(Ψ U)^[n] = Ψ (U ^ n)`, so that is what it
asks for — `hpow` — and `Ψ 1 = id` comes free from it at `n = 0`. Each result carries a
`to_additive` twin, which is what lets one proof serve both a multiplicative group action and an
additive shift.

## What it does and does not say

It does **not** say mixing is impossible. It says mixing is impossible *for this class of
generators*: genuinely mixing systems exist (`MeasureTheory.circ_hasCorrelationDecay` is one, on the
circle doubling map), and they are exactly the ones that are **not** compact-group translations.
The theorem is therefore a statement about where to look, not a no-go for the phenomenon.

Reference: `specs/q12-fibre-mechanism-scoping.md` (`W1`, of which this is the general form);
`specs/equilibration-arc-plan.md` (E4/E6, the source); `specs/future-work.md`. Consumers:
`CSD.Thermo.not_hasCorrelationDecay_blockPop_of_unitary` (the unitary base action) and
`CSD.LF4.KahlerFlow.not_hasCorrelationDecay_kFlow` (the `T²` fibre shift).
-/

@[expose] public section

open MeasureTheory Filter Topology

namespace MeasureTheory

variable {G X : Type*} [MeasurableSpace X] [Group G] [TopologicalSpace G]
  [IsTopologicalGroup G] [CompactSpace G]

omit [MeasurableSpace X] [TopologicalSpace G] [IsTopologicalGroup G] [CompactSpace G] in
/-- A flow whose iterates are the powers of its generator fixes points at `1`. -/
@[to_additive]
lemma apply_one_of_iterate_eq_pow {Ψ : G → X → X} {U : G}
    (hpow : ∀ (n : ℕ) (x : X), (Ψ U)^[n] x = Ψ (U ^ n) x) (x : X) : Ψ 1 x = x := by
  simpa using (hpow 0 x).symm

/-- **The correlation of a compact-group flow recurs.** For any `δ > 0` and any bound `M` there is a
lag `u ≥ M` at which the correlation is within `δ` of its lag-zero value.

This is `exists_le_pow_mem_of_compactSpace` transported along the correlation function: continuity
at `1` turns the neighbourhood of the identity into a neighbourhood of `⟨f²⟩`. -/
@[to_additive]
theorem exists_le_abs_correlation_sub_lt_of_compactGroup (μ : Measure X) (Ψ : G → X → X)
    (f : X → ℝ) (U : G) (hpow : ∀ (n : ℕ) (x : X), (Ψ U)^[n] x = Ψ (U ^ n) x)
    (hcont : ContinuousAt (fun V : G => ∫ x, f x * f (Ψ V x) ∂μ) 1)
    {δ : ℝ} (hδ : 0 < δ) (M : ℕ) :
    ∃ u, M ≤ u ∧
      |(∫ x, f x * f ((Ψ U)^[u] x) ∂μ) - (∫ x, f x * f x ∂μ)| < δ := by
  set g : G → ℝ := fun V => ∫ x, f x * f (Ψ V x) ∂μ with hg
  have hg1 : g 1 = ∫ x, f x * f x ∂μ :=
    integral_congr_ae (ae_of_all _ (fun x => by
      simp only [apply_one_of_iterate_eq_pow hpow]))
  have hnhds : {V : G | |g V - g 1| < δ} ∈ 𝓝 (1 : G) := by
    refine Filter.mem_of_superset (hcont (Metric.ball_mem_nhds (g 1) hδ)) (fun V hV => ?_)
    simpa [Real.dist_eq] using hV
  obtain ⟨u, hMu, hu⟩ := exists_le_pow_mem_of_compactSpace U hnhds M
  refine ⟨u, hMu, ?_⟩
  have hiter : ∫ x, f x * f ((Ψ U)^[u] x) ∂μ = g (U ^ u) :=
    integral_congr_ae (ae_of_all _ (fun x => by simp only [hpow]))
  rw [hiter, ← hg1]
  exact hu

/-- ★★ **No flow generated by a compact group has decaying correlations.**

For `Ψ U` with `U` in a compact group, an observable whose variance is nonzero cannot have a
summable decay envelope. Compare `HasCorrelationDecay.integral_mul_self_eq_of_periodic`, which is
the same obstruction in the special case where the return is exact.

The hypotheses are the minimum: `hpow` makes `Ψ` a flow along the powers of `U`, and `hcont` is what
lets a neighbourhood of the identity be read as a neighbourhood of the lag-zero correlation.
`continuousAt_correlation_of_abs_sub_le` supplies `hcont` from a uniform modulus. -/
@[to_additive]
theorem not_hasCorrelationDecay_of_compactGroup (μ : Measure X) (Ψ : G → X → X) (f : X → ℝ)
    (U : G) {ε : ℕ → ℝ} (hpow : ∀ (n : ℕ) (x : X), (Ψ U)^[n] x = Ψ (U ^ n) x)
    (hcont : ContinuousAt (fun V : G => ∫ x, f x * f (Ψ V x) ∂μ) 1)
    (hvar : (∫ x, f x * f x ∂μ) ≠ (∫ y, f y ∂μ) ^ 2) (hsum : Summable ε) :
    ¬ HasCorrelationDecay μ (Ψ U) f ε := fun hdec =>
  hvar (hdec.integral_mul_self_eq_of_recurrent
    (fun _ hδ M =>
      exists_le_abs_correlation_sub_lt_of_compactGroup μ Ψ f U hpow hcont hδ M) hsum)

omit [IsTopologicalGroup G] [CompactSpace G] in
/-- A **uniform modulus** vanishing at the identity gives the continuity the no-go needs.

This is the shape a physical estimate actually comes in: a bound on how far the correlation can move
when the generator moves, in terms of a continuous deviation of the generator from `1`. -/
@[to_additive continuousAt_correlation_of_abs_sub_le_add]
theorem continuousAt_correlation_of_abs_sub_le (μ : Measure X) (Ψ : G → X → X) (f : X → ℝ)
    {D : G → ℝ} (hD : Continuous D) (hD1 : D 1 = 0) (hone : ∀ x : X, Ψ 1 x = x)
    (hbd : ∀ V : G, |(∫ x, f x * f (Ψ V x) ∂μ) - (∫ x, f x * f x ∂μ)| ≤ D V) :
    ContinuousAt (fun V : G => ∫ x, f x * f (Ψ V x) ∂μ) 1 := by
  set g : G → ℝ := fun V => ∫ x, f x * f (Ψ V x) ∂μ with hg
  have hg1 : g 1 = ∫ x, f x * f x ∂μ :=
    integral_congr_ae (ae_of_all _ (fun x => by simp only [hone]))
  have hD0 : Tendsto D (𝓝 (1 : G)) (𝓝 0) := by
    have h : Tendsto D (𝓝 (1 : G)) (𝓝 (D 1)) := hD.continuousAt
    rwa [hD1] at h
  have hsq : Tendsto (fun V => g V - g 1) (𝓝 (1 : G)) (𝓝 0) := by
    refine squeeze_zero_norm (fun V => ?_) hD0
    rw [Real.norm_eq_abs, hg1]
    exact hbd V
  have hlim := hsq.add_const (g 1)
  simp only [sub_add_cancel, zero_add] at hlim
  exact hlim

end MeasureTheory
