/-
Copyright (c) 2026 Zayn Blore. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zayn Blore
-/
module

public import CsdLean4.Mathlib.Analysis.NormedSpace.TrotterGeneral
public import Mathlib.MeasureTheory.Integral.DominatedConvergence
public import Mathlib.Analysis.SpecialFunctions.Integrals.Basic
public import Mathlib.Analysis.SpecificLimits.Basic

/-!
# A bounded perturbation of a strongly continuous contraction semigroup

**Category:** 1-Mathlib (CSD-free; staged for upstream).

Let `S` be a strongly continuous contraction semigroup on a Banach space `E` (`IsContractionSemigroup`:
`S (s + t) = S s * S t`, `‖S t‖ ≤ 1`, `t ↦ S t ψ` continuous; extended by the identity to negative
times so that every integrand below is globally continuous), and `B : E →L[ℂ] E` bounded. No
generator is named: the semigroup is the object. The **Dyson series**

  `D₀(t) ψ = S t ψ`,  `Dₙ₊₁(t) ψ = ∫₀ᵗ S (t − s) (B (Dₙ(s) ψ)) ds`

converges to the **perturbed semigroup** `𝒮(t) ψ = ∑ₙ Dₙ(t) ψ`, the unique solution of the Duhamel
(Volterra) equation `𝒮(t) ψ = S t ψ + ∫₀ᵗ S (t − s) (B (𝒮(s) ψ)) ds`, and the **Trotter product
formula** holds: `(S (t/n) · exp ((t/n) B))ⁿ ψ → 𝒮(t) ψ`.

This is `Analysis/Matrix/DysonSeries.lean` with `exp (t A)` replaced by a semigroup and the matrix
Bochner integrals by vector-valued ones. It is the engine of the continuum path integral (Feynman–Kac
and Nelson's theorem, `specs/feynman-continuum-scoping.md` FC-1): for the heat semigroup and `B = −V`
the perturbed semigroup is `e^{−t(H₀ + V)}` without ever writing `H₀`.

* `IsContractionSemigroup S` — the predicate; `continuous_uncurry` — strong continuity plus the
  uniform bound give joint continuity of `(t, ψ) ↦ S t ψ`;
* `dysonTerm S B n t ψ` — the terms; `continuous_dysonTerm` (in `t`); `dysonTerm_add`,
  `dysonTerm_smul` (linear in `ψ`); ★ `norm_dysonTerm_le` — `‖Dₙ(t) ψ‖ ≤ (‖B‖ t)ⁿ / n! · ‖ψ‖`;
* `summable_dysonTerm`, `dysonSum S B t ψ = ∑' n, Dₙ(t) ψ`, ★ `norm_dysonSum_le` —
  `‖𝒮(t) ψ‖ ≤ e^{‖B‖ t} ‖ψ‖`, `continuous_dysonSum`;
* ★ `dysonSum_eq_add_integral` — **the Duhamel equation**; ★ `eq_dysonSum_of_duhamel` — **its
  uniqueness**: a continuous solution on `[0, T]` is the Dyson sum (the iterated Volterra bound
  `M (‖B‖ t)ⁿ / n! → 0`); ★★ `dysonSum_add_time` — **the semigroup law** `𝒮(t + s) = 𝒮(t) 𝒮(s)`, by
  uniqueness;
* `IsContractionSemigroup.perturbed hS B t : E →L[ℂ] E` — the bundled perturbed semigroup, with
  `perturbed_apply`, `norm_perturbed_le`, `perturbed_zero`, ★★ `perturbed_add`;
* `trotterStep S B h = S h * exp (h • B)`; ★ `norm_trotterStep_apply_sub_dysonSum_le` — the
  one-step defect `‖(S h · e^{hB}) χ − 𝒮(h) χ‖ ≤ 2 (‖B‖ h)² e^{‖B‖ h} ‖χ‖ + h ω` with `ω` the
  oscillation of `S h (B χ) − S (h − s) (B (S s χ))` on `[0, h]`; `exists_delta_of_isCompact` —
  that oscillation is uniformly small on a compact set; `pow_apply_sub_eq_sum` — telescoping;
  ★★ `tendsto_trotterStep_pow_apply` — **the Trotter product formula**,
  `(S (t/n) · exp ((t/n) B))ⁿ ψ → 𝒮(t) ψ`, by telescoping against the semigroup law along the
  compact orbit `{𝒮(s) ψ : s ∈ [0, t]}`;
* `IsContractionSemigroup.of_group` — a strongly continuous contraction group restricted to
  `t ≥ 0` is a contraction semigroup: the real-time (unitary) case.

**Three ways to the same operator.** `𝒮(t)` is the sum of the Dyson series, the unique solution of
the Duhamel equation, and the Trotter limit of time-sliced products; the module proves all three
agree. This is what lets the continuum path integral be *compared* across approaches: whatever
construction satisfies the Duhamel equation is `𝒮`.

## Honest scope

⚠️ **The semigroup is the primitive.** Nothing here asserts that `S` is generated by an operator, or
that `𝒮` is generated by `A + B`; at the pin there are no unbounded generators. `𝒮` is defined by
the series and characterised by the Duhamel equation, which is what identifies it with any other
construction of "`e^{t(A+B)}`".

References: F. J. Dyson, Phys. Rev. 75, 486 (1949); H. F. Trotter, Proc. AMS 10, 545 (1959);
K.-J. Engel, R. Nagel, *One-Parameter Semigroups for Linear Evolution Equations*, III.1 (bounded
perturbations) and III.5 (product formulas); `Analysis/Matrix/DysonSeries.lean`;
`Analysis/NormedSpace/TrotterGeneral.lean`; `specs/feynman-continuum-scoping.md`;
`specs/BACKLOG.md` #36(c).
-/

@[expose] public section

open scoped Nat Topology
open NormedSpace MeasureTheory intervalIntegral Filter

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℂ E] [CompleteSpace E]

/-! ### Strongly continuous contraction semigroups -/

/-- **A strongly continuous contraction semigroup** on `E`, extended by the identity to negative
times: `S (s + t) = S s * S t` for `s, t ≥ 0`, `‖S t‖ ≤ 1`, and `t ↦ S t ψ` continuous. -/
structure IsContractionSemigroup (S : ℝ → E →L[ℂ] E) : Prop where
  eq_one_of_nonpos : ∀ t, t ≤ 0 → S t = 1
  map_add : ∀ s t, 0 ≤ s → 0 ≤ t → S (s + t) = S s * S t
  norm_le_one : ∀ t, ‖S t‖ ≤ 1
  continuous_apply : ∀ ψ, Continuous fun t => S t ψ

namespace IsContractionSemigroup

variable {S : ℝ → E →L[ℂ] E} (hS : IsContractionSemigroup S)
include hS

omit [CompleteSpace E] in
theorem map_zero : S 0 = 1 := hS.eq_one_of_nonpos 0 le_rfl

omit [CompleteSpace E] in
theorem norm_apply_le (t : ℝ) (ψ : E) : ‖S t ψ‖ ≤ ‖ψ‖ :=
  le_trans (ContinuousLinearMap.le_opNorm _ _)
    (mul_le_of_le_one_left (norm_nonneg _) (hS.norm_le_one t))

omit [CompleteSpace E] in
/-- Strong continuity and the uniform bound give joint continuity of `(t, ψ) ↦ S t ψ`. -/
theorem continuous_uncurry : Continuous fun p : ℝ × E => S p.1 p.2 := by
  rw [continuous_iff_continuousAt]
  rintro ⟨t₀, ψ₀⟩
  rw [Metric.continuousAt_iff]
  intro ε hε
  obtain ⟨δ, hδ, hδ'⟩ := Metric.continuousAt_iff.mp ((hS.continuous_apply ψ₀).continuousAt (x := t₀))
    (ε / 2) (by positivity)
  refine ⟨min δ (ε / 2), lt_min hδ (by positivity), ?_⟩
  rintro ⟨t, ψ⟩ hp
  rw [Prod.dist_eq, max_lt_iff] at hp
  obtain ⟨ht, hψ⟩ := hp
  have h1 : dist (S t ψ₀) (S t₀ ψ₀) < ε / 2 := hδ' (lt_of_lt_of_le ht (min_le_left _ _))
  have h2 : ‖S t ψ - S t ψ₀‖ < ε / 2 := by
    rw [← map_sub]
    exact lt_of_le_of_lt (hS.norm_apply_le t _)
      (lt_of_lt_of_le (by rwa [dist_eq_norm] at hψ) (min_le_right _ _))
  calc dist (S t ψ) (S t₀ ψ₀) ≤ dist (S t ψ) (S t ψ₀) + dist (S t ψ₀) (S t₀ ψ₀) := dist_triangle _ _ _
    _ < ε / 2 + ε / 2 := by rw [dist_eq_norm]; exact add_lt_add h2 h1
    _ = ε := add_halves ε

omit [CompleteSpace E] hS in
/-- A strongly continuous one-parameter group of contractions (a unitary group, say), restricted
to `t ≥ 0` and extended by the identity, is a contraction semigroup: the real-time case of
everything below. -/
theorem of_group (U : ℝ → E →L[ℂ] E) (h0 : U 0 = 1) (hadd : ∀ s t, U (s + t) = U s * U t)
    (hnorm : ∀ t, ‖U t‖ ≤ 1) (hcont : ∀ ψ, Continuous fun t => U t ψ) :
    IsContractionSemigroup fun t => if 0 ≤ t then U t else 1 where
  eq_one_of_nonpos t ht := by
    by_cases h : 0 ≤ t
    · rw [if_pos h, le_antisymm ht h, h0]
    · rw [if_neg h]
  map_add s t hs ht := by rw [if_pos hs, if_pos ht, if_pos (add_nonneg hs ht), hadd]
  norm_le_one t := by
    split_ifs with h
    · exact hnorm t
    · exact ContinuousLinearMap.norm_id_le
  continuous_apply ψ := by
    have : (fun t => (if 0 ≤ t then U t else 1) ψ) = fun t => if 0 ≤ t then U t ψ else ψ := by
      funext t
      split_ifs <;> simp
    rw [this]
    exact (hcont ψ).if_le continuous_const continuous_const continuous_id fun t ht => by
      rw [← ht, h0, one_apply_eq_self]

end IsContractionSemigroup

/-! ### The Dyson series -/

namespace ContractionSemigroup

variable (S : ℝ → E →L[ℂ] E) (B : E →L[ℂ] E)

/-- **The Dyson terms**: `D₀(t) ψ = S t ψ`, `Dₙ₊₁(t) ψ = ∫₀ᵗ S (t − s) (B (Dₙ(s) ψ)) ds`. -/
noncomputable def dysonTerm : ℕ → ℝ → E → E
  | 0 => fun t ψ => S t ψ
  | n + 1 => fun t ψ => ∫ s in (0 : ℝ)..t, S (t - s) (B (dysonTerm n s ψ))

omit [CompleteSpace E] in
theorem dysonTerm_zero (t : ℝ) (ψ : E) : dysonTerm S B 0 t ψ = S t ψ := rfl

omit [CompleteSpace E] in
theorem dysonTerm_succ (n : ℕ) (t : ℝ) (ψ : E) :
    dysonTerm S B (n + 1) t ψ = ∫ s in (0 : ℝ)..t, S (t - s) (B (dysonTerm S B n s ψ)) := rfl

variable {S}

omit [CompleteSpace E] in
theorem continuous_dysonTerm (hS : IsContractionSemigroup S) (n : ℕ) (ψ : E) :
    Continuous fun t => dysonTerm S B n t ψ := by
  induction n with
  | zero => exact hS.continuous_apply ψ
  | succ n ih =>
    refine intervalIntegral.continuous_parametric_intervalIntegral_of_continuous
      (f := fun t s => S (t - s) (B (dysonTerm S B n s ψ))) ?_ continuous_id
    exact hS.continuous_uncurry.comp
      ((continuous_fst.sub continuous_snd).prodMk (B.continuous.comp (ih.comp continuous_snd)))

omit [CompleteSpace E] in
theorem continuous_dysonTerm_integrand (hS : IsContractionSemigroup S) (n : ℕ) (t : ℝ) (ψ : E) :
    Continuous fun s => S (t - s) (B (dysonTerm S B n s ψ)) :=
  hS.continuous_uncurry.comp
    ((continuous_const.sub continuous_id).prodMk
      (B.continuous.comp (continuous_dysonTerm B hS n ψ)))

omit [CompleteSpace E] in
theorem dysonTerm_add (hS : IsContractionSemigroup S) (n : ℕ) (t : ℝ) (ψ χ : E) :
    dysonTerm S B n t (ψ + χ) = dysonTerm S B n t ψ + dysonTerm S B n t χ := by
  induction n generalizing t with
  | zero => simp only [dysonTerm_zero, map_add]
  | succ n ih =>
    simp only [dysonTerm_succ, ih, map_add]
    exact intervalIntegral.integral_add
      ((continuous_dysonTerm_integrand B hS n t ψ).intervalIntegrable _ _)
      ((continuous_dysonTerm_integrand B hS n t χ).intervalIntegrable _ _)

omit [CompleteSpace E] in
theorem dysonTerm_smul (n : ℕ) (t : ℝ) (c : ℂ) (ψ : E) :
    dysonTerm S B n t (c • ψ) = c • dysonTerm S B n t ψ := by
  induction n generalizing t with
  | zero => simp only [dysonTerm_zero, map_smul]
  | succ n ih =>
    simp only [dysonTerm_succ, ih, map_smul]
    exact intervalIntegral.integral_smul c _

omit [CompleteSpace E] in
/-- ★ `‖Dₙ(t) ψ‖ ≤ (‖B‖ t)ⁿ / n! · ‖ψ‖` for `0 ≤ t`. -/
theorem norm_dysonTerm_le (hS : IsContractionSemigroup S) (n : ℕ) {t : ℝ} (ht : 0 ≤ t) (ψ : E) :
    ‖dysonTerm S B n t ψ‖ ≤ (‖B‖ * t) ^ n / n ! * ‖ψ‖ := by
  induction n generalizing t with
  | zero =>
    rw [dysonTerm_zero]
    simpa using hS.norm_apply_le t ψ
  | succ n ih =>
    rw [dysonTerm_succ]
    have hint : ∀ s ∈ Set.Icc (0 : ℝ) t,
        ‖S (t - s) (B (dysonTerm S B n s ψ))‖ ≤ ‖B‖ * ((‖B‖ * s) ^ n / n ! * ‖ψ‖) := by
      intro s hs
      calc ‖S (t - s) (B (dysonTerm S B n s ψ))‖
          ≤ ‖B (dysonTerm S B n s ψ)‖ := hS.norm_apply_le _ _
        _ ≤ ‖B‖ * ‖dysonTerm S B n s ψ‖ := B.le_opNorm _
        _ ≤ ‖B‖ * ((‖B‖ * s) ^ n / n ! * ‖ψ‖) := by gcongr; exact ih hs.1
    calc ‖∫ s in (0 : ℝ)..t, S (t - s) (B (dysonTerm S B n s ψ))‖
        ≤ ∫ s in (0 : ℝ)..t, ‖S (t - s) (B (dysonTerm S B n s ψ))‖ :=
          intervalIntegral.norm_integral_le_integral_norm ht
      _ ≤ ∫ s in (0 : ℝ)..t, ‖B‖ * ((‖B‖ * s) ^ n / n ! * ‖ψ‖) := by
          refine intervalIntegral.integral_mono_on ht
            ((continuous_dysonTerm_integrand B hS n t ψ).norm.intervalIntegrable _ _)
            (Continuous.intervalIntegrable (by fun_prop) _ _) hint
      _ = (‖B‖ * t) ^ (n + 1) / (n + 1)! * ‖ψ‖ := by
          simp_rw [mul_pow, mul_div_assoc, mul_assoc]
          rw [intervalIntegral.integral_const_mul, intervalIntegral.integral_const_mul,
            intervalIntegral.integral_mul_const, intervalIntegral.integral_div, integral_pow,
            Nat.factorial_succ]
          push_cast
          field_simp
          ring

omit [CompleteSpace E] in
theorem summable_norm_dysonTerm (hS : IsContractionSemigroup S) {t : ℝ} (ht : 0 ≤ t) (ψ : E) :
    Summable fun n => ‖dysonTerm S B n t ψ‖ :=
  Summable.of_nonneg_of_le (fun _ => norm_nonneg _) (fun n => norm_dysonTerm_le B hS n ht ψ)
    ((Real.summable_pow_div_factorial (‖B‖ * t)).mul_right _)

theorem summable_dysonTerm (hS : IsContractionSemigroup S) {t : ℝ} (ht : 0 ≤ t) (ψ : E) :
    Summable fun n => dysonTerm S B n t ψ :=
  (summable_norm_dysonTerm B hS ht ψ).of_norm

variable (S) in
/-- **The Dyson sum** `𝒮(t) ψ = ∑' n, Dₙ(t) ψ`, at time `max t 0` (the identity for `t ≤ 0`). -/
noncomputable def dysonSum (t : ℝ) (ψ : E) : E := ∑' n, dysonTerm S B n (max t 0) ψ

omit [CompleteSpace E] in
theorem dysonSum_of_nonneg {t : ℝ} (ht : 0 ≤ t) (ψ : E) :
    dysonSum S B t ψ = ∑' n, dysonTerm S B n t ψ := by
  rw [dysonSum, max_eq_left ht]

theorem hasSum_dysonTerm (hS : IsContractionSemigroup S) {t : ℝ} (ht : 0 ≤ t) (ψ : E) :
    HasSum (fun n => dysonTerm S B n t ψ) (dysonSum S B t ψ) := by
  rw [dysonSum_of_nonneg B ht]
  exact (summable_dysonTerm B hS ht ψ).hasSum

omit [CompleteSpace E] in
/-- ★ `‖𝒮(t) ψ‖ ≤ e^{‖B‖ t} ‖ψ‖` for `0 ≤ t`. -/
theorem norm_dysonSum_le (hS : IsContractionSemigroup S) {t : ℝ} (ht : 0 ≤ t) (ψ : E) :
    ‖dysonSum S B t ψ‖ ≤ Real.exp (‖B‖ * t) * ‖ψ‖ := by
  rw [dysonSum_of_nonneg B ht]
  have hsum := (Real.summable_pow_div_factorial (‖B‖ * t)).mul_right ‖ψ‖
  calc ‖∑' n, dysonTerm S B n t ψ‖
      ≤ ∑' n, ‖dysonTerm S B n t ψ‖ :=
        norm_tsum_le_tsum_norm (summable_norm_dysonTerm B hS ht ψ)
    _ ≤ ∑' n, (‖B‖ * t) ^ n / n ! * ‖ψ‖ :=
        (summable_norm_dysonTerm B hS ht ψ).tsum_le_tsum
          (fun n => norm_dysonTerm_le B hS n ht ψ) hsum
    _ = Real.exp (‖B‖ * t) * ‖ψ‖ := by
        rw [tsum_mul_right, Real.exp_eq_exp_ℝ, ← (expSeries_div_hasSum_exp (‖B‖ * t)).tsum_eq]

theorem dysonSum_add (hS : IsContractionSemigroup S) (t : ℝ) (ψ χ : E) :
    dysonSum S B t (ψ + χ) = dysonSum S B t ψ + dysonSum S B t χ := by
  simp only [dysonSum, dysonTerm_add B hS]
  exact (summable_dysonTerm B hS (le_max_right t 0) ψ).tsum_add
    (summable_dysonTerm B hS (le_max_right t 0) χ)

omit [CompleteSpace E] in
theorem dysonSum_smul (t : ℝ) (c : ℂ) (ψ : E) :
    dysonSum S B t (c • ψ) = c • dysonSum S B t ψ := by
  simp only [dysonSum, dysonTerm_smul B]
  exact tsum_const_smul'' c

omit [CompleteSpace E] in
theorem dysonSum_zero (hS : IsContractionSemigroup S) (ψ : E) : dysonSum S B 0 ψ = ψ := by
  rw [dysonSum_of_nonneg B le_rfl]
  have h : ∀ n, dysonTerm S B n 0 ψ = if n = 0 then ψ else 0 := by
    intro n
    cases n with
    | zero => simp [dysonTerm_zero, hS.map_zero]
    | succ n => simp [dysonTerm_succ]
  simp_rw [h]
  exact tsum_ite_eq 0 (fun _ => ψ)

/-- The Dyson sum is continuous in time, by uniform convergence of the series on `[0, T]`. -/
theorem continuousOn_dysonSum_Iic (hS : IsContractionSemigroup S) (ψ : E) (T : ℝ) :
    ContinuousOn (fun t => dysonSum S B t ψ) (Set.Iic T) := by
  simp only [dysonSum]
  refine continuousOn_tsum (u := fun n => (‖B‖ * max T 0) ^ n / n ! * ‖ψ‖)
    (fun n => ((continuous_dysonTerm B hS n ψ).comp (continuous_id.max continuous_const)).continuousOn)
    ((Real.summable_pow_div_factorial (‖B‖ * max T 0)).mul_right _) ?_
  intro n t ht
  refine le_trans (norm_dysonTerm_le B hS n (le_max_right t 0) ψ) ?_
  gcongr
  exact Set.mem_Iic.mp ht

theorem continuous_dysonSum (hS : IsContractionSemigroup S) (ψ : E) :
    Continuous fun t => dysonSum S B t ψ := by
  rw [continuous_iff_continuousAt]
  intro t
  exact (continuousOn_dysonSum_Iic B hS ψ (t + 1)).continuousAt (Iic_mem_nhds (by linarith))

/-! ### The Duhamel equation -/

/-- The integrand of the Duhamel equation is continuous. -/
theorem continuous_dysonSum_integrand (hS : IsContractionSemigroup S) (t : ℝ) (ψ : E) :
    Continuous fun s => S (t - s) (B (dysonSum S B s ψ)) :=
  hS.continuous_uncurry.comp
    ((continuous_const.sub continuous_id).prodMk (B.continuous.comp (continuous_dysonSum B hS ψ)))

/-- ★ **The Duhamel equation**: `𝒮(t) ψ = S t ψ + ∫₀ᵗ S (t − s) (B (𝒮(s) ψ)) ds` for `0 ≤ t`. -/
theorem dysonSum_eq_add_integral (hS : IsContractionSemigroup S) {t : ℝ} (ht : 0 ≤ t) (ψ : E) :
    dysonSum S B t ψ = S t ψ + ∫ s in (0 : ℝ)..t, S (t - s) (B (dysonSum S B s ψ)) := by
  rw [dysonSum_of_nonneg B ht, (summable_dysonTerm B hS ht ψ).tsum_eq_zero_add, dysonTerm_zero]
  congr 1
  have hsum : HasSum (fun n => ∫ s in (0 : ℝ)..t, S (t - s) (B (dysonTerm S B n s ψ)))
      (∫ s in (0 : ℝ)..t, S (t - s) (B (dysonSum S B s ψ))) := by
    refine intervalIntegral.hasSum_integral_of_dominated_convergence
      (bound := fun n s => ‖B‖ * ((‖B‖ * s) ^ n / n ! * ‖ψ‖))
      (fun n => (continuous_dysonTerm_integrand B hS n t ψ).aestronglyMeasurable) ?_ ?_ ?_ ?_
    · intro n
      refine Filter.Eventually.of_forall fun s hs => ?_
      rw [Set.uIoc_of_le ht] at hs
      calc ‖S (t - s) (B (dysonTerm S B n s ψ))‖
          ≤ ‖B (dysonTerm S B n s ψ)‖ := hS.norm_apply_le _ _
        _ ≤ ‖B‖ * ‖dysonTerm S B n s ψ‖ := B.le_opNorm _
        _ ≤ ‖B‖ * ((‖B‖ * s) ^ n / n ! * ‖ψ‖) := by
            gcongr; exact norm_dysonTerm_le B hS n hs.1.le ψ
    · exact Filter.Eventually.of_forall fun s _ =>
        ((Real.summable_pow_div_factorial _).mul_right _).mul_left _
    · have : (fun s : ℝ => ∑' n, ‖B‖ * ((‖B‖ * s) ^ n / n ! * ‖ψ‖))
          = fun s => ‖B‖ * (Real.exp (‖B‖ * s) * ‖ψ‖) := by
        funext s
        rw [tsum_mul_left, tsum_mul_right, Real.exp_eq_exp_ℝ,
          ← (expSeries_div_hasSum_exp (‖B‖ * s)).tsum_eq]
      rw [this]
      exact (by fun_prop : Continuous fun s : ℝ => ‖B‖ * (Real.exp (‖B‖ * s) * ‖ψ‖))
        |>.intervalIntegrable _ _
    · refine Filter.Eventually.of_forall fun s hs => ?_
      rw [Set.uIoc_of_le ht] at hs
      exact ((S (t - s)).comp B).hasSum (hasSum_dysonTerm B hS hs.1.le ψ)
  exact hsum.tsum_eq

omit [CompleteSpace E] in
/-- The Volterra integral of the bound `(‖B‖ s)ⁿ / n!` is the next term of the exponential
series. -/
theorem integral_norm_pow_div_factorial (n : ℕ) (t : ℝ) :
    ∫ s in (0 : ℝ)..t, ‖B‖ * ((‖B‖ * s) ^ n / n !) = (‖B‖ * t) ^ (n + 1) / (n + 1)! := by
  simp_rw [mul_pow, mul_div_assoc]
  rw [intervalIntegral.integral_const_mul, intervalIntegral.integral_const_mul,
    intervalIntegral.integral_div, integral_pow, Nat.factorial_succ]
  push_cast
  field_simp
  ring

/-- ★ **Uniqueness for the Duhamel equation.** A continuous solution of
`X t = S t ψ + ∫₀ᵗ S (t − s) (B (X s)) ds` on `[0, T]` is the Dyson sum. -/
theorem eq_dysonSum_of_duhamel (hS : IsContractionSemigroup S) {T : ℝ} {X : ℝ → E}
    (hX : ContinuousOn X (Set.Icc 0 T)) (ψ : E)
    (hX' : ∀ t ∈ Set.Icc (0 : ℝ) T, X t = S t ψ + ∫ s in (0 : ℝ)..t, S (t - s) (B (X s))) :
    ∀ t ∈ Set.Icc (0 : ℝ) T, X t = dysonSum S B t ψ := by
  set Y : ℝ → E := fun t => X t - dysonSum S B t ψ with hY
  have hYc : ContinuousOn Y (Set.Icc 0 T) := hX.sub (continuous_dysonSum B hS ψ).continuousOn
  have hYint : ∀ t ∈ Set.Icc (0 : ℝ) T, ContinuousOn (fun s => S (t - s) (B (Y s))) (Set.Icc 0 t) :=
    fun t ht => hS.continuous_uncurry.comp_continuousOn
      ((continuous_const.sub continuous_id).continuousOn.prodMk
        (B.continuous.comp_continuousOn (hYc.mono (Set.Icc_subset_Icc le_rfl ht.2))))
  have hYeq : ∀ t ∈ Set.Icc (0 : ℝ) T, Y t = ∫ s in (0 : ℝ)..t, S (t - s) (B (Y s)) := by
    intro t ht
    have hint : ∀ s ∈ Set.uIcc (0 : ℝ) t,
        S (t - s) (B (Y s)) = S (t - s) (B (X s)) - S (t - s) (B (dysonSum S B s ψ)) := by
      intro s _
      simp only [hY, map_sub]
    have hXint : IntervalIntegrable (fun s => S (t - s) (B (X s))) volume 0 t := by
      refine ContinuousOn.intervalIntegrable ?_
      rw [Set.uIcc_of_le ht.1]
      exact hS.continuous_uncurry.comp_continuousOn
        ((continuous_const.sub continuous_id).continuousOn.prodMk
          (B.continuous.comp_continuousOn (hX.mono (Set.Icc_subset_Icc le_rfl ht.2))))
    rw [hY]
    simp only
    rw [hX' t ht, dysonSum_eq_add_integral B hS ht.1 ψ, intervalIntegral.integral_congr hint,
      intervalIntegral.integral_sub hXint
        ((continuous_dysonSum_integrand B hS t ψ).intervalIntegrable _ _)]
    abel
  obtain ⟨M, hM⟩ := (isCompact_Icc (a := (0 : ℝ)) (b := T)).exists_bound_of_continuousOn hYc
  have hbound : ∀ n : ℕ, ∀ t ∈ Set.Icc (0 : ℝ) T, ‖Y t‖ ≤ M * ((‖B‖ * t) ^ n / n !) := by
    intro n
    induction n with
    | zero => intro t ht; simpa using hM t ht
    | succ n ih =>
      intro t ht
      rw [hYeq t ht]
      calc ‖∫ s in (0 : ℝ)..t, S (t - s) (B (Y s))‖
          ≤ ∫ s in (0 : ℝ)..t, ‖S (t - s) (B (Y s))‖ :=
            intervalIntegral.norm_integral_le_integral_norm ht.1
        _ ≤ ∫ s in (0 : ℝ)..t, M * (‖B‖ * ((‖B‖ * s) ^ n / n !)) := by
            refine intervalIntegral.integral_mono_on ht.1
              ((hYint t ht).norm.intervalIntegrable_of_Icc ht.1)
              (Continuous.intervalIntegrable (by fun_prop) _ _) fun s hs => ?_
            calc ‖S (t - s) (B (Y s))‖ ≤ ‖B (Y s)‖ := hS.norm_apply_le _ _
              _ ≤ ‖B‖ * ‖Y s‖ := B.le_opNorm _
              _ ≤ ‖B‖ * (M * ((‖B‖ * s) ^ n / n !)) := by
                  gcongr; exact ih s ⟨hs.1, le_trans hs.2 ht.2⟩
              _ = M * (‖B‖ * ((‖B‖ * s) ^ n / n !)) := by ring
        _ = M * ((‖B‖ * t) ^ (n + 1) / (n + 1)!) := by
            rw [intervalIntegral.integral_const_mul, integral_norm_pow_div_factorial]
  intro t ht
  have hlim : Tendsto (fun n : ℕ => M * ((‖B‖ * t) ^ n / n !)) atTop (𝓝 0) := by
    simpa using (FloorSemiring.tendsto_pow_div_factorial_atTop (‖B‖ * t)).const_mul M
  have hYt : ‖Y t‖ ≤ 0 := ge_of_tendsto' hlim fun n => hbound n t ht
  have h0 : Y t = 0 := norm_le_zero_iff.mp hYt
  rw [hY] at h0
  exact sub_eq_zero.mp h0

/-- ★★ **The semigroup law**: `𝒮(t + s) ψ = 𝒮(t) (𝒮(s) ψ)` for `s, t ≥ 0`, by uniqueness for the
Duhamel equation. -/
theorem dysonSum_add_time (hS : IsContractionSemigroup S) {s t : ℝ} (hs : 0 ≤ s) (ht : 0 ≤ t)
    (ψ : E) : dysonSum S B (t + s) ψ = dysonSum S B t (dysonSum S B s ψ) := by
  refine eq_dysonSum_of_duhamel B hS (T := t) (X := fun u => dysonSum S B (u + s) ψ)
    ((continuous_dysonSum B hS ψ).comp (continuous_add_const s)).continuousOn _ ?_ t ⟨ht, le_rfl⟩
  intro u hu
  have hu0 : 0 ≤ u + s := add_nonneg hu.1 hs
  have hsplit := intervalIntegral.integral_add_adjacent_intervals (μ := volume) (a := (0 : ℝ))
    (b := s) (c := u + s) ((continuous_dysonSum_integrand B hS (u + s) ψ).intervalIntegrable _ _)
    ((continuous_dysonSum_integrand B hS (u + s) ψ).intervalIntegrable _ _)
  have hfirst : ∫ r in (0 : ℝ)..s, S (u + s - r) (B (dysonSum S B r ψ))
      = S u (∫ r in (0 : ℝ)..s, S (s - r) (B (dysonSum S B r ψ))) := by
    rw [← ContinuousLinearMap.intervalIntegral_comp_comm _
      ((continuous_dysonSum_integrand B hS s ψ).intervalIntegrable _ _)]
    refine intervalIntegral.integral_congr fun r hr => ?_
    rw [Set.uIcc_of_le hs] at hr
    rw [show u + s - r = u + (s - r) by ring, hS.map_add u (s - r) hu.1 (by linarith [hr.2]),
      mul_apply_eq_comp]
  have hsecond : ∫ r in (0 : ℝ)..u, S (u - r) (B (dysonSum S B (r + s) ψ))
      = ∫ r in s..u + s, S (u + s - r) (B (dysonSum S B r ψ)) := by
    have h := intervalIntegral.integral_comp_add_right
      (fun r => S (u + s - r) (B (dysonSum S B r ψ))) (a := 0) (b := u) s
    rw [zero_add] at h
    rw [← h]
    refine intervalIntegral.integral_congr fun r _ => ?_
    congr 2
    ring
  show dysonSum S B (u + s) ψ
    = S u (dysonSum S B s ψ) + ∫ r in (0 : ℝ)..u, S (u - r) (B (dysonSum S B (r + s) ψ))
  rw [dysonSum_eq_add_integral B hS hu0 ψ, hS.map_add u s hu.1 hs, ← hsplit, hfirst, hsecond,
    mul_apply_eq_comp, ← add_assoc, ← map_add, ← dysonSum_eq_add_integral B hS hs ψ]

/-! ### The perturbed semigroup as an operator -/

omit [CompleteSpace E] in
theorem dysonSum_max (t : ℝ) (ψ : E) : dysonSum S B (max t 0) ψ = dysonSum S B t ψ := by
  rw [dysonSum, dysonSum, max_eq_left (le_max_right t 0)]

/-- ★ **The perturbed semigroup** `𝒮(t)` as a continuous linear map, `‖𝒮(t)‖ ≤ e^{‖B‖ t}`. -/
noncomputable def _root_.IsContractionSemigroup.perturbed (hS : IsContractionSemigroup S)
    (B : E →L[ℂ] E) (t : ℝ) : E →L[ℂ] E :=
  LinearMap.mkContinuous
    { toFun := dysonSum S B t
      map_add' := dysonSum_add B hS t
      map_smul' := fun c ψ => by simp [dysonSum_smul] }
    (Real.exp (‖B‖ * max t 0)) fun ψ => by
      simp only [LinearMap.coe_mk, AddHom.coe_mk]
      rw [← dysonSum_max B t ψ]
      exact norm_dysonSum_le B hS (le_max_right t 0) ψ

theorem perturbed_apply (hS : IsContractionSemigroup S) (t : ℝ) (ψ : E) :
    hS.perturbed B t ψ = dysonSum S B t ψ := rfl

theorem norm_perturbed_le (hS : IsContractionSemigroup S) (t : ℝ) :
    ‖hS.perturbed B t‖ ≤ Real.exp (‖B‖ * max t 0) :=
  LinearMap.mkContinuous_norm_le _ (Real.exp_pos _).le _

theorem perturbed_zero (hS : IsContractionSemigroup S) : hS.perturbed B 0 = 1 :=
  ContinuousLinearMap.ext fun ψ => by rw [perturbed_apply, dysonSum_zero B hS, one_apply_eq_self]

/-- ★★ The perturbed semigroup is a semigroup: `𝒮(t + s) = 𝒮(t) * 𝒮(s)` for `s, t ≥ 0`. -/
theorem perturbed_add (hS : IsContractionSemigroup S) {s t : ℝ} (hs : 0 ≤ s) (ht : 0 ≤ t) :
    hS.perturbed B (t + s) = hS.perturbed B t * hS.perturbed B s :=
  ContinuousLinearMap.ext fun ψ => by
    rw [mul_apply_eq_comp, perturbed_apply, perturbed_apply, perturbed_apply,
      dysonSum_add_time B hS hs ht]

theorem continuous_perturbed_apply (hS : IsContractionSemigroup S) (ψ : E) :
    Continuous fun t => hS.perturbed B t ψ :=
  continuous_dysonSum B hS ψ

/-! ### The Trotter product formula -/

variable (S) in
/-- **The Trotter step** `S h · exp (h B)`. -/
noncomputable def trotterStep (h : ℝ) : E →L[ℂ] E := S h * exp (h • B)

omit [CompleteSpace E] in
theorem trotterStep_apply (h : ℝ) (χ : E) : trotterStep S B h χ = S h (exp (h • B) χ) :=
  mul_apply_eq_comp _ _ _

theorem norm_trotterStep_le [Nontrivial E] (hS : IsContractionSemigroup S) {h : ℝ} (hh : 0 ≤ h) :
    ‖trotterStep S B h‖ ≤ Real.exp (h * ‖B‖) := by
  calc ‖S h * exp (h • B)‖ ≤ ‖S h‖ * ‖exp (h • B)‖ := norm_mul_le _ _
    _ ≤ 1 * Real.exp ‖h • B‖ := by
        gcongr
        · exact hS.norm_le_one h
        · exact norm_exp_le_exp_norm _
    _ = Real.exp (h * ‖B‖) := by rw [one_mul, norm_smul, Real.norm_of_nonneg hh]

theorem norm_trotterStep_pow_apply_le [Nontrivial E] (hS : IsContractionSemigroup S) {h : ℝ}
    (hh : 0 ≤ h) (m : ℕ) (χ : E) :
    ‖(trotterStep S B h ^ m) χ‖ ≤ Real.exp (m * h * ‖B‖) * ‖χ‖ := by
  induction m with
  | zero => simp
  | succ m ih =>
    rw [pow_succ', mul_apply_eq_comp]
    calc ‖trotterStep S B h ((trotterStep S B h ^ m) χ)‖
        ≤ ‖trotterStep S B h‖ * ‖(trotterStep S B h ^ m) χ‖ := ContinuousLinearMap.le_opNorm _ _
      _ ≤ Real.exp (h * ‖B‖) * (Real.exp (m * h * ‖B‖) * ‖χ‖) := by
          gcongr
          exact norm_trotterStep_le B hS hh
      _ = Real.exp ((m + 1 : ℕ) * h * ‖B‖) * ‖χ‖ := by
          rw [← mul_assoc, ← Real.exp_add]
          push_cast
          ring_nf

omit [CompleteSpace E] in
/-- Telescoping a product against a sequence: `Fⁿ (u 0) − u n = ∑ₖ F^{n−1−k} (F (u k) − u (k+1))`. -/
theorem pow_apply_sub_eq_sum (F : E →L[ℂ] E) (u : ℕ → E) (n : ℕ) :
    (F ^ n) (u 0) - u n
      = ∑ k ∈ Finset.range n, (F ^ (n - 1 - k)) (F (u k) - u (k + 1)) := by
  induction n with
  | zero => simp
  | succ n ih =>
    rw [Finset.sum_range_succ, show n + 1 - 1 - n = 0 by omega, pow_zero, one_apply_eq_self]
    have hsum : ∑ k ∈ Finset.range n, (F ^ (n + 1 - 1 - k)) (F (u k) - u (k + 1))
        = F (∑ k ∈ Finset.range n, (F ^ (n - 1 - k)) (F (u k) - u (k + 1))) := by
      rw [map_sum]
      refine Finset.sum_congr rfl fun k hk => ?_
      rw [show n + 1 - 1 - k = (n - 1 - k) + 1 by have := Finset.mem_range.mp hk; omega, pow_succ',
        mul_apply_eq_comp]
    rw [hsum, ← ih, pow_succ', mul_apply_eq_comp, map_sub]
    abel

omit [CompleteSpace E] in
/-- The tail of the exponential series: `∑ₙ xⁿ⁺²/(n+2)! ≤ x² eˣ` for `0 ≤ x`. -/
theorem tsum_pow_div_factorial_add_two_le {x : ℝ} (hx : 0 ≤ x) :
    ∑' n : ℕ, x ^ (n + 2) / (n + 2)! ≤ x ^ 2 * Real.exp x := by
  have h1 : Summable fun n : ℕ => x ^ (n + 2) / (n + 2)! :=
    (Real.summable_pow_div_factorial x).comp_injective (add_left_injective 2)
  have h2 : ∀ n : ℕ, x ^ (n + 2) / (n + 2)! ≤ x ^ 2 * (x ^ n / n !) := by
    intro n
    rw [pow_add, mul_comm (x ^ n), mul_div_assoc]
    gcongr
    omega
  calc ∑' n : ℕ, x ^ (n + 2) / (n + 2)!
      ≤ ∑' n : ℕ, x ^ 2 * (x ^ n / n !) :=
        h1.tsum_le_tsum h2 ((Real.summable_pow_div_factorial x).mul_left _)
    _ = x ^ 2 * Real.exp x := by
        rw [tsum_mul_left, Real.exp_eq_exp_ℝ, ← (expSeries_div_hasSum_exp x).tsum_eq]

/-- The Dyson series beyond first order: `‖𝒮(h) χ − S h χ − D₁(h) χ‖ ≤ (‖B‖ h)² e^{‖B‖ h} ‖χ‖`. -/
theorem norm_dysonSum_sub_sub_le (hS : IsContractionSemigroup S) {h : ℝ} (hh : 0 ≤ h) (χ : E) :
    ‖dysonSum S B h χ - S h χ - dysonTerm S B 1 h χ‖
      ≤ (‖B‖ * h) ^ 2 * Real.exp (‖B‖ * h) * ‖χ‖ := by
  have hs := summable_dysonTerm B hS hh χ
  have htail : dysonSum S B h χ - S h χ - dysonTerm S B 1 h χ
      = ∑' n, dysonTerm S B (n + 2) h χ := by
    rw [dysonSum_of_nonneg B hh, ← hs.sum_add_tsum_nat_add 2, Finset.sum_range_succ,
      Finset.sum_range_one, dysonTerm_zero]
    abel
  rw [htail]
  have hnorm : Summable fun n => ‖dysonTerm S B (n + 2) h χ‖ :=
    (summable_norm_dysonTerm B hS hh χ).comp_injective (add_left_injective 2)
  calc ‖∑' n, dysonTerm S B (n + 2) h χ‖
      ≤ ∑' n, ‖dysonTerm S B (n + 2) h χ‖ := norm_tsum_le_tsum_norm hnorm
    _ ≤ ∑' n, (‖B‖ * h) ^ (n + 2) / (n + 2)! * ‖χ‖ :=
        hnorm.tsum_le_tsum (fun n => norm_dysonTerm_le B hS (n + 2) hh χ)
          (((Real.summable_pow_div_factorial (‖B‖ * h)).comp_injective
            (add_left_injective 2)).mul_right _)
    _ = (∑' n, (‖B‖ * h) ^ (n + 2) / (n + 2)!) * ‖χ‖ := tsum_mul_right
    _ ≤ (‖B‖ * h) ^ 2 * Real.exp (‖B‖ * h) * ‖χ‖ := by
        gcongr
        exact tsum_pow_div_factorial_add_two_le (by positivity)

/-- The one-step defect, decomposed: the second-order remainder of `exp (h B)`, the integral of
`S h (B χ) − S (h − s) (B (S s χ))` over `[0, h]`, and the Dyson tail. -/
theorem trotterStep_apply_sub_dysonSum (hS : IsContractionSemigroup S) (h : ℝ) (χ : E) :
    trotterStep S B h χ - dysonSum S B h χ
      = S h (exp (h • B) χ - χ - h • B χ)
        + (∫ s in (0 : ℝ)..h, (S h (B χ) - S (h - s) (B (S s χ))))
        - (dysonSum S B h χ - S h χ - dysonTerm S B 1 h χ) := by
  have h1 : dysonTerm S B 1 h χ = ∫ s in (0 : ℝ)..h, S (h - s) (B (S s χ)) := rfl
  have h2 : (∫ s in (0 : ℝ)..h, (S h (B χ) - S (h - s) (B (S s χ))))
      = S h (h • B χ) - dysonTerm S B 1 h χ := by
    rw [h1, intervalIntegral.integral_sub (f := fun _ => S h (B χ))
      (g := fun s => S (h - s) (B (S s χ))) (continuous_const.intervalIntegrable _ _)
      ((continuous_dysonTerm_integrand B hS 0 h χ).intervalIntegrable _ _),
      intervalIntegral.integral_const, sub_zero, (S h).map_smul_of_tower]
  rw [h2, trotterStep_apply, map_sub, map_sub]
  abel

/-- ★ **The one-step defect bound**: if `‖S h (B χ) − S (h − s) (B (S s χ))‖ ≤ ω` on `[0, h]`, then
`‖(S h · exp (h B)) χ − 𝒮(h) χ‖ ≤ 2 (‖B‖ h)² e^{‖B‖ h} ‖χ‖ + h ω`. -/
theorem norm_trotterStep_apply_sub_dysonSum_le (hS : IsContractionSemigroup S)
    {h : ℝ} (hh : 0 ≤ h) (χ : E) {ω : ℝ}
    (hω : ∀ s ∈ Set.Icc (0 : ℝ) h, ‖S h (B χ) - S (h - s) (B (S s χ))‖ ≤ ω) :
    ‖trotterStep S B h χ - dysonSum S B h χ‖
      ≤ 2 * ((‖B‖ * h) ^ 2 * Real.exp (‖B‖ * h) * ‖χ‖) + h * ω := by
  rw [trotterStep_apply_sub_dysonSum B hS h χ]
  have hi : ‖S h (exp (h • B) χ - χ - h • B χ)‖ ≤ (‖B‖ * h) ^ 2 * Real.exp (‖B‖ * h) * ‖χ‖ := by
    have hχ : exp (h • B) χ - χ - h • B χ = (exp (h • B) - 1 - h • B) χ := by
      simp
    calc ‖S h (exp (h • B) χ - χ - h • B χ)‖
        ≤ ‖exp (h • B) χ - χ - h • B χ‖ := hS.norm_apply_le _ _
      _ = ‖(exp (h • B) - 1 - h • B) χ‖ := by rw [hχ]
      _ ≤ ‖exp (h • B) - 1 - h • B‖ * ‖χ‖ := ContinuousLinearMap.le_opNorm _ _
      _ ≤ ‖h • B‖ ^ 2 * Real.exp ‖h • B‖ * ‖χ‖ := by
          gcongr
          exact norm_exp_sub_one_sub_le' _
      _ = (‖B‖ * h) ^ 2 * Real.exp (‖B‖ * h) * ‖χ‖ := by
          rw [norm_smul, Real.norm_of_nonneg hh, mul_comm h]
  have hii : ‖∫ s in (0 : ℝ)..h, (S h (B χ) - S (h - s) (B (S s χ)))‖ ≤ h * ω := by
    refine le_trans (intervalIntegral.norm_integral_le_of_norm_le_const (C := ω) fun s hs => ?_) ?_
    · rw [Set.uIoc_of_le hh] at hs
      exact hω s ⟨hs.1.le, hs.2⟩
    · rw [sub_zero, abs_of_nonneg hh, mul_comm]
  have hiii := norm_dysonSum_sub_sub_le B hS hh χ
  calc ‖S h (exp (h • B) χ - χ - h • B χ)
          + (∫ s in (0 : ℝ)..h, (S h (B χ) - S (h - s) (B (S s χ))))
          - (dysonSum S B h χ - S h χ - dysonTerm S B 1 h χ)‖
      ≤ ‖S h (exp (h • B) χ - χ - h • B χ)
          + ∫ s in (0 : ℝ)..h, (S h (B χ) - S (h - s) (B (S s χ)))‖
        + ‖dysonSum S B h χ - S h χ - dysonTerm S B 1 h χ‖ := norm_sub_le _ _
    _ ≤ ‖S h (exp (h • B) χ - χ - h • B χ)‖
          + ‖∫ s in (0 : ℝ)..h, (S h (B χ) - S (h - s) (B (S s χ)))‖
        + ‖dysonSum S B h χ - S h χ - dysonTerm S B 1 h χ‖ := by
          gcongr
          exact norm_add_le _ _
    _ ≤ (‖B‖ * h) ^ 2 * Real.exp (‖B‖ * h) * ‖χ‖ + h * ω
        + (‖B‖ * h) ^ 2 * Real.exp (‖B‖ * h) * ‖χ‖ := by gcongr
    _ = 2 * ((‖B‖ * h) ^ 2 * Real.exp (‖B‖ * h) * ‖χ‖) + h * ω := by ring

omit [CompleteSpace E] in
/-- **Uniformity on a compact set**: for every `ε > 0` there is `δ > 0` with
`‖S h (B χ) − S (h − s) (B (S s χ))‖ ≤ ε` for all `0 ≤ s ≤ h ≤ δ` and all `χ` in a compact `K`. -/
theorem exists_delta_of_isCompact (hS : IsContractionSemigroup S) {K : Set E} (hK : IsCompact K)
    {ε : ℝ} (hε : 0 < ε) :
    ∃ δ > 0, ∀ h ∈ Set.Icc (0 : ℝ) δ, ∀ s ∈ Set.Icc (0 : ℝ) h, ∀ χ ∈ K,
      ‖S h (B χ) - S (h - s) (B (S s χ))‖ ≤ ε := by
  set Φ : ℝ × ℝ × E → E := fun p => S p.1 (B p.2.2) - S (p.1 - p.2.1) (B (S p.2.1 p.2.2)) with hΦ
  have hΦc : Continuous Φ := by
    refine Continuous.sub ?_ ?_
    · exact hS.continuous_uncurry.comp
        (continuous_fst.prodMk (B.continuous.comp (continuous_snd.comp continuous_snd)))
    · exact hS.continuous_uncurry.comp
        ((continuous_fst.sub (continuous_fst.comp continuous_snd)).prodMk
          (B.continuous.comp (hS.continuous_uncurry.comp continuous_snd)))
  have hC : IsCompact (Set.Icc (0 : ℝ) 1 ×ˢ (Set.Icc (0 : ℝ) 1 ×ˢ K)) :=
    isCompact_Icc.prod (isCompact_Icc.prod hK)
  have hu := hC.uniformContinuousOn_of_continuous hΦc.continuousOn
  rw [Metric.uniformContinuousOn_iff_le] at hu
  obtain ⟨δ, hδ, hδ'⟩ := hu ε hε
  refine ⟨min δ 1, lt_min hδ one_pos, fun h hh s hs χ hχ => ?_⟩
  have hh1 : h ≤ 1 := le_trans hh.2 (min_le_right _ _)
  have hhδ : h ≤ δ := le_trans hh.2 (min_le_left _ _)
  have h0 : Φ (0, 0, χ) = 0 := by simp [hΦ, hS.map_zero]
  have key := hδ' (h, s, χ) ⟨⟨hh.1, hh1⟩, ⟨hs.1, le_trans hs.2 hh1⟩, hχ⟩ (0, 0, χ)
    ⟨⟨le_rfl, zero_le_one⟩, ⟨le_rfl, zero_le_one⟩, hχ⟩ (by
      rw [Prod.dist_eq, Prod.dist_eq, dist_self, Real.dist_eq, Real.dist_eq, sub_zero, sub_zero,
        abs_of_nonneg hh.1, abs_of_nonneg hs.1]
      exact max_le hhδ (max_le (le_trans hs.2 hhδ) hδ.le))
  rw [dist_eq_norm, h0, sub_zero] at key
  exact key

/-- The telescoped bound for the `n`-step product, given a uniform bound `ε₁` on the one-step
defect integrand along the orbit `𝒮(k t/n) ψ`. -/
theorem norm_trotterStep_pow_apply_sub_le [Nontrivial E] (hS : IsContractionSemigroup S) {t : ℝ}
    (ht : 0 ≤ t) (ψ : E) {n : ℕ} (hn : 0 < n) {ε₁ : ℝ}
    (hε₁ : ∀ k ∈ Finset.range n, ∀ s ∈ Set.Icc (0 : ℝ) (t / n),
      ‖S (t / n) (B (dysonSum S B (k * (t / n)) ψ))
        - S (t / n - s) (B (S s (dysonSum S B (k * (t / n)) ψ)))‖ ≤ ε₁) :
    ‖(trotterStep S B (t / n) ^ n) ψ - dysonSum S B t ψ‖
      ≤ Real.exp (t * ‖B‖) * (n * (2 * ((‖B‖ * (t / n)) ^ 2 * Real.exp (‖B‖ * (t / n))
          * (Real.exp (‖B‖ * t) * ‖ψ‖)) + (t / n) * ε₁)) := by
  set h := t / n with hh_def
  have hh : 0 ≤ h := by positivity
  have hnh : (n : ℝ) * h = t := by
    rw [hh_def, mul_div_cancel₀]
    exact_mod_cast hn.ne'
  set u : ℕ → E := fun k => dysonSum S B (k * h) ψ with hu
  have hu0 : u 0 = ψ := by simp [hu, dysonSum_zero B hS]
  have hun : u n = dysonSum S B t ψ := by simp [hu, hnh]
  have hstep : ∀ k, u (k + 1) = dysonSum S B h (u k) := by
    intro k
    simp only [hu]
    rw [← dysonSum_add_time B hS (by positivity) hh]
    congr 1
    push_cast
    ring
  have hkh : ∀ k ∈ Finset.range n, (k : ℝ) * h ≤ t := by
    intro k hk
    have : (k : ℝ) ≤ n := by exact_mod_cast (Finset.mem_range.mp hk).le
    rw [← hnh]
    exact mul_le_mul_of_nonneg_right this hh
  have hunorm : ∀ k ∈ Finset.range n, ‖u k‖ ≤ Real.exp (‖B‖ * t) * ‖ψ‖ := by
    intro k hk
    refine le_trans (norm_dysonSum_le B hS (by positivity) ψ) ?_
    gcongr
    exact hkh k hk
  have hpow : ∀ k ∈ Finset.range n, ∀ v : E,
      ‖(trotterStep S B h ^ (n - 1 - k)) v‖ ≤ Real.exp (t * ‖B‖) * ‖v‖ := by
    intro k hk v
    refine le_trans (norm_trotterStep_pow_apply_le B hS hh _ v) ?_
    gcongr
    calc ((n - 1 - k : ℕ) : ℝ) * h ≤ n * h := by
          gcongr
          exact_mod_cast (by omega : n - 1 - k ≤ n)
      _ = t := hnh
  rw [show (trotterStep S B h ^ n) ψ - dysonSum S B t ψ = (trotterStep S B h ^ n) (u 0) - u n by
    rw [hu0, hun], pow_apply_sub_eq_sum]
  calc ‖∑ k ∈ Finset.range n, (trotterStep S B h ^ (n - 1 - k)) (trotterStep S B h (u k) - u (k + 1))‖
      ≤ ∑ k ∈ Finset.range n,
          ‖(trotterStep S B h ^ (n - 1 - k)) (trotterStep S B h (u k) - u (k + 1))‖ :=
        norm_sum_le _ _
    _ ≤ ∑ _k ∈ Finset.range n, Real.exp (t * ‖B‖)
          * (2 * ((‖B‖ * h) ^ 2 * Real.exp (‖B‖ * h) * (Real.exp (‖B‖ * t) * ‖ψ‖)) + h * ε₁) := by
        refine Finset.sum_le_sum fun k hk => ?_
        refine le_trans (hpow k hk _) ?_
        gcongr
        rw [hstep k]
        refine le_trans (norm_trotterStep_apply_sub_dysonSum_le B hS hh (u k)
          (ω := ε₁) fun s hs => hε₁ k hk s hs) ?_
        gcongr
        exact hunorm k hk
    _ = Real.exp (t * ‖B‖) * (n * (2 * ((‖B‖ * h) ^ 2 * Real.exp (‖B‖ * h)
          * (Real.exp (‖B‖ * t) * ‖ψ‖)) + h * ε₁)) := by
        rw [Finset.sum_const, Finset.card_range, nsmul_eq_mul]
        ring

/-- ★★ **The Trotter product formula** for a bounded perturbation of a strongly continuous
contraction semigroup: `(S (t/n) · exp ((t/n) B))ⁿ ψ → 𝒮(t) ψ` for every `ψ` and `0 ≤ t`. -/
theorem tendsto_trotterStep_pow_apply [Nontrivial E] (hS : IsContractionSemigroup S) {t : ℝ}
    (ht : 0 ≤ t) (ψ : E) :
    Tendsto (fun n : ℕ => (trotterStep S B (t / n) ^ n) ψ) atTop (𝓝 (dysonSum S B t ψ)) := by
  set K := (fun s => dysonSum S B s ψ) '' Set.Icc (0 : ℝ) t with hK
  have hKc : IsCompact K := isCompact_Icc.image (continuous_dysonSum B hS ψ)
  rw [Metric.tendsto_atTop]
  intro ε hε
  set M := Real.exp (‖B‖ * t) * ‖ψ‖ with hM
  set C₁ := Real.exp (t * ‖B‖) * (2 * ‖B‖ ^ 2 * t * Real.exp ‖B‖ * M) with hC₁
  set C₂ := Real.exp (t * ‖B‖) * t with hC₂
  have hM0 : 0 ≤ M := by positivity
  have hC₁0 : 0 ≤ C₁ := by positivity
  have hC₂0 : 0 ≤ C₂ := by positivity
  obtain ⟨δ, hδ, hδ'⟩ := exists_delta_of_isCompact B hS hKc (ε := ε / (2 * (C₂ + 1)))
    (by positivity)
  set m := min (min δ 1) (ε / (2 * (C₁ + 1))) with hm
  have hm0 : 0 < m := lt_min (lt_min hδ one_pos) (by positivity)
  obtain ⟨N, hN⟩ := exists_nat_gt (t / m)
  refine ⟨N + 1, fun n hn => ?_⟩
  have hn0 : 0 < n := by omega
  have hnR : (0 : ℝ) < n := by exact_mod_cast hn0
  set h := t / n with hh_def
  have hh : 0 ≤ h := by positivity
  have hhm : h ≤ m := by
    rw [hh_def, div_le_iff₀ hnR]
    have : t / m < n := lt_of_lt_of_le hN (by exact_mod_cast (by omega : N ≤ n))
    rw [div_lt_iff₀ hm0] at this
    linarith
  have hhδ : h ≤ δ := le_trans hhm (le_trans (min_le_left _ _) (min_le_left _ _))
  have hh1 : h ≤ 1 := le_trans hhm (le_trans (min_le_left _ _) (min_le_right _ _))
  have hhε : h ≤ ε / (2 * (C₁ + 1)) := le_trans hhm (min_le_right _ _)
  have hnh : (n : ℝ) * h = t := by
    rw [hh_def, mul_div_cancel₀ _ hnR.ne']
  have hb := norm_trotterStep_pow_apply_sub_le B hS ht ψ hn0 (ε₁ := ε / (2 * (C₂ + 1)))
    (fun k hk s hs => hδ' h ⟨hh, hhδ⟩ s hs _ ⟨k * h, ⟨by positivity, by
      rw [← hnh]
      exact mul_le_mul_of_nonneg_right (by exact_mod_cast (Finset.mem_range.mp hk).le) hh⟩, rfl⟩)
  rw [dist_eq_norm]
  refine lt_of_le_of_lt hb ?_
  have hexp : Real.exp (‖B‖ * h) ≤ Real.exp ‖B‖ :=
    Real.exp_le_exp.mpr (mul_le_of_le_one_right (norm_nonneg _) hh1)
  have hrewrite : (n : ℝ) * (2 * ((‖B‖ * h) ^ 2 * Real.exp (‖B‖ * h) * M) + h * (ε / (2 * (C₂ + 1))))
      = 2 * ‖B‖ ^ 2 * t * h * Real.exp (‖B‖ * h) * M + t * (ε / (2 * (C₂ + 1))) := by
    rw [← hnh]
    ring
  rw [hrewrite, mul_add]
  have h1 : Real.exp (t * ‖B‖) * (2 * ‖B‖ ^ 2 * t * h * Real.exp (‖B‖ * h) * M) ≤ C₁ * h := by
    rw [hC₁]
    have : 2 * ‖B‖ ^ 2 * t * h * Real.exp (‖B‖ * h) * M ≤ 2 * ‖B‖ ^ 2 * t * Real.exp ‖B‖ * M * h := by
      have h0 : 0 ≤ 2 * ‖B‖ ^ 2 * t * h * M := by positivity
      calc 2 * ‖B‖ ^ 2 * t * h * Real.exp (‖B‖ * h) * M
          = (2 * ‖B‖ ^ 2 * t * h * M) * Real.exp (‖B‖ * h) := by ring
        _ ≤ (2 * ‖B‖ ^ 2 * t * h * M) * Real.exp ‖B‖ := mul_le_mul_of_nonneg_left hexp h0
        _ = 2 * ‖B‖ ^ 2 * t * Real.exp ‖B‖ * M * h := by ring
    calc Real.exp (t * ‖B‖) * (2 * ‖B‖ ^ 2 * t * h * Real.exp (‖B‖ * h) * M)
        ≤ Real.exp (t * ‖B‖) * (2 * ‖B‖ ^ 2 * t * Real.exp ‖B‖ * M * h) :=
          mul_le_mul_of_nonneg_left this (Real.exp_pos _).le
      _ = Real.exp (t * ‖B‖) * (2 * ‖B‖ ^ 2 * t * Real.exp ‖B‖ * M) * h := by ring
  have h2 : Real.exp (t * ‖B‖) * (t * (ε / (2 * (C₂ + 1)))) = C₂ * (ε / (2 * (C₂ + 1))) := by
    rw [hC₂]; ring
  have h3 : C₁ * h < ε / 2 := by
    calc C₁ * h ≤ C₁ * (ε / (2 * (C₁ + 1))) := mul_le_mul_of_nonneg_left hhε hC₁0
      _ = ε / 2 * (C₁ / (C₁ + 1)) := by field_simp
      _ < ε / 2 := by
          have : C₁ / (C₁ + 1) < 1 := (div_lt_one (by positivity)).mpr (by linarith)
          nlinarith
  have h4 : C₂ * (ε / (2 * (C₂ + 1))) < ε / 2 := by
    calc C₂ * (ε / (2 * (C₂ + 1))) = ε / 2 * (C₂ / (C₂ + 1)) := by field_simp
      _ < ε / 2 := by
          have : C₂ / (C₂ + 1) < 1 := (div_lt_one (by positivity)).mpr (by linarith)
          nlinarith
  linarith

end ContractionSemigroup
