/-
Copyright (c) 2026 Zayn Blore. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zayn Blore
-/
module

public import CsdLean4.Mathlib.QuantumInfo.RotatingFrame
public import CsdLean4.Empirical.QM.BerryPhase

/-!
# Berry's adiabatic theorem for a spin-½ in a rotating field

**Category:** 3-Local (QM-validity). BACKLOG #56, brick BP-5 of `specs/berry-phase-scoping.md`.

A spin-½ in a magnetic field of fixed magnitude `B` whose direction sweeps the cone of half-angle
`θ` at angular velocity `ω`,
`H(t) = (1/2) B n(t)·σ`, `n(t) = (sin θ cos ωt, sin θ sin ωt, cos θ)`,
is the model Berry solves in §5 of his 1984 paper. Everything here is *exact*, with the adiabatic
limit appearing as an explicit bound in `ω`, never as an unproved approximation.

## The four statements

* ★★★ `hasDerivAt_prop` — the time-dependent Schrödinger equation is solved exactly:
  `V(t) = R_z(ωt) R_k(Ωt)` satisfies `V′ = −i H(t) V`, `V 0 = 1`, `V t` unitary, where
  `Ω = √((B sin θ)² + (B cos θ − ω)²)` is the Rabi frequency and `k` the unit axis of the
  rotating-frame Hamiltonian `K = H(0) − (ω/2)σ₃`. ★★ `hasDerivAt_state` is the same equation for
  the state `ψ(t) = V(t) ψ₀`.
* ★★ `fieldHam_mulVec_coneCurve` — the instantaneous eigenvector of `H(t)` with eigenvalue `B/2` is
  exactly the cone curve `(cos θ/2, e^{iωt} sin θ/2)` of BP-2, so the ray loop whose geometric phase
  `BerryPhase.lean` computed is the loop this Hamiltonian traces.
* ★★★ `norm_inner_coneCurve_state_sq` — **adiabatic following, exactly**: the probability of still
  being in the instantaneous eigenstate is `1 − (ω sin θ/Ω)² sin²(Ωt/2)`, hence
  ★★★ `one_sub_le_norm_inner_coneCurve_state_sq` bounds the loss by `(ω/(B − ω))²` for all time.
* ★★★ `norm_inner_state_sub_exp_le` — **the phase at the end of one turn** `T = 2π/ω` is the
  dynamical phase `−(B/2)T` plus the geometric phase `−π(1 − cos θ)` of BP-2, with an error
  `≤ πω/(2(B − ω)) + (ω/(B − ω))²`, i.e. `O(ω)`. ★ `geometricPhase_cone_loop` identifies that
  second summand as `GeometricPhase.geometricPhase` of the loop over `[0, T]`, so the statement is
  Berry's, not a coincidence of numbers.

## How it is proved

The rotating-frame reduction of `CsdLean4/Mathlib/QuantumInfo/RotatingFrame.lean`: because
`H(t) = R_z(ωt) H(0) R_z(ωt)ᴴ` (★ `drive_conj_initHam`, the Bloch rotation `axisRot_z_conj`), the
propagator is the drive times the evolution generated by the *constant* `K = H(0) − (ω/2)σ₃`
(★ `initHam_sub_driveGen`), and both factors are axis–angle rotations whose derivative is
`hasDerivAt_axisRot`. No matrix exponential, no Dyson series, no perturbation theory.

The overlap is then algebra: `R_z(ωt)` is unitary, so it drops out of the inner product
(`inner_toEuclideanCLM_unitary`) and the whole time dependence sits in the Rabi factor,
whose diagonal matrix element is `cos(Ωt/2) − i (k·n₀) sin(Ωt/2)`
(★★ `inner_spinUp_rabiProp`). The two error bounds come from one exact identity,
★ `one_sub_cosDelta_sq`: `1 − (k·n₀)² = (ω sin θ/Ω)²`.

## Honest scope

⚠️ One model: a rigid rotation of a fixed `H₀` for spin-½. The general adiabatic theorem
(Born–Fock, Kato: an arbitrary gapped path `H(R(t))`, error `O(1/T)`) is **not** proved here and is
not claimed anywhere in this corpus — it is BACKLOG #88. The bounds here are unconditional in `t`
because this model's rotating frame is exact; a general proof cannot be that cheap.

References: M. V. Berry, Proc. R. Soc. A 392 (1984) 45, §5; I. I. Rabi, Phys. Rev. 51 (1937) 652;
L. D. Landau, E. M. Lifshitz, *Quantum Mechanics* §39; `specs/berry-phase-scoping.md`;
`specs/qm-empirical-tests.md` ER3; `specs/BACKLOG.md` #56.
-/

@[expose] public section

noncomputable section

open QuantumInfo.SU2 QuantumInfo.RotatingFrame GeometricPhase
open scoped Matrix Matrix.Norms.L2Operator Real ComplexConjugate

namespace CSD
namespace Empirical
namespace QM
namespace BerryAdiabatic

/-! ### The model -/

/-- The Hamiltonian of a spin-½ in a field of magnitude `B` whose direction sweeps the cone of
half-angle `θ` at angular velocity `ω`: `H(t) = (1/2) B n(t)·σ` with
`n(t) = (sin θ cos ωt, sin θ sin ωt, cos θ)`. -/
def fieldHam (θ ω B : ℝ) (t : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  ((1 / 2 : ℝ) : ℂ) • pauliAxis (B * Real.sin θ * Real.cos (ω * t))
    (B * Real.sin θ * Real.sin (ω * t)) (B * Real.cos θ)

/-- The Hamiltonian at time zero. -/
def initHam (θ B : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  ((1 / 2 : ℝ) : ℂ) • pauliAxis (B * Real.sin θ) 0 (B * Real.cos θ)

/-- The generator of the drive, `G = (ω/2) σ₃`. -/
def driveGen (ω : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  ((1 / 2 : ℝ) : ℂ) • pauliAxis 0 0 ω

/-- The drive `U(t) = R_z(ωt) = e^{−i(ω/2)t σ₃}`, which turns `H(0)` into `H(t)`. -/
def drive (ω : ℝ) (t : ℝ) : Matrix (Fin 2) (Fin 2) ℂ := axisRot 0 0 1 (ω * t)

/-- The Rabi frequency `Ω = √((B sin θ)² + (B cos θ − ω)²)`: twice the energy gap of the
rotating-frame Hamiltonian `K = H(0) − (ω/2)σ₃`. -/
def rabiFreq (θ ω B : ℝ) : ℝ := Real.sqrt ((B * Real.sin θ) ^ 2 + (B * Real.cos θ - ω) ^ 2)

/-- The `x`-component of the unit axis of `K`. -/
def rabiAxisX (θ ω B : ℝ) : ℝ := B * Real.sin θ / rabiFreq θ ω B

/-- The `z`-component of the unit axis of `K`. -/
def rabiAxisZ (θ ω B : ℝ) : ℝ := (B * Real.cos θ - ω) / rabiFreq θ ω B

/-- The rotating-frame evolution `e^{−itK} = R_k(Ωt)`. -/
def rabiProp (θ ω B : ℝ) (t : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  axisRot (rabiAxisX θ ω B) 0 (rabiAxisZ θ ω B) (rabiFreq θ ω B * t)

/-- The propagator of the driven spin: the drive times the rotating-frame evolution. -/
def prop (θ ω B : ℝ) (t : ℝ) : Matrix (Fin 2) (Fin 2) ℂ := drive ω t * rabiProp θ ω B t

/-- The initial state: spin-up along `n(0)`, the `+B/2` eigenvector of `H(0)`. -/
def spinUp (θ : ℝ) : EuclideanSpace ℂ (Fin 2) :=
  WithLp.toLp 2 ![(Real.cos (θ / 2) : ℂ), (Real.sin (θ / 2) : ℂ)]

/-- The state of the spin at time `t`, started in `spinUp θ`. -/
def state (θ ω B : ℝ) (t : ℝ) : EuclideanSpace ℂ (Fin 2) :=
  Matrix.toEuclideanCLM (𝕜 := ℂ) (prop θ ω B t) (spinUp θ)

/-! ### The Rabi frequency and its axis -/

theorem rabiFreq_sq (θ ω B : ℝ) :
    rabiFreq θ ω B ^ 2 = (B * Real.sin θ) ^ 2 + (B * Real.cos θ - ω) ^ 2 :=
  Real.sq_sqrt (by positivity)

/-- The Rabi frequency is at least the detuning `B − ω`: the gap never closes below `B − ω`. -/
theorem sub_le_rabiFreq (θ : ℝ) {ω B : ℝ} (hω : 0 ≤ ω) (hB : 0 ≤ B) :
    B - ω ≤ rabiFreq θ ω B := by
  rcases le_or_gt (B - ω) 0 with h | h
  · exact h.trans (Real.sqrt_nonneg _)
  · rw [rabiFreq, show B - ω = Real.sqrt ((B - ω) ^ 2) from (Real.sqrt_sq h.le).symm]
    refine Real.sqrt_le_sqrt ?_
    have key : (B * Real.sin θ) ^ 2 + (B * Real.cos θ) ^ 2 = B ^ 2 := by
      linear_combination (B ^ 2) * Real.sin_sq_add_cos_sq θ
    nlinarith [key, mul_nonneg (mul_nonneg hB hω) (sub_nonneg.2 (Real.cos_le_one θ))]

theorem rabiFreq_pos {θ ω B : ℝ} (hω : 0 < ω) (hωB : ω < B) : 0 < rabiFreq θ ω B :=
  lt_of_lt_of_le (by linarith) (sub_le_rabiFreq θ hω.le (by linarith))

theorem rabiFreq_ne_zero {θ ω B : ℝ} (hω : 0 < ω) (hωB : ω < B) : rabiFreq θ ω B ≠ 0 :=
  (rabiFreq_pos hω hωB).ne'

/-- The axis of `K` is a unit vector. -/
theorem rabiAxis_unit {θ ω B : ℝ} (hΩ : rabiFreq θ ω B ≠ 0) :
    rabiAxisX θ ω B ^ 2 + (0 : ℝ) ^ 2 + rabiAxisZ θ ω B ^ 2 = 1 := by
  have h := rabiFreq_sq θ ω B
  rw [rabiAxisX, rabiAxisZ, div_pow, div_pow]
  field_simp
  linarith [h]

theorem zero_zero_one_unit : (0 : ℝ) ^ 2 + (0 : ℝ) ^ 2 + (1 : ℝ) ^ 2 = 1 := by norm_num

/-! ### The rigid rotation -/

theorem isHermitian_smul_pauliAxis (s a b c : ℝ) :
    (((s : ℝ) : ℂ) • pauliAxis a b c).IsHermitian := by
  show (((s : ℝ) : ℂ) • pauliAxis a b c)ᴴ = ((s : ℝ) : ℂ) • pauliAxis a b c
  rw [Matrix.conjTranspose_smul, (pauliAxis_isHermitian a b c).eq, RCLike.star_def,
    Complex.conj_ofReal]

theorem initHam_isHermitian (θ B : ℝ) : (initHam θ B).IsHermitian :=
  isHermitian_smul_pauliAxis _ _ _ _

theorem driveGen_isHermitian (ω : ℝ) : (driveGen ω).IsHermitian :=
  isHermitian_smul_pauliAxis _ _ _ _

theorem fieldHam_isHermitian (θ ω B t : ℝ) : (fieldHam θ ω B t).IsHermitian :=
  isHermitian_smul_pauliAxis _ _ _ _

theorem fieldHam_zero (θ ω B : ℝ) : fieldHam θ ω B 0 = initHam θ B := by
  rw [fieldHam, initHam, mul_zero, Real.cos_zero, Real.sin_zero, mul_zero, mul_one]

theorem driveGen_eq (ω : ℝ) : driveGen ω = ((ω / 2 : ℝ) : ℂ) • pauliAxis 0 0 1 := by
  rw [driveGen, smul_pauliAxis, smul_pauliAxis]
  congr 1 <;> ring

theorem drive_zero (ω : ℝ) : drive ω 0 = 1 := by
  rw [drive, mul_zero, axisRot_zero]

theorem drive_conjTranspose_mul (ω t : ℝ) : (drive ω t)ᴴ * drive ω t = 1 := by
  rw [drive, axisRot_conjTranspose, ← axisRot_add zero_zero_one_unit, neg_add_cancel, axisRot_zero]

/-- ★ **The field Hamiltonian is a rigid rotation of `H(0)`**: `H(t) = R_z(ωt) H(0) R_z(ωt)ᴴ`,
by the Bloch rotation `axisRot_z_conj`. -/
theorem drive_conj_initHam (θ ω B t : ℝ) :
    drive ω t * initHam θ B * (drive ω t)ᴴ = fieldHam θ ω B t := by
  rw [initHam, fieldHam, drive, Matrix.mul_smul, Matrix.smul_mul, axisRot_z_conj,
    show B * Real.sin θ * Real.cos (ω * t) - 0 * Real.sin (ω * t)
      = B * Real.sin θ * Real.cos (ω * t) from by ring,
    show B * Real.sin θ * Real.sin (ω * t) + 0 * Real.cos (ω * t)
      = B * Real.sin θ * Real.sin (ω * t) from by ring]

/-- ★ **The rotating-frame Hamiltonian** `K = H(0) − (ω/2)σ₃` is `(Ω/2) k·σ` for the unit axis
`k = (B sin θ, 0, B cos θ − ω)/Ω`. -/
theorem initHam_sub_driveGen {θ ω B : ℝ} (hΩ : rabiFreq θ ω B ≠ 0) :
    initHam θ B - driveGen ω
      = ((rabiFreq θ ω B / 2 : ℝ) : ℂ) • pauliAxis (rabiAxisX θ ω B) 0 (rabiAxisZ θ ω B) := by
  have hkey : ∀ x : ℝ, rabiFreq θ ω B / 2 * (x / rabiFreq θ ω B) = 1 / 2 * x := by
    intro x
    field_simp
  rw [initHam, driveGen, smul_pauliAxis, smul_pauliAxis, pauliAxis_sub, smul_pauliAxis,
    rabiAxisX, rabiAxisZ, hkey, hkey]
  congr 1 <;> ring

/-! ### The exact solution -/

theorem prop_zero (θ ω B : ℝ) : prop θ ω B 0 = 1 := by
  rw [prop, rabiProp, drive_zero, mul_zero, axisRot_zero, one_mul]

theorem rabiProp_conjTranspose_mul {θ ω B : ℝ} (hΩ : rabiFreq θ ω B ≠ 0) (t : ℝ) :
    (rabiProp θ ω B t)ᴴ * rabiProp θ ω B t = 1 := by
  rw [rabiProp, axisRot_conjTranspose, ← axisRot_add (rabiAxis_unit hΩ), neg_add_cancel,
    axisRot_zero]

theorem prop_conjTranspose_mul {θ ω B : ℝ} (hΩ : rabiFreq θ ω B ≠ 0) (t : ℝ) :
    (prop θ ω B t)ᴴ * prop θ ω B t = 1 := by
  rw [prop, Matrix.conjTranspose_mul, Matrix.mul_assoc, ← Matrix.mul_assoc ((drive ω t)ᴴ),
    drive_conjTranspose_mul, Matrix.one_mul, rabiProp_conjTranspose_mul hΩ]

/-- ★★★ **The time-dependent Schrödinger equation, solved exactly.** For a spin-½ in a field of
magnitude `B` precessing on the cone of half-angle `θ` at angular velocity `ω`, the propagator
`V(t) = R_z(ωt) · R_k(Ωt)` satisfies `V′(t) = −i H(t) V(t)`, with `V 0 = 1` (`prop_zero`) and
`V t` unitary (`prop_conjTranspose_mul`). No approximation and no time ordering: the drive is a
rigid rotation, so the rotating-frame generator `K` is constant. -/
theorem hasDerivAt_prop {θ ω B : ℝ} (hΩ : rabiFreq θ ω B ≠ 0) (t : ℝ) :
    HasDerivAt (prop θ ω B) ((-Complex.I) • (fieldHam θ ω B t * prop θ ω B t)) t := by
  have hu : HasDerivAt (drive ω) (drive ω t * ((-Complex.I) • driveGen ω)) t := by
    rw [driveGen_eq, smul_smul]
    exact hasDerivAt_axisRot_right zero_zero_one_unit ω t
  have he : HasDerivAt (rabiProp θ ω B)
      (((-Complex.I) • (initHam θ B - driveGen ω)) * rabiProp θ ω B t) t := by
    rw [initHam_sub_driveGen hΩ, smul_smul]
    exact hasDerivAt_axisRot (rabiAxis_unit hΩ) (rabiFreq θ ω B) t
  rw [← drive_conj_initHam]
  exact hasDerivAt_mul_of_gen hu he (drive_conjTranspose_mul ω t)

/-- ★★ **The state solves the Schrödinger equation.** -/
theorem hasDerivAt_state {θ ω B : ℝ} (hΩ : rabiFreq θ ω B ≠ 0) (t : ℝ) :
    HasDerivAt (state θ ω B)
      ((-Complex.I) • Matrix.toEuclideanCLM (𝕜 := ℂ) (fieldHam θ ω B t) (state θ ω B t)) t := by
  have h := ((Matrix.evalCLM (spinUp θ)).restrictScalars ℝ).hasFDerivAt.comp_hasDerivAt t
    (hasDerivAt_prop hΩ t)
  refine h.congr_deriv ?_
  show Matrix.evalCLM (spinUp θ) ((-Complex.I) • (fieldHam θ ω B t * prop θ ω B t)) = _
  rw [map_smul, Matrix.evalCLM_apply, Matrix.toEuclideanCLM_mul_apply, state]

/-! ### The instantaneous eigenvector is BP-2's cone curve -/

theorem coneCurve_ofLp (θ φ : ℝ) :
    (BerryPhase.coneCurve θ φ).ofLp
      = ![(Real.cos (θ / 2) : ℂ), Complex.exp ((φ : ℂ) * Complex.I) * (Real.sin (θ / 2) : ℂ)] := by
  rw [BerryPhase.coneCurve, WithLp.ofLp_toLp]

theorem coneCurve_zero_eq_spinUp (θ : ℝ) : BerryPhase.coneCurve θ 0 = spinUp θ := by
  rw [BerryPhase.coneCurve, spinUp]
  norm_num

/-- `e^{ix} = cos x + i sin x` with real casts, the one bridge between the `cos`/`sin` form of
`axisRot` and the exponential form of the cone curve. -/
theorem exp_ofReal_mul_I_eq (x : ℝ) :
    Complex.exp ((x : ℂ) * Complex.I)
      = (Real.cos x : ℂ) + Complex.I * (Real.sin x : ℂ) := by
  rw [Complex.exp_mul_I, ← Complex.ofReal_cos, ← Complex.ofReal_sin]
  ring

/-- ★★ **The cone curve of BP-2 is the instantaneous eigenvector of the rotating field**, with
eigenvalue `B/2`: `H(t) (cos θ/2, e^{iωt} sin θ/2) = (B/2) (cos θ/2, e^{iωt} sin θ/2)`. The ray
loop whose geometric phase `BerryPhase.geometricPhase_coneCurve` computed is therefore exactly the
loop this Hamiltonian traces out. -/
theorem fieldHam_mulVec_coneCurve (θ ω B t : ℝ) :
    fieldHam θ ω B t *ᵥ (BerryPhase.coneCurve θ (ω * t)).ofLp
      = ((B / 2 : ℝ) : ℂ) • (BerryPhase.coneCurve θ (ω * t)).ofLp := by
  have hcs : Complex.cos (θ : ℂ) * Complex.cos ((θ : ℂ) / 2)
      + Complex.sin (θ : ℂ) * Complex.sin ((θ : ℂ) / 2) = Complex.cos ((θ : ℂ) / 2) := by
    rw [← Complex.cos_sub, show (θ : ℂ) - (θ : ℂ) / 2 = (θ : ℂ) / 2 from by ring]
  have hsc : Complex.sin (θ : ℂ) * Complex.cos ((θ : ℂ) / 2)
      - Complex.cos (θ : ℂ) * Complex.sin ((θ : ℂ) / 2) = Complex.sin ((θ : ℂ) / 2) := by
    rw [← Complex.sin_sub, show (θ : ℂ) - (θ : ℂ) / 2 = (θ : ℂ) / 2 from by ring]
  have hpy := Complex.sin_sq_add_cos_sq ((ω : ℂ) * (t : ℂ))
  funext i
  fin_cases i
  · simp [fieldHam, coneCurve_ofLp, pauliAxis, Matrix.mulVec, dotProduct, Fin.sum_univ_two,
      Complex.exp_mul_I]
    linear_combination ((B : ℂ) / 2) * hcs
      + ((B : ℂ) / 2) * Complex.sin (θ : ℂ) * Complex.sin ((θ : ℂ) / 2) * hpy
      - ((B : ℂ) / 2) * Complex.sin (θ : ℂ) * Complex.sin ((θ : ℂ) / 2)
        * Complex.sin ((ω : ℂ) * (t : ℂ)) ^ 2 * Complex.I_mul_I
  · simp [fieldHam, coneCurve_ofLp, pauliAxis, Matrix.mulVec, dotProduct, Fin.sum_univ_two,
      Complex.exp_mul_I]
    linear_combination ((B : ℂ) / 2) * (Complex.cos ((ω : ℂ) * (t : ℂ))
      + Complex.I * Complex.sin ((ω : ℂ) * (t : ℂ))) * hsc

/-! ### The Rabi overlap -/

/-- `cos δ = k·n(0) = (B − ω cos θ)/Ω`, the cosine of the angle between the rotating-frame axis and
the initial field direction. One exact identity, ★ `one_sub_cosDelta_sq`, controls the whole
adiabatic error: `1 − cos²δ = (ω sin θ/Ω)²`. -/
def cosDelta (θ ω B : ℝ) : ℝ := (B - ω * Real.cos θ) / rabiFreq θ ω B

theorem rabiFreq_sq_sub (θ ω B : ℝ) :
    rabiFreq θ ω B ^ 2 - (B - ω * Real.cos θ) ^ 2 = (ω * Real.sin θ) ^ 2 := by
  rw [rabiFreq_sq]
  linear_combination (B ^ 2 - ω ^ 2) * Real.sin_sq_add_cos_sq θ

theorem rabiAxis_dot (θ ω B : ℝ) :
    rabiAxisX θ ω B * Real.sin θ + rabiAxisZ θ ω B * Real.cos θ = cosDelta θ ω B := by
  rw [rabiAxisX, rabiAxisZ, cosDelta, div_mul_eq_mul_div, div_mul_eq_mul_div, ← add_div]
  congr 1
  linear_combination B * Real.sin_sq_add_cos_sq θ

/-- ★ **The one exact identity behind both adiabatic bounds.** -/
theorem one_sub_cosDelta_sq {θ ω B : ℝ} (hΩ : rabiFreq θ ω B ≠ 0) :
    1 - cosDelta θ ω B ^ 2 = (ω * Real.sin θ / rabiFreq θ ω B) ^ 2 := by
  have hne : rabiFreq θ ω B ^ 2 ≠ 0 := pow_ne_zero 2 hΩ
  rw [cosDelta, div_pow, div_pow, eq_div_iff hne, sub_mul, one_mul, div_mul_cancel₀ _ hne]
  linear_combination rabiFreq_sq_sub θ ω B

theorem cosDelta_nonneg {θ ω B : ℝ} (hω : 0 < ω) (hωB : ω < B) : 0 ≤ cosDelta θ ω B := by
  refine div_nonneg ?_ (Real.sqrt_nonneg _)
  nlinarith [mul_le_mul_of_nonneg_left (Real.cos_le_one θ) hω.le]

theorem cosDelta_le_one {θ ω B : ℝ} (hΩ : rabiFreq θ ω B ≠ 0) : cosDelta θ ω B ≤ 1 := by
  nlinarith [one_sub_cosDelta_sq hΩ, sq_nonneg (ω * Real.sin θ / rabiFreq θ ω B),
    sq_nonneg (cosDelta θ ω B - 1)]

/-! ### Inner products of two-component states -/

theorem toEuclideanCLM_apply_eq (M : Matrix (Fin 2) (Fin 2) ℂ) (x : EuclideanSpace ℂ (Fin 2)) :
    Matrix.toEuclideanCLM (𝕜 := ℂ) M x = WithLp.toLp 2 (M *ᵥ x.ofLp) := rfl

theorem inner_toLp (x y : Fin 2 → ℂ) :
    inner ℂ (WithLp.toLp 2 x : EuclideanSpace ℂ (Fin 2)) (WithLp.toLp 2 y)
      = (starRingEnd ℂ) (x 0) * y 0 + (starRingEnd ℂ) (x 1) * y 1 := by
  rw [PiLp.inner_apply, Fin.sum_univ_two]
  simp [RCLike.inner_apply, mul_comm]

theorem spinUp_ofLp (θ : ℝ) :
    (spinUp θ).ofLp = ![(Real.cos (θ / 2) : ℂ), (Real.sin (θ / 2) : ℂ)] := by
  rw [spinUp, WithLp.ofLp_toLp]

/-- The inner product against the (real) initial state, with the conjugation already taken. -/
theorem inner_spinUp_toLp (θ : ℝ) (y : Fin 2 → ℂ) :
    inner ℂ (spinUp θ) (WithLp.toLp 2 y : EuclideanSpace ℂ (Fin 2))
      = ((Real.cos (θ / 2) : ℝ) : ℂ) * y 0 + ((Real.sin (θ / 2) : ℝ) : ℂ) * y 1 := by
  rw [spinUp, inner_toLp]
  simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Complex.conj_ofReal]

theorem inner_spinUp_self (θ : ℝ) : inner ℂ (spinUp θ) (spinUp θ) = 1 := by
  rw [spinUp, inner_toLp]
  simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Complex.conj_ofReal]
  norm_cast
  linear_combination Real.sin_sq_add_cos_sq (θ / 2)

/-- ★ **The Bloch expectation of `n·σ` in the state spin-up along `n(0)`** is `n·n(0)`; the
`σ₂`-component drops out because the state is real. -/
theorem inner_spinUp_pauliAxis (θ a b c : ℝ) :
    inner ℂ (spinUp θ) (Matrix.toEuclideanCLM (𝕜 := ℂ) (pauliAxis a b c) (spinUp θ))
      = ((a * Real.sin θ + c * Real.cos θ : ℝ) : ℂ) := by
  have hc : Real.cos θ = Real.cos (θ / 2) ^ 2 - Real.sin (θ / 2) ^ 2 := by
    rw [← Real.cos_two_mul' (θ / 2), show 2 * (θ / 2) = θ from by ring]
  have hs : Real.sin θ = 2 * Real.sin (θ / 2) * Real.cos (θ / 2) := by
    rw [← Real.sin_two_mul (θ / 2), show 2 * (θ / 2) = θ from by ring]
  rw [toEuclideanCLM_apply_eq, inner_spinUp_toLp, spinUp_ofLp, hc, hs]
  simp only [pauliAxis, Matrix.mulVec, dotProduct, Fin.sum_univ_two, Matrix.of_apply,
    Matrix.cons_val', Matrix.cons_val_zero, Matrix.cons_val_one,
    Matrix.empty_val', Matrix.cons_val_fin_one]
  push_cast
  ring

/-- ★★ **The Rabi overlap.** The rotating-frame evolution has diagonal matrix element
`⟪ψ₀, e^{−itK} ψ₀⟫ = cos(Ωt/2) − i cos δ sin(Ωt/2)` in the initial eigenstate. -/
theorem inner_spinUp_rabiProp (θ ω B t : ℝ) :
    inner ℂ (spinUp θ) (Matrix.toEuclideanCLM (𝕜 := ℂ) (rabiProp θ ω B t) (spinUp θ))
      = ((Real.cos (rabiFreq θ ω B * t / 2) : ℝ) : ℂ)
        - Complex.I * ((cosDelta θ ω B * Real.sin (rabiFreq θ ω B * t / 2) : ℝ) : ℂ) := by
  have hE : ∀ M : Matrix (Fin 2) (Fin 2) ℂ,
      Matrix.toEuclideanCLM (𝕜 := ℂ) M (spinUp θ) = Matrix.evalCLM (spinUp θ) M := fun _ => rfl
  have hone : Matrix.evalCLM (spinUp θ) (1 : Matrix (Fin 2) (Fin 2) ℂ) = spinUp θ := by
    rw [Matrix.evalCLM_apply, map_one, one_apply_eq_self]
  rw [rabiProp, axisRot_eq, hE, map_sub, map_smul, map_smul, inner_sub_right, inner_smul_right,
    inner_smul_right, hone, inner_spinUp_self, ← hE, inner_spinUp_pauliAxis, rabiAxis_dot]
  push_cast
  ring

/-! ### The state in the instantaneous eigenbasis -/

theorem drive_mulVec_spinUp (θ ω t : ℝ) :
    drive ω t *ᵥ (spinUp θ).ofLp
      = ![Complex.exp (((-(ω * t / 2) : ℝ) : ℂ) * Complex.I) * (Real.cos (θ / 2) : ℂ),
          Complex.exp ((((ω * t / 2) : ℝ) : ℂ) * Complex.I) * (Real.sin (θ / 2) : ℂ)] := by
  have hm : Complex.exp (((-(ω * t / 2) : ℝ) : ℂ) * Complex.I)
      = ((Real.cos (ω * t / 2) : ℝ) : ℂ)
        - Complex.I * ((Real.sin (ω * t / 2) : ℝ) : ℂ) := by
    rw [exp_ofReal_mul_I_eq, Real.cos_neg, Real.sin_neg]
    push_cast
    ring
  have hp : Complex.exp ((((ω * t / 2) : ℝ) : ℂ) * Complex.I)
      = ((Real.cos (ω * t / 2) : ℝ) : ℂ)
        + Complex.I * ((Real.sin (ω * t / 2) : ℝ) : ℂ) := exp_ofReal_mul_I_eq _
  rw [hm, hp]
  funext i
  fin_cases i <;>
    simp only [drive, axisRot, su2, spinUp_ofLp, Matrix.mulVec, dotProduct, Fin.sum_univ_two,
      Matrix.of_apply, Matrix.cons_val', Matrix.cons_val_zero, Matrix.cons_val_one,
      Matrix.empty_val', Matrix.cons_val_fin_one] <;>
    push_cast <;>
    ring

theorem exp_real_add (x y : ℝ) :
    Complex.exp (((x + y : ℝ) : ℂ) * Complex.I)
      = Complex.exp ((x : ℂ) * Complex.I) * Complex.exp ((y : ℂ) * Complex.I) := by
  rw [← Complex.exp_add]
  congr 1
  push_cast
  ring

/-- ★ **BP-2's cone curve is the drive applied to the initial eigenstate**, up to the phase
`e^{iωt/2}`: the two lifts of the same ray loop differ by a gauge, which is exactly what
`GeometricPhase.geometricPhase_rephase` says the geometric phase does not see. -/
theorem coneCurve_eq_smul_drive (θ ω t : ℝ) :
    BerryPhase.coneCurve θ (ω * t)
      = Complex.exp ((((ω * t / 2) : ℝ) : ℂ) * Complex.I)
        • Matrix.toEuclideanCLM (𝕜 := ℂ) (drive ω t) (spinUp θ) := by
  have h0 : Complex.exp ((((ω * t / 2) : ℝ) : ℂ) * Complex.I)
      * Complex.exp (((-(ω * t / 2) : ℝ) : ℂ) * Complex.I) = 1 := by
    rw [← exp_real_add, show ω * t / 2 + -(ω * t / 2) = 0 from by ring]
    norm_num
  have h1 : Complex.exp ((((ω * t / 2) : ℝ) : ℂ) * Complex.I)
      * Complex.exp ((((ω * t / 2) : ℝ) : ℂ) * Complex.I)
      = Complex.exp (((ω * t : ℝ) : ℂ) * Complex.I) := by
    rw [← exp_real_add, show ω * t / 2 + ω * t / 2 = ω * t from by ring]
  apply WithLp.ofLp_injective
  rw [coneCurve_ofLp, WithLp.ofLp_smul, toEuclideanCLM_apply_eq, WithLp.ofLp_toLp,
    drive_mulVec_spinUp]
  simp only [Matrix.smul_cons, Matrix.smul_empty, smul_eq_mul, ← mul_assoc, h0, h1, one_mul]

theorem inner_coneCurve_state (θ ω B t : ℝ) :
    inner ℂ (BerryPhase.coneCurve θ (ω * t)) (state θ ω B t)
      = (starRingEnd ℂ) (Complex.exp ((((ω * t / 2) : ℝ) : ℂ) * Complex.I))
        * inner ℂ (spinUp θ) (Matrix.toEuclideanCLM (𝕜 := ℂ) (rabiProp θ ω B t) (spinUp θ)) := by
  rw [coneCurve_eq_smul_drive, inner_smul_left, state, prop, Matrix.toEuclideanCLM_mul_apply,
    inner_toEuclideanCLM_unitary (drive_conjTranspose_mul ω t)]

/-- ★★★ **Adiabatic following, exactly.** The probability of still being in the instantaneous
eigenstate at time `t` is `1 − (ω sin θ/Ω)² sin²(Ωt/2)`: an exact Rabi formula, with no
approximation anywhere. -/
theorem norm_inner_coneCurve_state_sq {θ ω B : ℝ} (hΩ : rabiFreq θ ω B ≠ 0) (t : ℝ) :
    ‖inner ℂ (BerryPhase.coneCurve θ (ω * t)) (state θ ω B t)‖ ^ 2
      = 1 - (ω * Real.sin θ / rabiFreq θ ω B) ^ 2
        * Real.sin (rabiFreq θ ω B * t / 2) ^ 2 := by
  rw [inner_coneCurve_state, inner_spinUp_rabiProp, norm_mul, RCLike.norm_conj,
    Complex.norm_exp_ofReal_mul_I, one_mul, Complex.sq_norm, Complex.normSq_apply]
  simp only [Complex.sub_re, Complex.sub_im, Complex.mul_re, Complex.mul_im, Complex.I_re,
    Complex.I_im, Complex.ofReal_re, Complex.ofReal_im, zero_mul, one_mul, sub_zero, zero_sub,
    mul_zero, zero_add, neg_mul, mul_neg, neg_neg]
  linear_combination Real.sin_sq_add_cos_sq (rabiFreq θ ω B * t / 2)
    - Real.sin (rabiFreq θ ω B * t / 2) ^ 2 * one_sub_cosDelta_sq hΩ

/-- ★★★ **The adiabatic theorem for this model**: for `0 < ω < B` the spin stays in the
instantaneous eigenstate up to a probability `(ω/(B − ω))²`, *uniformly in time* — the rotating
frame is exact here, so no `T`-dependence is lost. -/
theorem one_sub_le_norm_inner_coneCurve_state_sq {θ ω B : ℝ} (hω : 0 < ω) (hωB : ω < B) (t : ℝ) :
    1 - (ω / (B - ω)) ^ 2
      ≤ ‖inner ℂ (BerryPhase.coneCurve θ (ω * t)) (state θ ω B t)‖ ^ 2 := by
  have hd : 0 < B - ω := by linarith
  have hΩ := rabiFreq_ne_zero (θ := θ) hω hωB
  have hΩge : B - ω ≤ rabiFreq θ ω B := sub_le_rabiFreq θ hω.le (by linarith)
  have hnum : (ω * Real.sin θ) ^ 2 ≤ ω ^ 2 := by
    nlinarith [Real.sin_sq_le_one θ, sq_nonneg ω]
  have hden : (B - ω) ^ 2 ≤ rabiFreq θ ω B ^ 2 := by nlinarith
  have hfrac : (ω * Real.sin θ / rabiFreq θ ω B) ^ 2 ≤ (ω / (B - ω)) ^ 2 := by
    rw [div_pow, div_pow]
    exact div_le_div₀ (by positivity) hnum (by positivity) hden
  rw [norm_inner_coneCurve_state_sq hΩ]
  nlinarith [Real.sin_sq_le_one (rabiFreq θ ω B * t / 2), hfrac,
    sq_nonneg (ω * Real.sin θ / rabiFreq θ ω B),
    sq_nonneg (Real.sin (rabiFreq θ ω B * t / 2))]

/-! ### The phase after one turn -/

/-- ★ **The geometric phase of the loop the field traces in one turn** is BP-2's
`−π(1 − cos θ)`, in the repo's own `GeometricPhase.geometricPhase`: the reparametrisation
`t ↦ ωt` does not change it. -/
theorem geometricPhase_cone_loop (θ : ℝ) {ω T : ℝ} (hT : ω * T = 2 * π) :
    geometricPhase (fun t => BerryPhase.coneCurve θ (ω * t)) T 0 = -π * (1 - Real.cos θ) := by
  have hderiv : ∀ t : ℝ, HasDerivAt (fun s : ℝ => BerryPhase.coneCurve θ (ω * s))
      (ω • WithLp.toLp 2 ![(0 : ℂ),
        Complex.I * Complex.exp (((ω * t : ℝ) : ℂ) * Complex.I) * (Real.sin (θ / 2) : ℂ)]) t := by
    intro t
    have hin : HasDerivAt (fun s : ℝ => ω * s) ω t := by
      simpa using (hasDerivAt_id t).const_mul ω
    exact (BerryPhase.hasDerivAt_coneCurve θ (ω * t)).scomp t hin
  have hconn : ∀ t : ℝ, connectionForm (fun s : ℝ => BerryPhase.coneCurve θ (ω * s)) t
      = ω * Real.sin (θ / 2) ^ 2 := by
    intro t
    have h1 : connectionForm (BerryPhase.coneCurve θ) (ω * t) = Real.sin (θ / 2) ^ 2 :=
      BerryPhase.connectionForm_coneCurve θ (ω * t)
    rw [connectionForm, (BerryPhase.hasDerivAt_coneCurve θ (ω * t)).deriv] at h1
    rw [connectionForm, (hderiv t).deriv, RCLike.real_smul_eq_coe_smul (K := ℂ),
      inner_smul_right, Complex.mul_im]
    rw [h1]
    simp
  rw [geometricPhase, dynamicalPhase]
  have hfun : (fun t => connectionForm (fun s : ℝ => BerryPhase.coneCurve θ (ω * s)) t)
      = fun _ => ω * Real.sin (θ / 2) ^ 2 := funext hconn
  rw [hfun, intervalIntegral.integral_const, Real.sin_sq_eq_half_sub,
    show 2 * (θ / 2) = θ from by ring]
  simp only [sub_zero, smul_eq_mul]
  linear_combination (-(1 : ℝ) / 2 + Real.cos θ / 2) * hT

theorem drive_period {ω T : ℝ} (hT : ω * T = 2 * π) : drive ω T = -1 := by
  rw [drive, hT, axisRot_two_pi]

theorem state_period {θ ω B T : ℝ} (hT : ω * T = 2 * π) :
    state θ ω B T = -Matrix.toEuclideanCLM (𝕜 := ℂ) (rabiProp θ ω B T) (spinUp θ) := by
  rw [state, prop, drive_period hT, neg_mul, one_mul, map_neg, neg_apply]

theorem inner_spinUp_state_period {θ ω B T : ℝ} (hT : ω * T = 2 * π) :
    inner ℂ (spinUp θ) (state θ ω B T)
      = -(((Real.cos (rabiFreq θ ω B * T / 2) : ℝ) : ℂ)
        - Complex.I * ((cosDelta θ ω B * Real.sin (rabiFreq θ ω B * T / 2) : ℝ) : ℂ)) := by
  rw [state_period hT, inner_neg_right, inner_spinUp_rabiProp]

/-- ★★★ **The phase at the end of one turn is dynamical plus geometric.** For `0 < ω < B` and
`ωT = 2π`, the overlap of the final state with the initial eigenstate is
`e^{i(−(B/2)T − π(1 − cos θ))}` up to an error `πω/(2(B − ω)) + (ω/(B − ω))²`: the dynamical phase
`−(B/2)T = −∫₀ᵀ E dt` plus the geometric phase `−π(1 − cos θ)` of BP-2
(★ `geometricPhase_cone_loop`), with an `O(ω)` error that is explicit, not asymptotic. -/
theorem norm_inner_state_sub_exp_le {θ ω B T : ℝ} (hω : 0 < ω) (hωB : ω < B)
    (hT : ω * T = 2 * π) :
    ‖inner ℂ (spinUp θ) (state θ ω B T)
        - Complex.exp (((-(B / 2) * T - π * (1 - Real.cos θ) : ℝ) : ℂ) * Complex.I)‖
      ≤ π * ω / (2 * (B - ω)) + (ω / (B - ω)) ^ 2 := by
  have hd : 0 < B - ω := by linarith
  have hΩ := rabiFreq_ne_zero (θ := θ) hω hωB
  have hΩpos := rabiFreq_pos (θ := θ) hω hωB
  have hΩge : B - ω ≤ rabiFreq θ ω B := sub_le_rabiFreq θ hω.le (by linarith)
  have hTpos : 0 < T := by nlinarith [Real.pi_pos]
  -- notation
  obtain ⟨Ω, hΩdef⟩ : ∃ x, x = rabiFreq θ ω B := ⟨_, rfl⟩
  obtain ⟨c, hcdef⟩ : ∃ x, x = cosDelta θ ω B := ⟨_, rfl⟩
  obtain ⟨φ, hφdef⟩ : ∃ x, x = -(B / 2) * T - π * (1 - Real.cos θ) := ⟨_, rfl⟩
  obtain ⟨ε, hεdef⟩ : ∃ x, x = T / 2 * (Ω - (B - ω * Real.cos θ)) := ⟨_, rfl⟩
  obtain ⟨C, hCdef⟩ : ∃ x, x = Real.cos (Ω * T / 2) := ⟨_, rfl⟩
  obtain ⟨S, hSdef⟩ : ∃ x, x = Real.sin (Ω * T / 2) := ⟨_, rfl⟩
  -- the two exponential identities
  have hexpC : Complex.exp (((-(Ω * T / 2) : ℝ) : ℂ) * Complex.I)
      = ((C : ℝ) : ℂ) - Complex.I * ((S : ℝ) : ℂ) := by
    rw [hCdef, hSdef, exp_ofReal_mul_I_eq, Real.cos_neg, Real.sin_neg]
    push_cast
    ring
  have hsum : φ + -ε = (π - Ω * T / 2) + -(2 * π) := by
    rw [hφdef, hεdef]
    linear_combination (-(Real.cos θ) / 2) * hT
  have h2pi : Complex.exp (((-(2 * π) : ℝ) : ℂ) * Complex.I) = 1 := by
    rw [show (((-(2 * π) : ℝ) : ℂ) * Complex.I) = -(2 * (π : ℂ) * Complex.I) from by
      push_cast; ring, Complex.exp_neg, Complex.exp_two_pi_mul_I, inv_one]
  have hpi : Complex.exp (((π : ℝ) : ℂ) * Complex.I) = -1 := Complex.exp_pi_mul_I
  have hexp : -Complex.exp (((-(Ω * T / 2) : ℝ) : ℂ) * Complex.I)
      = Complex.exp ((φ : ℂ) * Complex.I) * Complex.exp (((-ε : ℝ) : ℂ) * Complex.I) := by
    rw [← exp_real_add, hsum, exp_real_add, h2pi, mul_one,
      show (π - Ω * T / 2 : ℝ) = π + -(Ω * T / 2) from by ring, exp_real_add, hpi]
    ring
  -- the split
  have hAE : -(((C : ℝ) : ℂ) - Complex.I * ((c * S : ℝ) : ℂ))
      - Complex.exp ((φ : ℂ) * Complex.I)
      = Complex.I * ((S * (c - 1) : ℝ) : ℂ)
        + Complex.exp ((φ : ℂ) * Complex.I)
          * (Complex.exp (((-ε : ℝ) : ℂ) * Complex.I) - 1) := by
    push_cast at hexp hexpC ⊢
    linear_combination hexp + hexpC
  -- the two bounds
  have hcle : c ≤ 1 := by rw [hcdef]; exact cosDelta_le_one hΩ
  have hcnn : 0 ≤ c := by rw [hcdef]; exact cosDelta_nonneg hω hωB
  have hone := one_sub_cosDelta_sq (θ := θ) (ω := ω) (B := B) hΩ
  rw [← hcdef, ← hΩdef] at hone
  have hnum : (ω * Real.sin θ) ^ 2 ≤ ω ^ 2 := by nlinarith [Real.sin_sq_le_one θ, sq_nonneg ω]
  have hden : (B - ω) ^ 2 ≤ Ω ^ 2 := by rw [hΩdef]; nlinarith
  have hfrac : (ω * Real.sin θ / Ω) ^ 2 ≤ (ω / (B - ω)) ^ 2 := by
    rw [div_pow, div_pow]
    exact div_le_div₀ (by positivity) hnum (by positivity) hden
  have hb1 : ‖Complex.I * ((S * (c - 1) : ℝ) : ℂ)‖ ≤ (ω / (B - ω)) ^ 2 := by
    rw [norm_mul, Complex.norm_I, one_mul, Complex.norm_real, Real.norm_eq_abs, abs_mul]
    have habs : |c - 1| = 1 - c := by rw [abs_sub_comm, abs_of_nonneg (by linarith)]
    rw [habs]
    have hsle : |S| ≤ 1 := by rw [hSdef]; exact Real.abs_sin_le_one _
    have hstep : 1 - c ≤ (ω * Real.sin θ / Ω) ^ 2 := by
      nlinarith [hone, hcnn, hcle]
    nlinarith [abs_nonneg S, hstep, hfrac, hcnn, hcle]
  have hb2 : ‖Complex.exp ((φ : ℂ) * Complex.I)
      * (Complex.exp (((-ε : ℝ) : ℂ) * Complex.I) - 1)‖ ≤ π * ω / (2 * (B - ω)) := by
    rw [norm_mul, Complex.norm_exp_ofReal_mul_I, one_mul]
    have hcomm : ((-ε : ℝ) : ℂ) * Complex.I = Complex.I * ((-ε : ℝ) : ℂ) := by ring
    rw [hcomm]
    refine le_trans Real.norm_exp_I_mul_ofReal_sub_one_le ?_
    rw [Real.norm_eq_abs]
    -- ε ≥ 0 and ε ≤ π ω / (2 (B − ω))
    have hXle : B - ω * Real.cos θ ≤ Ω := by
      have := cosDelta_le_one (θ := θ) (ω := ω) (B := B) hΩ
      rw [cosDelta, div_le_one hΩpos] at this
      rw [hΩdef]
      exact this
    have hεnn : 0 ≤ ε := by
      rw [hεdef]
      have : 0 ≤ T / 2 := by linarith
      nlinarith
    have hsum2 : 2 * (B - ω) ≤ Ω + (B - ω * Real.cos θ) := by
      nlinarith [mul_le_mul_of_nonneg_left (Real.cos_le_one θ) hω.le, hΩge, hΩdef]
    have hprod : (Ω - (B - ω * Real.cos θ)) * (Ω + (B - ω * Real.cos θ)) = (ω * Real.sin θ) ^ 2 := by
      rw [hΩdef]
      linear_combination rabiFreq_sq_sub θ ω B
    have hstep : Ω - (B - ω * Real.cos θ) ≤ ω ^ 2 / (2 * (B - ω)) := by
      rw [le_div_iff₀ (by positivity)]
      nlinarith [hprod, hsum2, sub_nonneg.2 hXle, Real.sin_sq_le_one θ]
    rw [abs_neg, abs_of_nonneg hεnn, hεdef]
    have hTnn : 0 ≤ T / 2 := by linarith
    calc T / 2 * (Ω - (B - ω * Real.cos θ)) ≤ T / 2 * (ω ^ 2 / (2 * (B - ω))) :=
          mul_le_mul_of_nonneg_left hstep hTnn
      _ = π * ω / (2 * (B - ω)) := by
          field_simp
          linear_combination hT
  rw [inner_spinUp_state_period hT, ← hΩdef, ← hCdef, ← hSdef, ← hcdef, ← hφdef, hAE]
  refine le_trans (norm_add_le _ _) ?_
  linarith [hb1, hb2]

end BerryAdiabatic
end QM
end Empirical
end CSD

end
