/-
Copyright (c) 2026 Zayn Blore. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zayn Blore
-/
module

public import CsdLean4.SigmaLayer.MeasureBridge

/-!
# SigmaLayer/DynamicsBridge: projectable dynamics and its Hamiltonian realisation

**Category:** 7-SigmaLayer (the projective-sector layer (Paper C)).

Bridge assumption B2: the ontic flow is projectable through `pi` (there is an induced flow on the
projective sector). `ProjectiveDynamicsBridge` bundles the projected flow, its one-parameter-group laws
and the projectability equation. For the concrete product model
(`productDynamics`/`productSector`) the projected flow is `exp(-itH)`-conjugation on rays, so it is
projectable AND has a Hamiltonian realisation: theorem target T5 (`HasHamiltonianRealisation`) is
inhabited for this concrete model, reusing `manyToOneSchrodingerSetup_schrodinger_form` and
`expNegITH_unitary_group`.

Unitarity of the projected flow is NOT a field of `ProjectiveSector`; it is the separate target
`HasUnitaryRealisation` / `HasHamiltonianRealisation`, proved only where a concrete model supplies it.
-/

@[expose] public section

open MeasureTheory
open scoped LinearAlgebra.Projectivization

namespace CSD.SigmaLayer

universe u

/-- **Projective dynamics bridge (B2 interface).** The projected flow, its measurability, the
projectability equation `pi (flow t x) = projectedFlow t (pi x)`, and the one-parameter-group laws of
the projected flow. -/
structure ProjectiveDynamicsBridge {N : ℕ} {Sigma : Type u} [MeasurableSpace Sigma]
    {D : ConstraintDynamics Sigma} (Q : ProjectiveSector N D) where
  /-- The induced flow on the projective sector. -/
  projectedFlow : OnticTime → ProjectiveState N → ProjectiveState N
  /-- Each projected time-`t` map is measurable. -/
  measurable_projectedFlow : ∀ t, Measurable (projectedFlow t)
  /-- The ontic flow descends through `pi` to the projected flow. -/
  projectable : ∀ t x, Q.pi (D.flow t x) = projectedFlow t (Q.pi x)
  /-- The projected flow is the identity at time `0`. -/
  projected_zero : ∀ p, projectedFlow 0 p = p
  /-- The projected flow composes additively in time. -/
  projected_add : ∀ s t p, projectedFlow (s + t) p = projectedFlow s (projectedFlow t p)

/-! ### The concrete product instance: projectable, Hamiltonian-realised -/

variable {M : ℕ} (H : Matrix (Fin (M + 1)) (Fin (M + 1)) ℂ) (hH : H.IsHermitian)
  (p₀ : CSD.LF4.CPN (M + 1))

/-- The projected flow of the product model: `exp(-itH)`-conjugation on rays. -/
noncomputable def productProjectedFlow :
    OnticTime → ProjectiveState (M + 1) → ProjectiveState (M + 1) :=
  fun t p => CSD.LF4.schrodingerUnitary hH t • p

/-- **The product model is projectable with `exp(-itH)`-conjugation as its projected flow (B2 proved).**
The ontic flow descends through `pi = Prod.fst` to `exp(-itH) • ·`, with the projected group laws from
`expNegITH_unitary_group`. -/
noncomputable def productDynamicsBridge :
    ProjectiveDynamicsBridge (productSector H hH p₀) where
  projectedFlow := productProjectedFlow H hH
  measurable_projectedFlow := fun t => (continuous_const_smul (CSD.LF4.schrodingerUnitary hH t)).measurable
  projectable := fun t x => CSD.LF4.manyToOneSchrodingerSetup_schrodinger_form H hH p₀ t x
  projected_zero := fun p => by
    simp only [productProjectedFlow, (CSD.LF4.expNegITH_unitary_group hH).2, one_smul]
  projected_add := fun s t p => by
    simp only [productProjectedFlow, (CSD.LF4.expNegITH_unitary_group hH).1, mul_smul]

/-- **T5 inhabited for the product model: the projected flow has a Hamiltonian realisation.** The
projected flow is generated by the Hermitian `H` via `exp(-itH)`; a concrete inhabitant of
`HasHamiltonianRealisation`, not a postulate. -/
theorem productProjectedFlow_hasHamiltonianRealisation :
    HasHamiltonianRealisation (productProjectedFlow H hH) :=
  ⟨H, hH, fun _ _ => rfl⟩

/-- **T4 inhabited for the product model: the projected flow has a unitary realisation.** The Hamiltonian
realisation is in particular a unitary realisation. -/
theorem productProjectedFlow_hasUnitaryRealisation :
    HasUnitaryRealisation (productProjectedFlow H hH) :=
  ⟨fun t => CSD.LF4.schrodingerUnitary hH t, fun _ _ => rfl⟩

end CSD.SigmaLayer
