/-
Copyright (c) 2026 Zayn Blore. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zayn Blore
-/
module

public import CsdLean4.SigmaLayer.PointerBorn

/-!
# SigmaLayer/JointFlowTransfer: back-reaction is harmless to records and Born

**Category:** dynamical measurement — `specs/BACKLOG.md` **A1**, the formalisable half of
the joint-arena Hamiltonian route.

## The problem this solves

Paper C A2 / TN6 ask for measurement generated by a scalar `𝓗` on the **whole** arena. The
corpus's smooth witness is *fibrewise*: `pointerEvolve` freezes the ontic coordinate
(`pointerEvolve_fst : (pointerEvolve c ε y).1 = y.1`, by `rfl`), so it is not the flow of
any interaction scalar wherever the weights vary (`PointerGeneration.lean`'s boundary
note). A genuine joint flow **moves the base too** — it back-reacts — and the worry is that
the back-reaction destroys the landing and Born analysis built on the frozen-base map.

This module proves it does not, and isolates exactly why.

## What is proved

`IsJointLift c ε Φ` asks of a candidate joint flow `Φ` only three things: its **pointer
component agrees** with the fibrewise witness, and it **conserves the context rates and the
register coordinate**. Then:

* ★★ `IsJointLift.outcomeSector_eq` — `Φ`'s record preimage is the **same set** as the
  fibrewise witness's outcome sector. Not "the same measure": literally the same set. The
  record regions are cylinders over the pointer (`arenaRecord N j = univ ×ˢ recordRegion j`),
  so horizontal motion cannot be seen by them.
* ★ `IsJointLift.landing`, `IsJointLift.born_lower`, `IsJointLift.born_upper` — landing and
  the full `ε`-Born sandwich hold for `Φ`, transported along that set equality with no
  measure-theoretic work at all.
* `IsJointLift.weights_conserved` — the weight field is constant along `Φ`. This is where
  the Poisson argument plugs in: it is exactly what `{wᵢ,wⱼ} = 0` delivers, and it is what
  makes iterating the stroke well-defined.
* ★ `IsJointLift.moment_marginal_unchanged` — **the honest replacement for the no-collapse
  theorem.** `pointerEvolve_base_marginal_unchanged` says the fibrewise witness leaves the
  *sector marginal* untouched; under a genuine lift that is false, because the base point
  moves inside its moment fibre. What survives — and all that is needed — is that the
  **moment-and-register** data is unchanged.
* `isJointLift_pointerEvolve` — the fibrewise witness is itself a joint lift, so none of
  this is vacuous.

## Why the hypotheses are these and not the obvious ones

The first draft of this row asked for "arena-measure preservation" and "`basinIndex`
conserved". Both were wrong, and the corrections are worth recording:

* Born is measured against `pointerPrep`, a base-**Dirac** slice (`epistemicMeasure p ⊗
  ready-conditioned FS`), which is **null** for the arena Liouville measure. So
  "Hamiltonian ⇒ Liouville-preserving" says *nothing* about the Born statements. What
  actually carries them is the set equality above.
* `basinIndex` is the selector of the *shear/swap* witnesses. The smooth witness lands on
  `shrunkCell` membership instead. Conserving the rates and the register conserves both;
  conserving `basinIndex` alone would not.

⚠️ **Honest scope.** (i) This is a **conditional** (`CONVENTIONS.md` §8.3 `_of_` pattern):
it makes back-reaction harmless *given* the three hypotheses, and does not construct a
joint flow satisfying them. Discharging them for the actual `X_𝓗` is the paper's job
(`BACKLOG.md` A2) and needs `{wᵢ,wⱼ} = 0`, which is well-formed only now that the weights
are `C^∞` (`SmoothProfile.lean`, B1). (ii) The transfer covers the **single measurement
stroke** — landing and the sector Born. The protocol's two-time laws and persistence are
statements about a whole propagator family, not about one map, and are not restated here.
(iii) Nothing here says the joint flow is Hamiltonian; that identification is the
§2a-scoped arrow (`MATHLIB-GAPS.md`). (iv) There is no perturbative version: `circleCell`
is half-open and `rep` jumps at `0`, so the selector is discontinuous in the conserved
data — *approximate* conservation buys nothing without a separate collar estimate.

## References

`specs/BACKLOG.md` A1 (this row), A2 (the paper half), B1 (the discharged prerequisite);
`SigmaLayer/PointerLanding.lean` (`pointer_landing`), `SigmaLayer/PointerBorn.lean`
(`pointer_born_lower`/`_upper`, `pointerPrep`), `SigmaLayer/PointerGeneration.lean` (the
fibrewise boundary this answers), `SigmaLayer/PointerWeights.lean`
(`contDiff_pointerWeights_lift`).
-/

@[expose] public section

namespace CSD.RecordLayer

open MeasureTheory

variable {N : ℕ} [NeZero N]

/-- **What a joint lift of the measurement stroke must satisfy.** Deliberately weak: the
pointer component agrees with the fibrewise witness, and the data the weights and the cell
geometry read — the context rates and the register coordinate — is conserved. The base
point itself is free to move, which is exactly what back-reaction does. -/
structure IsJointLift (c : ContextField N) (ε : ℝ)
    (Φ : PointerArena N N → PointerArena N N) : Prop where
  /-- The pointer is driven by the same fixed-weight propagator. -/
  pointer_eq : ∀ y, (Φ y).2 = (pointerEvolve c ε y).2
  /-- The context rates (the moments, for `momentContext`) are constants of motion. -/
  rate_conserved : ∀ y j, c.rate (Φ y).1.1 j = c.rate y.1.1 j
  /-- The register coordinate is a constant of motion. -/
  register_conserved : ∀ y, (Φ y).1.2.1 = y.1.2.1

namespace IsJointLift

variable {c : ContextField N} {ε : ℝ} {Φ : PointerArena N N → PointerArena N N}

omit [NeZero N] in
/-- Membership of a record cylinder reads the pointer only. -/
lemma mem_arenaRecord_iff (y : PointerArena N N) (j : Fin N) :
    y ∈ arenaRecord N j ↔ y.2 ∈ recordRegion j := by
  constructor
  · rintro ⟨-, h⟩; exact h
  · intro h; exact ⟨Set.mem_univ _, h⟩

omit [NeZero N] in
/-- ★★ **The record preimages coincide — as sets.** Horizontal back-reaction is invisible
to the record regions because they are cylinders over the pointer, and the pointer
component is unchanged by hypothesis. Every sector-measure statement follows from this
without any measure theory. -/
theorem outcomeSector_eq (h : IsJointLift c ε Φ) (j : Fin N) :
    Φ ⁻¹' arenaRecord N j = pointerEvolve c ε ⁻¹' arenaRecord N j := by
  ext y
  simp only [Set.mem_preimage]
  rw [mem_arenaRecord_iff, mem_arenaRecord_iff, h.pointer_eq y]

omit [NeZero N] in
/-- **The weight field is a constant of motion.** This is precisely what the Poisson
argument `{wᵢ,wⱼ} = 0` delivers, and it is what makes repeating the stroke coherent: the
second stroke sees the same weights as the first. -/
theorem weights_conserved (h : IsJointLift c ε Φ) (y : PointerArena N N) :
    pointerWeights c ε (Φ y).1 = pointerWeights c ε y.1 := by
  have hrate : c.rate (Φ y).1.1 = c.rate y.1.1 := funext (h.rate_conserved y)
  funext j
  show smoothArcWeight ε (c.rate (Φ y).1.1 j) (cellMid (c.rate (Φ y).1.1) j) (Φ y).1.2.1
    = smoothArcWeight ε (c.rate y.1.1 j) (cellMid (c.rate y.1.1) j) y.1.2.1
  rw [hrate, h.register_conserved y]

omit [NeZero N] in
/-- ★ **The honest replacement for the no-collapse theorem.** The fibrewise witness leaves
the whole sector marginal untouched (`pointerEvolve_base_marginal_unchanged`); a genuine
lift does not, because the base point moves inside its moment fibre. What survives is that
the **moment-and-register** data — everything the measurement actually reads — is
unchanged. Any joint-flow prose should claim this and not the stronger statement. -/
theorem moment_marginal_unchanged (h : IsJointLift c ε Φ) :
    (fun y : PointerArena N N => (c.rate (Φ y).1.1, (Φ y).1.2.1))
      = fun y : PointerArena N N => (c.rate y.1.1, y.1.2.1) := by
  funext y
  rw [funext (h.rate_conserved y), h.register_conserved y]

/-- ★ **Landing transfers.** A ready pointer over the `ε`-shrunk cell of outcome `j` lands
in `j`'s record region under **any** joint lift — back-reaction included. -/
theorem landing (h : IsJointLift c ε Φ) {δ : ℝ} (hε : 0 < ε) (hδ : δ ≤ 1 / 2)
    {y : PointerArena N N} {j : Fin N}
    (hsec : y.1 ∈ shrunkCell c ε j) (hready : y.2 ∈ readyRegion δ) :
    Φ y ∈ arenaRecord N j := by
  rw [mem_arenaRecord_iff, h.pointer_eq y, ← mem_arenaRecord_iff]
  exact pointer_landing c hε hδ hsec hready

omit [NeZero N] in
/-- The fibrewise witness's outcome sector, in record-preimage form. -/
lemma protocol_outcomeSector_eq (c : ContextField N)
    (hc : ∀ j, Continuous fun p => c.rate p j) {ε δ : ℝ} (hδ : δ ≤ 1 / 2) (j : Fin N) :
    (pointerProtocol c hc ε hδ).outcomeSector j
      = pointerEvolve c ε ⁻¹' arenaRecord N j := by
  show (pointerProtocol c hc ε hδ).evolve 0 1 ⁻¹' arenaRecord N j = _
  rw [pointerProtocol_evolve_stroke c hc ε hδ]

/-- ★ **The lower Born bound transfers.** -/
theorem born_lower (h : IsJointLift c ε Φ) (hc : ∀ j, Continuous fun p => c.rate p j)
    {δ : ℝ} (hε : 0 < ε) (hδpos : 0 < δ) (hδ : δ ≤ 1 / 2)
    (p : LF4.CPN N) (q₀ : Pointer N) (j : Fin N) :
    ENNReal.ofReal (c.rate p j - 2 * ε)
      ≤ pointerPrep p q₀ δ (Φ ⁻¹' arenaRecord N j) := by
  rw [h.outcomeSector_eq j, ← protocol_outcomeSector_eq c hc hδ j]
  exact pointer_born_lower c hc hε hδpos hδ p q₀ j

/-- ★ **The upper Born bound transfers.** -/
theorem born_upper (h : IsJointLift c ε Φ) (hc : ∀ j, Continuous fun p => c.rate p j)
    {δ : ℝ} (hε : 0 < ε) (hδpos : 0 < δ) (hδ : δ ≤ 1 / 2)
    (p : LF4.CPN N) (q₀ : Pointer N) (i : Fin N) :
    pointerPrep p q₀ δ (Φ ⁻¹' arenaRecord N i)
      ≤ ENNReal.ofReal (c.rate p i + 2 * ((N : ℝ) - 1) * ε) := by
  rw [h.outcomeSector_eq i, ← protocol_outcomeSector_eq c hc hδ i]
  exact pointer_born_upper c hc hε hδpos hδ p q₀ i

end IsJointLift

/-- **The fibrewise witness is a joint lift** — with zero back-reaction. Non-vacuity: every
theorem above has at least this instance, so the hypotheses are satisfiable. -/
theorem isJointLift_pointerEvolve (c : ContextField N) (ε : ℝ) :
    IsJointLift c ε (pointerEvolve c ε) where
  pointer_eq _ := rfl
  rate_conserved _ _ := rfl
  register_conserved _ := rfl

/-! ### ★★ The transfer, bundled -/

/-- **Back-reaction is harmless**: for any joint lift of the measurement stroke, landing and
the full `ε`-Born sandwich hold exactly as they do for the frozen-base witness, and the
weight field and moment-register data are constants of motion. The conditional half of the
joint-arena Hamiltonian route (`BACKLOG.md` A1); the paper supplies the hypotheses. -/
structure JointFlowTransfer (c : ContextField N) (ε δ : ℝ)
    (Φ : PointerArena N N → PointerArena N N) : Prop where
  /-- The weights are constants of motion. -/
  weights_conserved : ∀ y, pointerWeights c ε (Φ y).1 = pointerWeights c ε y.1
  /-- The measurement-relevant data is unchanged (the no-collapse replacement). -/
  moment_marginal_unchanged :
    (fun y : PointerArena N N => (c.rate (Φ y).1.1, (Φ y).1.2.1))
      = fun y : PointerArena N N => (c.rate y.1.1, y.1.2.1)
  /-- Records are created, back-reaction notwithstanding. -/
  landing : ∀ {y : PointerArena N N} {j : Fin N},
    y.1 ∈ shrunkCell c ε j → y.2 ∈ readyRegion δ → Φ y ∈ arenaRecord N j
  /-- The `ε`-Born sandwich, lower half. -/
  born_lower : ∀ (p : LF4.CPN N) (q₀ : Pointer N) (j : Fin N),
    ENNReal.ofReal (c.rate p j - 2 * ε) ≤ pointerPrep p q₀ δ (Φ ⁻¹' arenaRecord N j)
  /-- The `ε`-Born sandwich, upper half. -/
  born_upper : ∀ (p : LF4.CPN N) (q₀ : Pointer N) (i : Fin N),
    pointerPrep p q₀ δ (Φ ⁻¹' arenaRecord N i)
      ≤ ENNReal.ofReal (c.rate p i + 2 * ((N : ℝ) - 1) * ε)

/-- ★★ **The transfer theorem.** Every joint lift enjoys the whole package. -/
theorem jointFlowTransfer {c : ContextField N} {ε : ℝ}
    {Φ : PointerArena N N → PointerArena N N} (h : IsJointLift c ε Φ)
    (hc : ∀ j, Continuous fun p => c.rate p j) {δ : ℝ} (hε : 0 < ε) (hδpos : 0 < δ)
    (hδ : δ ≤ 1 / 2) : JointFlowTransfer c ε δ Φ where
  weights_conserved := h.weights_conserved
  moment_marginal_unchanged := h.moment_marginal_unchanged
  landing hsec hready := h.landing hε hδ hsec hready
  born_lower := h.born_lower hc hε hδpos hδ
  born_upper := h.born_upper hc hε hδpos hδ

end CSD.RecordLayer
