/-
Copyright (c) 2026 Zayn Blore. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zayn Blore
-/
module

public import CsdLean4.SigmaLayer.UnifiedArena
public import CsdLean4.SigmaLayer.RotatedSwap
public import CsdLean4.SigmaLayer.JoinLuders
public import CsdLean4.SigmaLayer.PointerBorn

/-!
# SigmaLayer/MeasurementCapstone: one theorem for projective measurement dynamics

**Category:** capstone — the second external review's step 4, and the consolidation the
closure count was asking for.

## Why another capstone — and why this is the last one for this layer

The corpus grew tranche by tranche, and each tranche earned its own closure so its claims
were citable the day they landed: `unifiedArenaClosure` (rank-one, one arena),
`RotatedSwapClosure`/`measurement_covariance` (every apparatus basis),
`joinWitness_blockLuders` (degenerate Lüders on the projective join), and
`smoothWitnessClosure` (the smooth-Hamiltonian horn). Four closures is the *symptom* of that
history, not a design. This module is the *cure*: **one Prop bundling all four**, so that
"CSD reconstructs projective measurement dynamically" is henceforth a single citation —
`projectiveMeasurementCapstone` — rather than a conjunction scattered over four modules. The
constituent closures remain in place as the construction record and for pin stability; new
prose should cite this one.

## What the capstone asserts, per field

For every dimension, Hermitian generator, base point, and unit preparation:

* `rank_one` — one arena carries isolated Schrödinger dynamics **and** the complete
  rank-one measurement reconstruction (records created/exclusive/persistent, dynamical
  Born, rank-one Lüders, i.i.d. frequencies, mixed states), one Liouville measure family.
* `every_basis` — the full six-fact measurement closure holds for **every** orthonormal
  apparatus basis and every preparation: the computational basis is a parameter, not
  preferred structure of `Σ`.
* `degenerate` — for **every** block structure and block-supported calibration family, the
  ψ-dependent degenerate Lüders update is delivered by Liouville-preserving dynamics
  (`BlockLudersObligation`, inhabited by the join witness — the demand
  `swap_not_blockLuders` proved impossible for fixed ray-level calibrations).
* `smooth` — the smooth horn exists at every `ε`: a witness that is jointly continuous in
  time and state, Schrödinger-generated by an explicit Hermitian family, with a
  positive-measure ready state and the `ε`-Born sandwich (`SmoothWitnessClosure` on the
  canonical moment-map context).

⚠️ **Honest scope.** The four fields quantify over *different witnesses* — that is the
two-horn framing (author decision 2026-08-03, `docs/TOUR.md` §"Which horn is the right
one?"), not an accident: exact records and smooth generation are jointly impossible
(`no_everywhere_correlation`), so the capstone asserts each horn where it lives. POVM /
instrument dynamics and mixed *preparations* remain recorded extensions (`BACKLOG.md`); the
`smooth` field is stated as `Nonempty` because `SmoothWitnessClosure` carries data (its
protocol), keeping this capstone a `Prop`.

## References

`specs/BACKLOG.md` (the capstone row — this discharges it); second external review
2026-08-02 (step 4); `specs/reconstruction-status.md` §2a. Constituents:
`SigmaLayer/UnifiedArena.lean`, `RotatedSwap.lean`, `JoinLuders.lean`, `PointerBorn.lean`.
-/

@[expose] public section

namespace CSD.RecordLayer

open MeasureTheory

variable {M : ℕ} (H : Matrix (Fin (M + 1)) (Fin (M + 1)) ℂ) (hH : H.IsHermitian)
  (p₀ : LF4.CPN (M + 1)) (ψ : EuclideanSpace ℂ (Fin (M + 1))) (hψ0 : ψ ≠ 0)

/-- ★★★ **The projective-measurement capstone**: rank-one on one arena, every apparatus
basis, degenerate blocks, and the smooth horn — the corpus's four measurement closures as
one `Prop`. -/
structure ProjectiveMeasurementCapstone : Prop where
  /-- One arena: isolated Schrödinger dynamics + the complete rank-one reconstruction. -/
  rank_one : UnifiedArenaClosure H hH p₀ ψ hψ0
  /-- Every orthonormal apparatus basis, every preparation: the six-fact closure. -/
  every_basis : ∀ (bON : OrthonormalBasis (Fin (M + 1)) ℂ (EuclideanSpace ℂ (Fin (M + 1))))
    (φ : EuclideanSpace ℂ (Fin (M + 1))), RotatedSwapClosure bON φ
  /-- Every block structure: ψ-dependent degenerate Lüders through Liouville-preserving
  dynamics, from a fixed block-supported calibration family. -/
  degenerate : ∀ {K : ℕ} (b : Fin (M + 1) → Fin K)
    (α : Fin K → EuclideanSpace ℂ (Fin (M + 1))),
    (∀ i, blockProj b i (α i) = α i) → BlockLudersObligation b (joinPostMarg b α)
  /-- The smooth horn, at every `ε`: jointly continuous, Schrödinger-generated record
  dynamics with the `ε`-Born sandwich, on the canonical moment-map context. -/
  smooth : ∀ {ε δ : ℝ}, 0 < ε → 0 < δ → δ ≤ 1 / 2 →
    Nonempty (SmoothWitnessClosure (momentContext (M + 1)) ε δ)

/-- ★★★ **The capstone holds** — for every Hermitian generator, base point, and unit
preparation. One citation for the dynamical reconstruction of projective measurement. -/
theorem projectiveMeasurementCapstone (hψ : ‖ψ‖ = 1) :
    ProjectiveMeasurementCapstone H hH p₀ ψ hψ0 where
  rank_one := unifiedArenaClosure H hH p₀ ψ hψ0 hψ
  every_basis := measurement_covariance
  degenerate := fun b α hα => joinWitness_blockLuders (b := b) α hα
  smooth := fun hε hδpos hδ => ⟨smoothWitnessClosureCanonical hε hδpos hδ⟩

end CSD.RecordLayer
