import CsdLean4.SigmaLayer.ChoiceASector
import CsdLean4.LF4.ProjectedDynamics

/-!
# FND/TheoremTargets: the quantum reconstruction targets as uninhabited predicates

**Category:** 7-SigmaLayer (the Choice A ontological layer).

The quantum content of the reconstruction (Born rule, unitary and Schrödinger dynamics, ergodic
frequency convergence, Lüders update, no-signalling, Bell) is represented as well-typed `Prop`
predicates, NOT as axioms and NOT as structure fields. A target predicate is not a postulate: it is a
statement whose inhabitants are theorems to be proved for concrete models. This module defines the
targets whose types are supported by the current FND core; the measurement- and composition-dependent
targets (Lüders update, no-signalling, contextuality, Bell) are defined in their own modules once the
`DeisolationModel` and `CompositeSector` types exist.

**We deliberately provide no inhabitants of these predicates here.** Concrete proofs live with the
concrete models (see `FND/LiftedMeasurement.lean` and `FND/ForwardCapstone.lean`, and the existing
LF4/LF5/LF6 theorems they connect to).
-/

open MeasureTheory
open scoped BigOperators LinearAlgebra.Projectivization

namespace CSD.SigmaLayer

universe u

variable {N : ℕ} {Sigma : Type u} [MeasurableSpace Sigma]

/-- **T1: Born from volume.** The projective preparation law assigns each outcome region its Born
weight. Generic over the region/weight family; instantiated against the LF4 Born regions and weights in
concrete models. -/
def BornFromVolume [Nonempty Sigma] {D : ConstraintDynamics Sigma} (Q : ChoiceASector N D)
    (P : Preparation D) {ι : Type*} (region : ι → Set (ProjectiveState N)) (weight : ι → ENNReal) :
    Prop :=
  ∀ i, Q.projectivePreparationLaw P (region i) = weight i

/-- **T3: Born from deterministic flow.** For almost every initial ontic state (with respect to `muL`),
the time average along the flow trajectory of the outcome-region indicator converges to the region's
measure. The ergodic route to Born frequencies for a single deterministic trajectory. -/
def BornFromFlow (D : ConstraintDynamics Sigma) (region : Set Sigma) (value : ENNReal) : Prop :=
  ∀ᵐ x ∂(D.muL : Measure Sigma),
    Filter.Tendsto
      (fun n : ℕ =>
        (∑ k ∈ Finset.range n, Set.indicator region (fun _ => (1 : ℝ)) (D.flow (k : ℝ) x)) / n)
      Filter.atTop (nhds value.toReal)

/-- **B7 (ergodic branch): the flow is ergodic on the outcome regions.** Every measurable set invariant
under the time-1 flow map, among the relevant sigma-algebra, is null or co-null under `muL`. Defined,
not assumed; `BornFromFlow` is proved from this together with a Birkhoff hypothesis in concrete models. -/
def IsErgodicForOutcomeRegions (D : ConstraintDynamics Sigma) : Prop :=
  ∀ A : Set Sigma, MeasurableSet A → D.flow 1 ⁻¹' A = A →
    (D.muL : Measure Sigma) A = 0 ∨ (D.muL : Measure Sigma) Aᶜ = 0

/-- **T4: the projected flow has a unitary realisation.** There is a one-parameter family of unitary
matrices whose projective action equals the projected flow at every time. -/
def HasUnitaryRealisation (projectedFlow : OnticTime → ProjectiveState N → ProjectiveState N) : Prop :=
  ∃ U : OnticTime → Matrix.unitaryGroup (Fin N) ℂ, ∀ t p, projectedFlow t p = U t • p

/-- **T5: Hamiltonian (Schrödinger) realisation.** The unitary family is generated by a Hermitian
operator, `U t = exp(-i t H)` (reusing the existing `schrodingerUnitary`). -/
def HasHamiltonianRealisation
    (projectedFlow : OnticTime → ProjectiveState N → ProjectiveState N) : Prop :=
  ∃ (H : Matrix (Fin N) (Fin N) ℂ) (hH : H.IsHermitian),
    ∀ t p, projectedFlow t p = CSD.LF4.schrodingerUnitary hH t • p

/-- **B1: the ontic measure pushes forward to a target projective measure.** Named bridge assumption:
`pi_* muL = targetMeasure`. Proved for concrete product models (see `FND/MeasureBridge.lean`). -/
def HasProjectivePushforward {D : ConstraintDynamics Sigma} (Q : ChoiceASector N D)
    (targetMeasure : Measure (ProjectiveState N)) : Prop :=
  Measure.map Q.pi (D.muL : Measure Sigma) = targetMeasure

end CSD.SigmaLayer
