/-
Copyright (c) 2026 Zayn Blore. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zayn Blore
-/
module

public import CsdLean4.RecordLayer.BornFibrePartition

/-!
# SigmaLayer/DeIsolationFlow: the de-isolation outcome distribution (MD-1, step 2b′)

**Category:** 7-SigmaLayer (the record layer — the de-isolation flow's outcome distribution).

This is the **outcome-distribution** layer of the record layer (MD-1), built on the fibre partition
of `BornFibrePartition.lean`. Where that file gives the *per-cell* fibre measures, this file gives the
**outcome distribution** carried by the canonical **fibre typicality measure** `fibreTypicality`
(Lebesgue measure restricted to the unit fibre `[0,1)`, a probability measure), and the abstract
**de-isolation flow ⟹ Born** bridge.

The picture (plan `specs/record-layer-plan.md` §3c): a measurement is a *de-isolation flow* `Φ_M` on
the fibred `Σ`; its **pointer** `p = readout ∘ Φ_M : F → Fin n` sends a fibre point to the outcome
whose basin it lands in, and Born is the **fibre-typicality volume of the basin** — a *typicality*
volume of a flow-carved basin, not injected noise.

What is proved here, foundational-triple, no `sorry`:
* `fibreTypicality` is a probability measure (`instIsProbabilityMeasure`, `fibreTypicality_Ico01`).
* **Outcome probability = Born weight:** for a unit state the fibre typicality of the Born cell `i`
  is exactly `‖ψ i‖²` (`fibreTypicality_bornCell`) — the outcome probability of `i`.
* **The pointer is a.e. defined:** the Born cells cover the fibre up to a null set
  (`fibreTypicality_uncovered`) — the outcome is determined `fibreTypicality`-almost everywhere.
* **De-isolation flow ⟹ Born (`map_pointer_apply`):** *any* measurable pointer `p` whose basins
  carry the Born cell measures pushes `fibreTypicality` forward to the Born distribution — outcome
  `i` has probability `‖ψ i‖²`. This is the flow-*independent* content.

**The open research obligation (the wall, plan §3c / staging step 2b′):** exhibit a pointer `p`
*generated by a physical de-isolation Hamiltonian* `H_int(M)` — `p = readout ∘ (flow of H_int(M))` —
whose basins are `cdfCell (moment map)`. This file proves the Born *conclusion* from the basin
measures; it does **not** derive the basins from a Hamiltonian. `map_pointer_apply` makes the
remaining obligation precise: supply a measurable `p` with `fibreTypicality (p⁻¹{i}) = ‖ψ i‖²`.

## References
`specs/record-layer-plan.md` §3c (the de-isolation flow / first-passage race; step 2b′);
`SigmaLayer/BornFibrePartition.lean` (the fibre partition — `cdfCell`, `bornRate`, `volume_bornCell`,
`volume_iUnion_bornCell_unit`); `LF4/MomentMap.lean` (`momentMap_mk_eq_inner_sq`, the rates).
-/

@[expose] public section

open MeasureTheory Set

namespace CSD.RecordLayer

variable {n : ℕ}

/-- The **fibre typicality measure**: Lebesgue measure restricted to the unit fibre `[0,1)`. This is
the canonical typicality measure the de-isolation flow acts on; the outcome probabilities are the
fibre-typicality volumes of the basins. -/
noncomputable def fibreTypicality : Measure ℝ := volume.restrict (Ico (0 : ℝ) 1)

theorem fibreTypicality_Ico01 : fibreTypicality (Ico (0 : ℝ) 1) = 1 := by
  rw [fibreTypicality, Measure.restrict_apply measurableSet_Ico, inter_self, Real.volume_Ico]
  norm_num

instance instIsProbabilityMeasure : IsProbabilityMeasure fibreTypicality :=
  ⟨by
    show (volume.restrict (Ico (0 : ℝ) 1)) Set.univ = 1
    rw [Measure.restrict_apply_univ, Real.volume_Ico]; norm_num⟩

/-- The CDF cell for outcome `i` sits inside `[0, ∑ⱼ rⱼ)` (given `r ≥ 0`): the cumulative offset is
nonnegative and the cell ends at a partial sum `≤` the total. -/
theorem cdfCell_subset_Ico (r : Fin n → ℝ) (hr : ∀ i, 0 ≤ r i) (i : Fin n) :
    cdfCell r i ⊆ Ico 0 (∑ j, r j) := by
  rw [cdfCell]
  refine Set.Ico_subset_Ico (Finset.sum_nonneg fun j _ => hr j) ?_
  have hnotmem : i ∉ Finset.univ.filter (fun k : Fin n => (k : ℕ) < (i : ℕ)) := by simp
  calc loSum r i + r i
      = ∑ k ∈ insert i (Finset.univ.filter (fun k : Fin n => (k : ℕ) < (i : ℕ))), r k := by
        rw [Finset.sum_insert hnotmem, loSum]; ring
    _ ≤ ∑ j, r j := Finset.sum_le_sum_of_subset_of_nonneg (Finset.subset_univ _) (fun k _ _ => hr k)

/-- For a *unit* state the Born cells lie inside the unit fibre `[0,1)`. -/
theorem bornCell_subset_Ico01 (ψ : EuclideanSpace ℂ (Fin n)) (hψ : ‖ψ‖ = 1) (i : Fin n) :
    cdfCell (bornRate ψ) i ⊆ Ico (0 : ℝ) 1 := by
  have h := cdfCell_subset_Ico (bornRate ψ) (bornRate_nonneg ψ) i
  rwa [sum_bornRate_unit ψ hψ] at h

theorem iUnion_bornCell_subset_Ico01 (ψ : EuclideanSpace ℂ (Fin n)) (hψ : ‖ψ‖ = 1) :
    (⋃ i, cdfCell (bornRate ψ) i) ⊆ Ico (0 : ℝ) 1 :=
  Set.iUnion_subset fun i => bornCell_subset_Ico01 ψ hψ i

/-- **Outcome probability = Born weight.** For a unit state the fibre typicality of the Born cell `i`
is exactly `‖ψ i‖² = |⟨eᵢ, ψ⟩|²` — the de-isolation outcome `i` occurs with the Born probability. -/
theorem fibreTypicality_bornCell (ψ : EuclideanSpace ℂ (Fin n)) (hψ : ‖ψ‖ = 1) (i : Fin n) :
    fibreTypicality (cdfCell (bornRate ψ) i) = ENNReal.ofReal (‖ψ i‖ ^ 2) := by
  rw [fibreTypicality, Measure.restrict_apply (measurableSet_cdfCell _ i),
    inter_eq_left.mpr (bornCell_subset_Ico01 ψ hψ i), volume_bornCell]

/-- The Born cells cover the unit fibre up to fibre-typicality `1`. -/
theorem fibreTypicality_iUnion_bornCell (ψ : EuclideanSpace ℂ (Fin n)) (hψ : ‖ψ‖ = 1) :
    fibreTypicality (⋃ i, cdfCell (bornRate ψ) i) = 1 := by
  rw [fibreTypicality, Measure.restrict_apply (MeasurableSet.iUnion (measurableSet_cdfCell _)),
    inter_eq_left.mpr (iUnion_bornCell_subset_Ico01 ψ hψ), volume_iUnion_bornCell_unit ψ hψ]

/-- **The de-isolation pointer is defined almost everywhere.** For a unit state the Born cells cover
the fibre `[0,1)` up to a `fibreTypicality`-null set: the outcome is determined a.e., there is no
positive-typicality set on which no outcome is recorded. -/
theorem fibreTypicality_uncovered (ψ : EuclideanSpace ℂ (Fin n)) (hψ : ‖ψ‖ = 1) :
    fibreTypicality (Ico (0 : ℝ) 1 \ ⋃ i, cdfCell (bornRate ψ) i) = 0 := by
  have hmeasU : MeasurableSet (⋃ i, cdfCell (bornRate ψ) i) :=
    MeasurableSet.iUnion (measurableSet_cdfCell _)
  have hU : fibreTypicality (⋃ i, cdfCell (bornRate ψ) i) = 1 :=
    fibreTypicality_iUnion_bornCell ψ hψ
  rw [measure_sdiff (iUnion_bornCell_subset_Ico01 ψ hψ) hmeasU.nullMeasurableSet
      (by rw [hU]; exact ENNReal.one_ne_top), hU, fibreTypicality_Ico01, tsub_self]

/-- **The `[0,1)` in `fibreTypicality_uncovered` is not forced**: the same statement holds on
`univ`.

This corrects a reason that several record-layer modules gave for the restriction — that "Lebesgue
measure on the line is infinite". `fibreTypicality` is *not* Lebesgue measure on the line: it is
`volume.restrict (Ico 0 1)`, a **probability** measure (`instIsProbabilityMeasure`, proved directly
above), so nothing about infinite mass obstructs the `univ` form.

⚠️ But this theorem is weaker than it looks, and that is the real difference from the compact fibre.
It holds because `fibreTypicality` **assigns measure zero to everything outside `[0,1)`**
(`fibreTypicality_Ici_one`): points off the unit fibre are *excused by the measure*, not covered by
cells. On `CircleFibre` the total mass one is Haar mass on a compact group rather than a restriction
imposed by hand, so there is nowhere for an uncovered point to hide. See
`RecordLayer.circleBornMeasurement_ae_total`. -/
theorem fibreTypicality_uncovered_univ (ψ : EuclideanSpace ℂ (Fin n)) (hψ : ‖ψ‖ = 1) :
    fibreTypicality (univ \ ⋃ i, cdfCell (bornRate ψ) i) = 0 := by
  have hmeasU : MeasurableSet (⋃ i, cdfCell (bornRate ψ) i) :=
    MeasurableSet.iUnion (measurableSet_cdfCell _)
  have h := fibreTypicality_uncovered ψ hψ
  rw [fibreTypicality, Measure.restrict_apply (measurableSet_Ico.diff hmeasU),
    inter_eq_left.mpr sdiff_subset] at h
  rw [fibreTypicality, Measure.restrict_apply (MeasurableSet.univ.diff hmeasU)]
  have hset : (univ \ ⋃ i, cdfCell (bornRate ψ) i) ∩ Ico (0 : ℝ) 1
      = Ico (0 : ℝ) 1 \ ⋃ i, cdfCell (bornRate ψ) i := by
    ext x
    constructor
    · rintro ⟨⟨-, hx⟩, hI⟩; exact ⟨hI, hx⟩
    · rintro ⟨hI, hx⟩; exact ⟨⟨mem_univ x, hx⟩, hI⟩
  rw [hset]
  exact h

/-- **Why the `univ` form above is cheap on `ℝ`.** The unit fibre's complement carries infinite
Lebesgue measure but zero *typicality*: `fibreTypicality` excuses it by fiat. This is the honest
statement of what compactifying the fibre buys, and it is a fact about the restriction, not about
Lebesgue measure being infinite. -/
theorem fibreTypicality_Ici_one : fibreTypicality (Ici (1 : ℝ)) = 0 := by
  rw [fibreTypicality, Measure.restrict_apply measurableSet_Ici]
  have hempty : Ici (1 : ℝ) ∩ Ico 0 1 = ∅ := by
    ext x
    constructor
    · rintro ⟨h1, -, h2⟩; exact absurd h2 (not_lt.mpr h1)
    · exact fun h => h.elim
  rw [hempty, measure_empty]

/-- **De-isolation flow ⟹ Born.** *Any* measurable pointer `p` on the fibre whose basin `p⁻¹{i}` has
the Born cell measure pushes the fibre typicality forward to the Born distribution: the outcome-`i`
mass of `fibreTypicality.map p` is exactly `‖ψ i‖² = |⟨eᵢ, ψ⟩|²`.

This is the **flow-independent** content of step 2b′: given a de-isolation flow whose basins are the
moment-map/Born cells, the outcome distribution is Born. The open research obligation (plan §3c) is
to *exhibit* such a `p` generated by a physical de-isolation Hamiltonian `H_int(M)`; that derivation
is not part of this theorem, whose hypothesis `hbasin` is exactly the obligation. -/
theorem map_pointer_apply {p : ℝ → Fin n} (hp : Measurable p)
    (ψ : EuclideanSpace ℂ (Fin n)) (i : Fin n)
    (hbasin : fibreTypicality (p ⁻¹' {i}) = ENNReal.ofReal (‖ψ i‖ ^ 2)) :
    (fibreTypicality.map p) {i} = ENNReal.ofReal (‖ψ i‖ ^ 2) := by
  rw [Measure.map_apply hp (measurableSet_singleton i), hbasin]

end CSD.RecordLayer
