/-
Copyright (c) 2026 Zayn Blore. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zayn Blore
-/
module

public import CsdLean4.RecordLayer.ApproxProjectability
public import CsdLean4.SigmaLayer.MeasureBridge
public import CsdLean4.Mathlib.LinearAlgebra.Projectivization.TransitionProbability

/-!
# SigmaLayer/HamiltonianSignature: A2's formalisable half

**Category:** 7-SigmaLayer (Paper C A2 — Hamiltonian ontic dynamics).

## The split, stated up front

A2 as written — the ontic flow is generated by a Hamiltonian vector field `X_H = ω⁻¹dH` — needs the
symplectic form and the exterior derivative, which is the §2a-scoped manifold gap (verified a
tooling gap, not a falsity: the statement is standard Kähler geometry). What a measure space *can*
express is the **signature** a Hamiltonian flow leaves behind, and this module proves the witness
flow has every piece of it:

1. **A canonical conserved energy.** `onticEnergy H` — the expectation `re⟨ψ_p, H ψ_p⟩/‖ψ_p‖²` at
   the base point — is well-defined on rays and **conserved by the witness flow**
   (`onticEnergy_flow_invariant`): the flow conserves its own generator, the first Hamiltonian
   signature.
2. **The A5 junction.** `onticEnergy H` is fibre-independent by construction, so it is
   `EpsProjectable _ 0` — it *is* the canonical `h` of the exact case `H = h∘π`
   (`onticEnergy_epsProjectable`). A2's conserved energy and A5's projectable Hamiltonian are the
   same object, as they should be.
3. **The commuting phase torus.** The diagonal-phase unitaries form an additive (hence commuting)
   action that **preserves every moment-map coordinate** (`momentMap_phaseDiag_invariant`,
   `phaseDiag_add`) — the flow-level shadow of "the moment map generates the torus action". The
   fibre half of the torus signature is the translation flows of `ShearWitness.lean`
   (`pshift`, measure-preserving), already in place.

Together with the already-proved Liouville property (`ConstraintDynamics.flow_preserves`) and group
laws, the honest claim is: **every property of "Hamiltonian flow" expressible without the manifold
API is proved of the witness flow; the vector-field equation itself is scoped.** With this, A2's
unscoped content is discharged; what remains of A2 is exactly its §2a-scoped half.

## References

`RecordLayer/ApproxProjectability.lean` (`EpsProjectable` — the A5 junction);
`SigmaLayer/MeasureBridge.lean` (`productDynamics` — the witness flow);
`LF4/ProjectedDynamics.lean` (`schrodingerUnitary`, `schrodingerGen`);
`LF4/MomentMap.lean` (`momentMap`); `specs/reconstruction-status.md` §2a.
-/

@[expose] public section

open scoped LinearAlgebra.Projectivization
open NormedSpace Matrix

namespace CSD.RecordLayer

variable {N : ℕ}

/-! ### The canonical ontic energy -/

/-- The energy at a base point: the expectation of `H` in the ray's representative, normalised.
Well-defined on rays by `baseEnergy_mk`. -/
noncomputable def baseEnergy (H : Matrix (Fin N) (Fin N) ℂ) (p : LF4.CPN N) : ℝ :=
  RCLike.re (inner ℂ p.rep (Matrix.toEuclideanLin H p.rep)) / ‖p.rep‖ ^ 2

/-- **The canonical ontic energy** of a Hamiltonian: the base-point expectation, lifted to `Σ`.
Fibre-independent by construction — see `onticEnergy_epsProjectable`. -/
noncomputable def onticEnergy (H : Matrix (Fin N) (Fin N) ℂ) : LF4.KSigma N → ℝ :=
  fun x => baseEnergy H x.1

/-- The energy ratio is scale-invariant — the well-definedness computation. -/
theorem energyRatio_smul (H : Matrix (Fin N) (Fin N) ℂ) (c : ℂ) (hc : c ≠ 0)
    (v : EuclideanSpace ℂ (Fin N)) :
    RCLike.re (inner ℂ (c • v) (Matrix.toEuclideanLin H (c • v))) / ‖c • v‖ ^ 2
      = RCLike.re (inner ℂ v (Matrix.toEuclideanLin H v)) / ‖v‖ ^ 2 := by
  rw [map_smul, inner_smul_left, inner_smul_right, ← mul_assoc, Complex.conj_mul',
    norm_smul, mul_pow]
  rw [show ((‖c‖ : ℂ)) ^ 2 = ((‖c‖ ^ 2 : ℝ) : ℂ) by push_cast; ring,
    ← Complex.real_smul, RCLike.smul_re]
  have hc' : (‖c‖ : ℝ) ≠ 0 := norm_ne_zero_iff.mpr hc
  field_simp

/-- **The energy is well-defined on rays**: at `[ψ]` it is the normalised expectation in `ψ`. -/
theorem baseEnergy_mk (H : Matrix (Fin N) (Fin N) ℂ) (ψ : EuclideanSpace ℂ (Fin N)) (hψ : ψ ≠ 0) :
    baseEnergy H (Projectivization.mk ℂ ψ hψ)
      = RCLike.re (inner ℂ ψ (Matrix.toEuclideanLin H ψ)) / ‖ψ‖ ^ 2 := by
  obtain ⟨a, ha⟩ :=
    (Projectivization.mk_eq_mk_iff ℂ (Projectivization.mk ℂ ψ hψ).rep ψ
        (Projectivization.rep_nonzero _) hψ).mp (Projectivization.mk_rep _)
  unfold baseEnergy
  rw [← ha]
  simp only [Units.smul_def]
  exact energyRatio_smul H (↑a) (Units.ne_zero a) ψ

/-! ### Conservation under commuting unitaries, hence under the flow -/

/-- Adjoint move for the matrix action (general-`N` form of the corpus's
`inner_toEuclideanLin_adjoint`). -/
theorem inner_toEuclideanLin_adjoint' (W : Matrix (Fin N) (Fin N) ℂ)
    (x y : EuclideanSpace ℂ (Fin N)) :
    inner ℂ (Matrix.toEuclideanLin W x) y
      = inner ℂ x (Matrix.toEuclideanLin (star W) y) := by
  show WithLp.ofLp y ⬝ᵥ star (W *ᵥ WithLp.ofLp x)
      = (star W *ᵥ WithLp.ofLp y) ⬝ᵥ star (WithLp.ofLp x)
  rw [Matrix.star_mulVec, ← Matrix.star_eq_conjTranspose, dotProduct_comm (WithLp.ofLp y),
      ← dotProduct_mulVec, dotProduct_comm]

/-- Matrix multiplication composes through `toEuclideanLin`, pointwise. -/
theorem toEuclideanLin_mul_apply (A B : Matrix (Fin N) (Fin N) ℂ)
    (v : EuclideanSpace ℂ (Fin N)) :
    Matrix.toEuclideanLin A (Matrix.toEuclideanLin B v)
      = Matrix.toEuclideanLin (A * B) v := by
  show WithLp.toLp 2 (A *ᵥ (B *ᵥ WithLp.ofLp v)) = WithLp.toLp 2 ((A * B) *ᵥ WithLp.ofLp v)
  rw [Matrix.mulVec_mulVec]

/-- **Energy is invariant under any unitary commuting with `H`** — the algebraic core of
conservation. -/
theorem baseEnergy_smul_invariant (H : Matrix (Fin N) (Fin N) ℂ)
    (U : Matrix.unitaryGroup (Fin N) ℂ) (hcomm : (U : Matrix (Fin N) (Fin N) ℂ) * H = H * U)
    (p : LF4.CPN N) :
    baseEnergy H (U • p) = baseEnergy H p := by
  classical
  -- Work at a representative.
  have hrep : p = Projectivization.mk ℂ p.rep p.rep_nonzero := (Projectivization.mk_rep p).symm
  rw [hrep, Projectivization.smul_mk_eq_mk_toEuclideanLin U p.rep_nonzero,
    baseEnergy_mk, baseEnergy_mk]
  set v := p.rep with hv
  -- Numerator: `⟨Uv, H(Uv)⟩ = ⟨v, (U*HU) v⟩ = ⟨v, Hv⟩`.
  have hstar : star (U : Matrix (Fin N) (Fin N) ℂ) * (H * U)
      = H := by
    rw [← hcomm, ← mul_assoc, Unitary.coe_star_mul_self U, one_mul]
  have hnum : inner ℂ (Matrix.toEuclideanLin (U : Matrix (Fin N) (Fin N) ℂ) v)
      (Matrix.toEuclideanLin H (Matrix.toEuclideanLin (U : Matrix (Fin N) (Fin N) ℂ) v))
      = inner ℂ v (Matrix.toEuclideanLin H v) := by
    rw [toEuclideanLin_mul_apply, inner_toEuclideanLin_adjoint', toEuclideanLin_mul_apply,
      hstar]
  -- Denominator: unitaries preserve the norm.
  have hnorm : ‖Matrix.toEuclideanLin (U : Matrix (Fin N) (Fin N) ℂ) v‖ = ‖v‖ := by
    have h2 : inner ℂ (Matrix.toEuclideanLin (U : Matrix (Fin N) (Fin N) ℂ) v)
        (Matrix.toEuclideanLin (U : Matrix (Fin N) (Fin N) ℂ) v) = inner ℂ v v := by
      rw [inner_toEuclideanLin_adjoint', toEuclideanLin_mul_apply,
        Unitary.coe_star_mul_self U]
      simp
    have h3 : ‖Matrix.toEuclideanLin (U : Matrix (Fin N) (Fin N) ℂ) v‖ ^ 2 = ‖v‖ ^ 2 := by
      rw [← inner_self_eq_norm_sq (𝕜 := ℂ)
          (Matrix.toEuclideanLin (U : Matrix (Fin N) (Fin N) ℂ) v),
        ← inner_self_eq_norm_sq (𝕜 := ℂ) v, h2]
    have h4 := norm_nonneg (Matrix.toEuclideanLin (U : Matrix (Fin N) (Fin N) ℂ) v)
    have h5 := norm_nonneg v
    apply le_antisymm <;> nlinarith [h3, h4, h5]
  rw [hnum, hnorm]

/-- **★ The witness flow conserves its own generator** — the first Hamiltonian signature. The
Schrödinger unitary is `exp((-it)·H)`, which commutes with `H`, so `baseEnergy_smul_invariant`
applies at every time. -/
theorem onticEnergy_flow_invariant {M : ℕ} (H : Matrix (Fin (M + 1)) (Fin (M + 1)) ℂ)
    (hH : H.IsHermitian) (p₀ : LF4.CPN (M + 1)) (t : ℝ) (x : LF4.KSigma (M + 1)) :
    onticEnergy H ((CSD.SigmaLayer.productDynamics H hH p₀).flow t x) = onticEnergy H x := by
  show onticEnergy H (CSD.LF4.schrodingerUnitary hH t • x.1, x.2) = onticEnergy H x
  show baseEnergy H (CSD.LF4.schrodingerUnitary hH t • x.1) = baseEnergy H x.1
  refine baseEnergy_smul_invariant H _ ?_ x.1
  show NormedSpace.exp (CSD.LF4.schrodingerGen H t) * H
      = H * NormedSpace.exp (CSD.LF4.schrodingerGen H t)
  exact (((Commute.refl H).smul_left (-(t : ℂ) * Complex.I)).exp_left).eq

/-- **★ The A5 junction: the conserved energy is exactly projectable.** `onticEnergy H` depends on
the base point alone, so it is `EpsProjectable _ 0` — it *is* the canonical `h` of the exact case
`H = h∘π`. A2's conserved quantity and A5's projectable Hamiltonian are the same object. -/
theorem onticEnergy_epsProjectable (H : Matrix (Fin N) (Fin N) ℂ) :
    EpsProjectable (onticEnergy H) 0 :=
  (epsProjectable_zero_iff _).mpr ⟨baseEnergy H, rfl⟩

/-! ### The commuting phase torus -/

/-- The diagonal-phase unitary `diag(e^{iφ₀}, …, e^{iφ_{N-1}})`. -/
noncomputable def phaseDiag (φ : Fin N → ℝ) : Matrix.unitaryGroup (Fin N) ℂ :=
  ⟨Matrix.diagonal fun k => Complex.exp (Complex.I * φ k), by
    constructor
    · show star (Matrix.diagonal _) * Matrix.diagonal _ = 1
      rw [Matrix.star_eq_conjTranspose, Matrix.diagonal_conjTranspose,
        Matrix.diagonal_mul_diagonal]
      convert Matrix.diagonal_one using 2
      funext k
      rw [Pi.star_apply, Complex.star_def, ← Complex.exp_conj, ← Complex.exp_add,
        map_mul, Complex.conj_I, Complex.conj_ofReal,
        show -Complex.I * ((φ k : ℝ) : ℂ) + Complex.I * ((φ k : ℝ) : ℂ) = 0 by ring,
        Complex.exp_zero]
    · show Matrix.diagonal _ * star (Matrix.diagonal _) = 1
      rw [Matrix.star_eq_conjTranspose, Matrix.diagonal_conjTranspose,
        Matrix.diagonal_mul_diagonal]
      convert Matrix.diagonal_one using 2
      funext k
      rw [Pi.star_apply, Complex.star_def, ← Complex.exp_conj, ← Complex.exp_add,
        map_mul, Complex.conj_I, Complex.conj_ofReal,
        show Complex.I * ((φ k : ℝ) : ℂ) + -Complex.I * ((φ k : ℝ) : ℂ) = 0 by ring,
        Complex.exp_zero]⟩

/-- **The phase flows are additive, hence commute** — the abelian-torus half of the signature. -/
theorem phaseDiag_add (φ φ' : Fin N → ℝ) :
    phaseDiag (φ + φ') = phaseDiag φ * phaseDiag φ' := by
  apply Subtype.ext
  show Matrix.diagonal _ = Matrix.diagonal _ * Matrix.diagonal _
  rw [Matrix.diagonal_mul_diagonal]
  congr 1
  funext k
  rw [← Complex.exp_add, Pi.add_apply]
  push_cast
  ring_nf

theorem phaseDiag_comm (φ φ' : Fin N → ℝ) :
    phaseDiag φ * phaseDiag φ' = phaseDiag φ' * phaseDiag φ := by
  rw [← phaseDiag_add, ← phaseDiag_add, add_comm]

/-- **★ The phase torus preserves every moment-map coordinate** — the flow-level shadow of "the
moment map generates the torus action" (the generating statement itself needs the symplectic form
and is §2a-scoped). -/
theorem momentMap_phaseDiag_invariant (φ : Fin N → ℝ) (p : LF4.CPN N) (k : Fin N) :
    LF4.momentMap (phaseDiag φ • p) k = LF4.momentMap p k := by
  classical
  have hrep : p = Projectivization.mk ℂ p.rep p.rep_nonzero := (Projectivization.mk_rep p).symm
  rw [hrep, Projectivization.smul_mk_eq_mk_toEuclideanLin (phaseDiag φ) p.rep_nonzero,
    LF4.momentMap_mk, LF4.momentMap_mk]
  set v := p.rep with hv
  have happ : ∀ j, (Matrix.toEuclideanLin ((phaseDiag φ) : Matrix (Fin N) (Fin N) ℂ) v) j
      = Complex.exp (Complex.I * φ j) * v j := by
    intro j
    show (Matrix.diagonal _ *ᵥ WithLp.ofLp v) j = _
    rw [Matrix.mulVec_diagonal]
  have hnorm_coord : ∀ j,
      ‖(Matrix.toEuclideanLin ((phaseDiag φ) : Matrix (Fin N) (Fin N) ℂ) v) j‖ = ‖v j‖ := by
    intro j
    rw [happ j, norm_mul, Complex.norm_exp]
    simp
  have hnorm : ‖Matrix.toEuclideanLin ((phaseDiag φ) : Matrix (Fin N) (Fin N) ℂ) v‖ = ‖v‖ := by
    rw [EuclideanSpace.norm_eq, EuclideanSpace.norm_eq]
    congr 1
    exact Finset.sum_congr rfl fun j _ => by rw [hnorm_coord j]
  rw [hnorm_coord k, hnorm]

end CSD.RecordLayer
