/-
Copyright (c) 2026 Zayn Blore. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zayn Blore
-/
module

public import Mathlib.RingTheory.MatrixAlgebra
public import Mathlib.LinearAlgebra.Matrix.Kronecker
public import Mathlib.LinearAlgebra.Matrix.StdBasis
public import Mathlib.Data.Matrix.Basis
public import Mathlib.RingTheory.TensorProduct.Basic

/-!
# Mathlib upstream candidate: the Kronecker factor embeddings as algebra homomorphisms

**Category:** 1-Mathlib (CSD-free).

Mathlib packages the Kronecker product as the algebra equivalence
`Matrix.kroneckerAlgEquiv m n R : (Matrix m m R ⊗[R] Matrix n n R) ≃ₐ[R] Matrix (m × n) (m × n) R`
but has no bundled form of the two **factor embeddings** `A ↦ A ⊗ₖ 1` and `B ↦ 1 ⊗ₖ B`. They are
the compositions of that equivalence with the tensor-factor inclusions
`Algebra.TensorProduct.includeLeft` / `includeRight`:

- `Matrix.kroneckerLeftAlgHom R m n : Matrix m m R →ₐ[R] Matrix (m × n) (m × n) R`, `A ↦ A ⊗ₖ 1`;
- `Matrix.kroneckerRightAlgHom R m n : Matrix n n R →ₐ[R] Matrix (m × n) (m × n) R`, `B ↦ 1 ⊗ₖ B`;

with the API a bipartite-system consumer needs: the images commute
(`commute_kroneckerLeftAlgHom_kroneckerRightAlgHom`), their products are the Kronecker products
(`kroneckerLeftAlgHom_mul_kroneckerRightAlgHom`), they preserve the conjugate transpose
(`kroneckerLeftAlgHom_conjTranspose`), and **they generate**: the subalgebra generated by the two
images is everything (`adjoin_range_kroneckerLeftAlgHom_union_eq_top`), because the matrix units
`single (i, j) (k, l) 1 = single i k 1 ⊗ₖ single j l 1` lie in it.

The generation step is factored through the matrix-unit criteria
`Submodule.eq_top_of_forall_single_mem` / `Subalgebra.eq_top_of_forall_single_mem` (a submodule or
subalgebra of a matrix algebra containing every matrix unit is everything — `Matrix.stdBasis`
spans), which are useful on their own.

## Namespace / staging

Declarations live in `namespace Matrix` (Mathlib's symbol namespace for the Kronecker product), so
upstreaming is a file move onto `Mathlib/RingTheory/MatrixAlgebra.lean` (where
`kroneckerAlgEquiv` lives), no symbol rename. Mathlib has none of these as of the pinned revision.
MATHLIB-ABSENT(Matrix.kroneckerLeftAlgHom) MATHLIB-ABSENT(Matrix.kroneckerRightAlgHom)

## Consumers

- `CsdLean4/CV/CompositeArena.lean` (`leftHom` / `rightHom`, `composite_generate`);
- `CsdLean4/SigmaLayer/TensorTomography.lean` (`aliceHom` / `bobHom`, `kronecker_adjoin_eq_top`).
-/

@[expose] public section

open scoped Kronecker TensorProduct

namespace Matrix

/-! ### Generation by matrix units -/

section StdBasis

variable {R : Type*} [Semiring R] {m n : Type*} [Fintype m] [Fintype n] [DecidableEq m]
  [DecidableEq n]

/-- A submodule of a matrix module containing every matrix unit `single i j 1` is everything. -/
theorem _root_.Submodule.eq_top_of_forall_single_mem {p : Submodule R (Matrix m n R)}
    (h : ∀ i j, Matrix.single i j (1 : R) ∈ p) : p = ⊤ := by
  rw [eq_top_iff, ← (Matrix.stdBasis R m n).span_eq, Submodule.span_le]
  rintro _ ⟨⟨i, j⟩, rfl⟩
  rw [Matrix.stdBasis_eq_single]
  exact h i j

end StdBasis

section StdBasisAlgebra

variable {R : Type*} [CommSemiring R] {n : Type*} [Fintype n] [DecidableEq n]

/-- A subalgebra of a matrix algebra containing every matrix unit `single i j 1` is everything. -/
theorem _root_.Subalgebra.eq_top_of_forall_single_mem {S : Subalgebra R (Matrix n n R)}
    (h : ∀ i j, Matrix.single i j (1 : R) ∈ S) : S = ⊤ := by
  rw [← Algebra.toSubmodule_eq_top]
  exact Submodule.eq_top_of_forall_single_mem h

end StdBasisAlgebra

/-! ### The factor embeddings -/

section KroneckerAlgHom

variable (R : Type*) [CommSemiring R] (m n : Type*) [Fintype m] [Fintype n] [DecidableEq m]
  [DecidableEq n]

/-- The left Kronecker factor embedding `A ↦ A ⊗ₖ 1` as an `R`-algebra homomorphism. -/
noncomputable def kroneckerLeftAlgHom : Matrix m m R →ₐ[R] Matrix (m × n) (m × n) R :=
  (kroneckerAlgEquiv m n R).toAlgHom.comp Algebra.TensorProduct.includeLeft

/-- The right Kronecker factor embedding `B ↦ 1 ⊗ₖ B` as an `R`-algebra homomorphism. -/
noncomputable def kroneckerRightAlgHom : Matrix n n R →ₐ[R] Matrix (m × n) (m × n) R :=
  (kroneckerAlgEquiv m n R).toAlgHom.comp Algebra.TensorProduct.includeRight

variable {R m n}

@[simp] theorem kroneckerLeftAlgHom_apply (A : Matrix m m R) :
    kroneckerLeftAlgHom R m n A = A ⊗ₖ (1 : Matrix n n R) := rfl

@[simp] theorem kroneckerRightAlgHom_apply (B : Matrix n n R) :
    kroneckerRightAlgHom R m n B = (1 : Matrix m m R) ⊗ₖ B := rfl

/-- The product of the two embeddings is the Kronecker product. -/
theorem kroneckerLeftAlgHom_mul_kroneckerRightAlgHom (A : Matrix m m R) (B : Matrix n n R) :
    kroneckerLeftAlgHom R m n A * kroneckerRightAlgHom R m n B = A ⊗ₖ B := by
  rw [kroneckerLeftAlgHom_apply, kroneckerRightAlgHom_apply, ← mul_kronecker_mul, mul_one,
    one_mul]

/-- The two factor embeddings commute. -/
theorem commute_kroneckerLeftAlgHom_kroneckerRightAlgHom (A : Matrix m m R) (B : Matrix n n R) :
    Commute (kroneckerLeftAlgHom R m n A) (kroneckerRightAlgHom R m n B) := by
  rw [Commute, SemiconjBy, kroneckerLeftAlgHom_mul_kroneckerRightAlgHom,
    kroneckerRightAlgHom_apply, kroneckerLeftAlgHom_apply, ← mul_kronecker_mul, mul_one, one_mul]

/-- The left embedding preserves the conjugate transpose. -/
theorem kroneckerLeftAlgHom_conjTranspose [StarRing R] (A : Matrix m m R) :
    kroneckerLeftAlgHom R m n Aᴴ = (kroneckerLeftAlgHom R m n A)ᴴ := by
  rw [kroneckerLeftAlgHom_apply, kroneckerLeftAlgHom_apply, conjTranspose_kronecker,
    conjTranspose_one]

/-- The right embedding preserves the conjugate transpose. -/
theorem kroneckerRightAlgHom_conjTranspose [StarRing R] (B : Matrix n n R) :
    kroneckerRightAlgHom R m n Bᴴ = (kroneckerRightAlgHom R m n B)ᴴ := by
  rw [kroneckerRightAlgHom_apply, kroneckerRightAlgHom_apply, conjTranspose_kronecker,
    conjTranspose_one]

/-- The left embedding preserves `star`. -/
theorem kroneckerLeftAlgHom_star [StarRing R] (A : Matrix m m R) :
    kroneckerLeftAlgHom R m n (star A) = star (kroneckerLeftAlgHom R m n A) :=
  kroneckerLeftAlgHom_conjTranspose A

/-- The right embedding preserves `star`. -/
theorem kroneckerRightAlgHom_star [StarRing R] (B : Matrix n n R) :
    kroneckerRightAlgHom R m n (star B) = star (kroneckerRightAlgHom R m n B) :=
  kroneckerRightAlgHom_conjTranspose B

/-- Every matrix unit of the product index is a product of embedded matrix units. -/
theorem single_eq_kroneckerLeftAlgHom_mul_kroneckerRightAlgHom (i k : m) (j l : n) :
    Matrix.single (i, j) (k, l) (1 : R)
      = kroneckerLeftAlgHom R m n (Matrix.single i k 1)
        * kroneckerRightAlgHom R m n (Matrix.single j l 1) := by
  rw [kroneckerLeftAlgHom_mul_kroneckerRightAlgHom, single_kronecker_single, mul_one]

/-- **The two factor embeddings generate the matrix algebra of the product index.** -/
theorem adjoin_range_kroneckerLeftAlgHom_union_eq_top :
    Algebra.adjoin R
      (Set.range (kroneckerLeftAlgHom R m n) ∪ Set.range (kroneckerRightAlgHom R m n)) = ⊤ := by
  refine Subalgebra.eq_top_of_forall_single_mem fun ⟨i, j⟩ ⟨k, l⟩ => ?_
  rw [single_eq_kroneckerLeftAlgHom_mul_kroneckerRightAlgHom]
  exact mul_mem (Algebra.subset_adjoin (Or.inl ⟨_, rfl⟩))
    (Algebra.subset_adjoin (Or.inr ⟨_, rfl⟩))

end KroneckerAlgHom

end Matrix
