/-
Copyright (c) 2026 Zayn Blore. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zayn Blore
-/
module

public import CsdLean4.LF4.SingletKahler
public import CsdLean4.LF4.KahlerFlow

/-!
# SL-2: a genuine `Φ ≠ id` on the concrete ENTANGLED (singlet) sector

**Category:** 3-Local (a genuine `Φ ≠ id` on the concrete ENTANGLED (singlet) sector).

D1c-1 (`LF4/KahlerFlow.lean`) discharged the "`Φ = id` in the concrete Kähler
instance" debt for the GENERIC sector: `kSectorDataFlow` carries the non-identity
measure-preserving flow `Φ = kFlow sh` (a free `T²`-fibre translation), and
`kFlow_frequency_convergence` makes its Liouville-preservation *load-bearing* (it
pins the law of the evolved trials `kFlow sh ∘ sample`).

This module does the same for the **entangled** sector — the two-qubit singlet on
`Σ = ℂℙ³ × T²` (`LF4/SingletKahler.lean`), SL-2. The singlet preparation
`ofKählerPreparation` was built over `kSectorData` (`Φ = id`); here it is rebuilt
over `kSectorDataFlow p₀ sh` (`Φ = kFlow sh ≠ id`), and the per-sector frequency
capstone fires with the trials genuinely **evolved by the sector's own flow**.

The mechanism is exact and requires no new engine. An LF1 `OutcomeRegion`'s scored
event is `preEvent = Φ ⁻¹' Ω` (`LF1/Outcomes.lean`), so with `Φ = kFlow sh` the
capstone scores `X ⁻¹' preEvent = (kFlow sh ∘ X) ⁻¹' kRegion` — each sampled
microstate is pushed one flow-step before its outcome block is read. Liouville
preservation is load-bearing through `bridge_op_p`: the carving identity now reads
`kMuPsi (kFlow sh ⁻¹' kRegion) = kMuPsi (kRegion) = P_st`, the first equality being
`kFlow_measurePreserving_muPsi` (the singlet analogue of `kFlow_measurePreserving`).
So the empirical frequency of the flow-evolved singlet trials still converges a.s.
to the Born weight `P_st`.

## Deliverables

* `kFlow_measurePreserving_muPsi` — `kFlow sh` preserves the singlet fibre law
  `μψ = δ_{[singlet]} ⊗ vol_{T²}` (fixes the base ray, translates the fibre);
* `ofKählerPreparationFlow` — the singlet `PureSingletPreparation` over the
  `Φ ≠ id` sector `kSectorDataFlow p₀ sh`;
* `ofKählerPreparationFlow_phi_ne_id` — its sector genuinely carries `Φ ≠ id`;
* `ofKählerPreparationFlow_flow_frequency_convergence` — the per-sector empirical
  frequencies of the trials **evolved by `kFlow sh`** converge a.s. to `P_st`.

## Honest scope (unchanged from D1c-1)

`kFlow` is a *free* fibre translation: a genuine measure-preserving `Φ ≠ id`, but
dynamically trivial (it is not a de-isolation / measurement flow, nor a
Hamiltonian flow generated by the Kähler form; it moves only within the fibre over
a fixed ray). So this is the **structural** discharge of "`Φ = id` in the concrete
*entangled* instance", making Liouville-preservation load-bearing on the singlet —
NOT a derivation of the sector. **A5 is untouched** (the entangled sector /
Fubini–Study typicality is still posited; that is SL-1). Foundational-triple-only
/ Gleason-free, inherited from `ofKählerPreparation` and the LF3 chain.
-/

@[expose] public section

open MeasureTheory Matrix Matrix.UnitaryGroup
open scoped LinearAlgebra.Projectivization
open CSD.LF3

namespace CSD
namespace LF4

variable (ctx : CSD.LF3.MeasurementContext)

/-! ### `kFlow` preserves the singlet fibre law `μψ` -/

/-- **The fibre flow preserves the singlet fibre law.** `kFlow sh` fixes the base
ray (so it preserves the Dirac `δ_{[singlet]}` on `ℂℙ³`) and translates the `T²`
fibre (so it preserves the Haar volume there). This is the singlet analogue of
`kFlow_measurePreserving`, and the genuine Liouville content that makes `Φ`
load-bearing in the frequency capstone below. -/
theorem kFlow_measurePreserving_muPsi (sh : KTorus) :
    MeasurePreserving (kFlow (N := 4) sh) kMuPsi kMuPsi := by
  have h1 : MeasurePreserving (fun x : AddCircle (1 : ℝ) => sh.1 + x)
      (volume : Measure (AddCircle (1 : ℝ))) (volume : Measure (AddCircle (1 : ℝ))) :=
    measurePreserving_add_left _ sh.1
  have h2 : MeasurePreserving (fun x : AddCircle (1 : ℝ) => sh.2 + x)
      (volume : Measure (AddCircle (1 : ℝ))) (volume : Measure (AddCircle (1 : ℝ))) :=
    measurePreserving_add_left _ sh.2
  have htransl : MeasurePreserving (fun t : KTorus => sh + t)
      (volume : Measure KTorus) (volume : Measure KTorus) := h1.prod h2
  exact (MeasurePreserving.id (Measure.dirac singletRay)).prod htransl

/-! ### The preparation bundle over the `Φ ≠ id` sector

Each component of `ofKählerPreparation` references the sector only through its
projection `π = Prod.fst` and Liouville measure `μL = kMuL p₀` — both DEFINITIONALLY
equal between `kSectorData` and `kSectorDataFlow` (they differ only in `Φ`). So the
bridge / preparation / outcome-region proofs port verbatim. -/

/-- The axiom-free measure bridge for the `Φ ≠ id` sector (`c = 1`, `π∗μL = μFS`
via `Measure.fst_prod`), identical to `kBridge` — the bridge does not see `Φ`. -/
noncomputable def kBridgeFlow (p₀ : CPN 4) (sh : KTorus) :
    LF2.MeasureBridgeData (kSectorDataFlow p₀ sh) (fubiniStudyMeasure p₀) where
  is_inv := fun U =>
    ⟨(continuous_const_smul U).measurable, fubiniStudyMeasure_smul_invariant U p₀⟩
  c := 1
  bridge_eq := by
    show Measure.map (kSectorDataFlow p₀ sh).π
        ((kSectorDataFlow p₀ sh).μL : Measure (KSigma 4)) = 1 • fubiniStudyMeasure p₀
    rw [one_smul]
    show Measure.map Prod.fst (kMuL p₀) = fubiniStudyMeasure p₀
    rw [kMuL, ← Measure.fst, Measure.fst_prod]

/-- The singlet `PurePreparation` over the `Φ ≠ id` sector (constant `rep`, Dirac
concentration through `π = Prod.fst`), identical to `kPurePrep`. -/
noncomputable def kPurePrepFlow (p₀ : CPN 4) (sh : KTorus) :
    LF2.PurePreparation (kSectorDataFlow p₀ sh) kMuPsi 4 where
  ψ := singletPsi
  unit_ψ := singletPsi_norm
  rep := kRep
  hrep_unit := kRep_unit
  hrep_meas := kRep_meas
  ray_point := singletRay
  rep_at_ray := rfl
  push_dirac := by
    show Measure.map (kSectorDataFlow p₀ sh).π kMuPsi = Measure.dirac singletRay
    exact kMuPsi_push

/-- The per-sector outcome region over the `Φ ≠ id` ontic setup: same carved set
`kRegion` as `kOutcomeRegion` (the region is base-flow-agnostic). Its scored event
is `preEvent = kFlow sh ⁻¹' kRegion` — the flow enters HERE. -/
noncomputable def kOutcomeRegionFlow (p₀ : CPN 4) (sh : KTorus) (s t : Sign) :
    (kOnticSetupFlow p₀ sh).OutcomeRegion where
  Ω := kRegion ctx s t
  hΩ_meas := kRegion_measurable ctx s t

/-- **SL-2: the singlet preparation on the `Φ ≠ id` sector.** The concrete
`LF3.PureSingletPreparation` for the two-qubit singlet over `kSectorDataFlow p₀ sh`
(`Φ = kFlow sh ≠ id`). Identical to `ofKählerPreparation` except the underlying
sector carries the genuine non-identity flow, so the scored event is
`preEvent = kFlow sh ⁻¹' kRegion`. `bridge_op_p` holds because
`kMuPsi (kFlow sh ⁻¹' kRegion) = kMuPsi (kRegion) = P_st` — the first equality is
`kFlow`'s Liouville-preservation (`kFlow_measurePreserving_muPsi`), now
load-bearing; the second is the carving identity `kMuPsi_kRegion`. -/
noncomputable def ofKählerPreparationFlow
    (p₀ : CPN 4) (sh : KTorus) (hgen : ∀ s t : Sign, 0 < P_st ctx.a ctx.b s t) :
    LF3.PureSingletPreparation (kSectorDataFlow p₀ sh) ctx 4 :=
  LF3.PureSingletPreparation.ofHypothesis
    kMuPsi inferInstance
    (fubiniStudyMeasure p₀) inferInstance
    (kBridgeFlow p₀ sh)
    (kPurePrepFlow p₀ sh)
    (by decide)
    (kJED ctx hgen)
    (kOutcomeRegionFlow ctx p₀ sh)
    (by
      intro s t
      show kMuPsi (kFlow sh ⁻¹' kRegion ctx s t) = _
      rw [(kFlow_measurePreserving_muPsi sh).measure_preimage
            (kRegion_measurable ctx s t).nullMeasurableSet,
          kMuPsi_kRegion]
      congr 1
      symm
      rw [LF2.PurePreparation.born_rank_one_direct
            (kSectorDataFlow p₀ sh) (fubiniStudyMeasure p₀) (kBridgeFlow p₀ sh) kMuPsi
            (kPurePrepFlow p₀ sh) ((kJED ctx hgen).eig s t) ((kJED ctx hgen).eig_unit s t)]
      exact kEig_born ctx hgen s t)

/-- The underlying sector genuinely carries `Φ ≠ id` (for any nonzero fibre shift),
via `kFlow_ne_id`. This is the SL-2 headline: the concrete ENTANGLED sector now
carries a genuine non-identity flow. -/
theorem ofKählerPreparationFlow_phi_ne_id (p₀ : CPN 4) {sh : KTorus} (hsh : sh ≠ 0) :
    (kSectorDataFlow p₀ sh).toOntic.Φ ≠ id :=
  kFlow_ne_id p₀ hsh

/-- The scored event of the flow preparation is the flow-pullback of the carved
region: `preEvent = kFlow sh ⁻¹' kRegion`. So scoring trial `X n` on it reads
`X n ⁻¹' preEvent = (kFlow sh ∘ X n) ⁻¹' kRegion` — the microstate is evolved one
flow-step before its outcome block is checked. -/
lemma ofKählerPreparationFlow_preEvent
    (p₀ : CPN 4) (sh : KTorus) (hgen : ∀ s t : Sign, 0 < P_st ctx.a ctx.b s t)
    (s t : Sign) :
    ((ofKählerPreparationFlow ctx p₀ sh hgen).O_region s t).preEvent
      = kFlow sh ⁻¹' kRegion ctx s t := rfl

/-! ### The load-bearing capstone: frequencies of flow-evolved singlet trials -/

open Filter Topology in
/-- **SL-2 capstone: the singlet frequencies survive the sector's own flow.** For
i.i.d. trials with the posited singlet fibre law `μψ`, the per-sector empirical
frequencies of the trials **evolved by the sector's non-identity flow**
`kFlow sh ≠ id` — i.e. of `(kFlow sh ∘ X) ⁻¹' kRegion` — converge almost surely to
the Born weight `P_st ctx.a ctx.b s t`.

The deterministic flow `kFlow sh` is applied to every sampled microstate, and its
Liouville-preservation (`kFlow_measurePreserving_muPsi`) is exactly what keeps the
limit at `P_st` (via `bridge_op_p` / `weight_eq_P_st`). This is D1c-1's
load-bearing-flow achievement realised on the ENTANGLED singlet preparation.
Foundational-triple-only / Gleason-free. Standing gap unchanged: A5 (the entangled
sector is posited) and `kFlow` is dynamically trivial (a free fibre translation). -/
theorem ofKählerPreparationFlow_flow_frequency_convergence
    (p₀ : CPN 4) (sh : KTorus) (hgen : ∀ s t : Sign, 0 < P_st ctx.a ctx.b s t)
    {Ω : Type*} [MeasurableSpace Ω] {Pr : Measure Ω} [IsProbabilityMeasure Pr]
    {X : ℕ → Ω → KSigma 4} (hX : ∀ n, Measurable (X n))
    (hlaw : ∀ n, Measure.map (X n) Pr = kMuPsi)
    (hindep : ∀ s t,
      Pairwise
        (Function.onFun
          (fun f g : Ω → ℝ => ProbabilityTheory.IndepFun f g Pr)
          (fun n =>
            Set.indicator ((kFlow sh ∘ X n) ⁻¹' kRegion ctx s t) (fun _ => (1 : ℝ))))) :
    ∀ s t, ∀ᵐ ω ∂ Pr,
      Tendsto
        (fun M : ℕ =>
          (∑ i ∈ Finset.range M,
              Set.indicator ((kFlow sh ∘ X i) ⁻¹' kRegion ctx s t)
                (fun _ => (1 : ℝ)) ω) / (M : ℝ))
        atTop
        (nhds (P_st ctx.a ctx.b s t)) := by
  intro s t
  have hind' : ∀ s t,
      Pairwise
        (Function.onFun (fun f g : Ω → ℝ => ProbabilityTheory.IndepFun f g Pr)
          (fun n =>
            Set.indicator
              (X n ⁻¹' ((ofKählerPreparationFlow ctx p₀ sh hgen).O_region s t).preEvent)
              (fun _ => (1 : ℝ)))) := fun s t => by
    simpa only [ofKählerPreparationFlow_preEvent, ← Set.preimage_comp] using hindep s t
  have hconv := LF3.LF3_singlet_frequency_convergence
    (kSectorDataFlow p₀ sh) ctx (ofKählerPreparationFlow ctx p₀ sh hgen) hX hlaw hind' s t
  simpa only [ofKählerPreparationFlow_preEvent, ← Set.preimage_comp] using hconv

end LF4
end CSD
