/-
Copyright (c) 2026 Zayn Blore. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zayn Blore
-/
module

public import CsdLean4.Mathlib.Analysis.Matrix.SchrodingerUnitary
public import CsdLean4.Mathlib.Analysis.Semigroup.MatrixInstance
public import CsdLean4.Mathlib.QuantumInfo.SU2Rotation

/-!
# The rotating frame: a time-dependent Schrödinger equation solved exactly

**Category:** 1-Mathlib (CSD-free; staged for upstream). BACKLOG #56, brick BP-5 of
`specs/berry-phase-scoping.md`.

A Hamiltonian that is *rigidly rotated* by a one-parameter unitary group,
`H(t) = e^{−itG} H₀ e^{itG}`, has an exactly solvable time-dependent Schrödinger equation: its
propagator is
`V(t) = e^{−itG} · e^{−it(H₀ − G)}`,
the drive times the evolution generated by the *constant* rotating-frame Hamiltonian
`K = H₀ − G`. ★★ `hasDerivAt_rotProp` proves `V′(t) = −i H(t) V(t)` (with `V 0 = 1` and `V t`
unitary), and ★ `hasDerivAt_rotState` transports it to a state `V(t) ψ₀` of `ℂᴺ`.

The reduction is one line of algebra once it is stated in the right form: ★★
`hasDerivAt_mul_of_gen` asks only that `u` be generated by `G` on the right, that `e` be generated
by `K = H₀ − G` on the left, and that `u t` be unitary — then `u t (−iG) e t + u t (−iK) e t
= u t (−iH₀) e t = −i H(t) · u t e t`. Both instances in the corpus are four-line applications:
the matrix exponential here, and the axis–angle rotations of spin-½ in
`CsdLean4/Empirical/QM/BerryAdiabatic.lean` (BACKLOG #56, the adiabatic theorem for a spin in a
rotating field), which never mention `exp` at all.

The second half of the file is the spin-½ calculus that application needs: the Hermitian Pauli
combination `pauliAxis a b c = a σ₁ + b σ₂ + c σ₃` with ★ `pauliAxis_mul_self`
(`(n·σ)² = ‖n‖² · 1`), the rotations of `SU2Rotation.lean` written in terms of it (`axisRot_eq`),
their derivative in the angle (★ `hasDerivAt_axisRot`, `d/dt R_n(Ωt) = (−i(Ω/2) n·σ) R_n(Ωt)`, with
no matrix exponential and no entrywise differentiation — the path is a scalar combination of two
*constant* matrices) and the Bloch rotation ★ `axisRot_z_conj`: conjugating `n·σ` by a
`z`-rotation turns `n` about `z` by the angle. That last identity is what makes a rotating field a
rigid rotation of a fixed Hamiltonian.

## Main declarations

* ★★ `hasDerivAt_mul_of_gen` — the rotating-frame reduction, hypothesis form;
* `schrodingerUnitary_hasDerivAt_left` — the left-generated twin of
  `Matrix.schrodingerUnitary_hasDerivAt`;
* `rotHam`, `rotProp`, `rotHam_isHermitian`, `rotProp_zero`, `rotProp_mem_unitaryGroup`;
* ★★ `hasDerivAt_rotProp` — `V′ = −i H(t) V` for `V(t) = e^{−itG} e^{−it(H₀−G)}`;
* ★ `hasDerivAt_rotState` — the same equation for the state `V(t) ψ₀` on `ℂᴺ`;
* `pauliAxis`, `pauliAxis_isHermitian`, `su2_eq`, `pauliAxis_smul`, ★ `pauliAxis_mul_self`,
  `axisRot_eq`, `su2_conjTranspose`, `axisRot_conjTranspose`, `axisRot_mul_conjTranspose`,
  `axisRot_two_pi`;
* ★ `smul_pauliAxis_mul_axisRot`, ★ `hasDerivAt_axisRot`, ★ `axisRot_z_conj`.

## Honest scope

⚠️ The drive is a *rigid* rotation: `H(t)` is the conjugation orbit of a single `H₀` under a
one-parameter group, so the eigenvalues never move. Nothing here treats a general time-dependent
`H(t)`, for which there is no closed form, nor the adiabatic theorem of Kato–Born–Fock in its
general form (an arbitrary gapped path of Hamiltonians, error `O(1/T)`): that is BACKLOG #88, and
it is not claimed anywhere in this corpus.

References: L. D. Landau, E. M. Lifshitz, *Quantum Mechanics* §39 (the rotating frame); I. I. Rabi,
Phys. Rev. 51 (1937) 652; M. V. Berry, Proc. R. Soc. A 392 (1984) 45, §5;
`specs/berry-phase-scoping.md`; `specs/BACKLOG.md` #56; `specs/future-work.md`.
-/

@[expose] public section

noncomputable section

open scoped Matrix.Norms.L2Operator Real
open Matrix NormedSpace

namespace QuantumInfo

namespace RotatingFrame

variable {N : ℕ}

/-! ### The reduction -/

/-- ★★ **The rotating-frame reduction.** If `u` is a matrix path generated by `G` on the right
(`u′ = u · (−iG)`), `e` a path generated by `K = H₀ − G` on the left (`e′ = (−iK) · e`) and `u t`
is unitary, then the product `u e` solves the time-dependent Schrödinger equation of the rigidly
rotated Hamiltonian `H(t) = u t · H₀ · (u t)ᴴ`:
`(u e)′(t) = −i H(t) · (u t · e t)`.

Nothing is assumed about how `u` and `e` are built; the two instances in the corpus are the matrix
exponential (`hasDerivAt_rotProp`) and the axis–angle rotations of spin-½. -/
theorem hasDerivAt_mul_of_gen {G H₀ : Matrix (Fin N) (Fin N) ℂ}
    {u e : ℝ → Matrix (Fin N) (Fin N) ℂ} {t : ℝ}
    (hu : HasDerivAt u (u t * ((-Complex.I) • G)) t)
    (he : HasDerivAt e (((-Complex.I) • (H₀ - G)) * e t) t)
    (hU : (u t)ᴴ * u t = 1) :
    HasDerivAt (fun τ => u τ * e τ)
      ((-Complex.I) • (u t * H₀ * (u t)ᴴ * (u t * e t))) t := by
  refine (hu.mul he).congr_deriv ?_
  have h1 : u t * H₀ * (u t)ᴴ * (u t * e t) = u t * H₀ * e t := by
    rw [Matrix.mul_assoc (u t * H₀), ← Matrix.mul_assoc ((u t)ᴴ), hU, Matrix.one_mul]
  rw [h1]
  simp only [Matrix.mul_smul, Matrix.smul_mul]
  rw [← smul_add]
  congr 1
  noncomm_ring

/-- The left-generated twin of `Matrix.schrodingerUnitary_hasDerivAt`: the family
`U t = e^{−itH}` also has derivative `(−iH) · U t`, since a matrix exponential commutes with its
own generator. -/
theorem schrodingerUnitary_hasDerivAt_left (H : Matrix (Fin N) (Fin N) ℂ) (hH : H.IsHermitian)
    (t : ℝ) :
    HasDerivAt (fun τ : ℝ => (schrodingerUnitary hH τ : Matrix (Fin N) (Fin N) ℂ))
      (((-Complex.I) • H) * (schrodingerUnitary hH t : Matrix (Fin N) (Fin N) ℂ)) t := by
  have hfun : (fun τ : ℝ => (schrodingerUnitary hH τ : Matrix (Fin N) (Fin N) ℂ))
      = (fun τ : ℝ => NormedSpace.exp (τ • ((-Complex.I) • H))) := by
    funext τ
    show NormedSpace.exp (schrodingerGen H τ) = _
    rw [schrodingerGen_eq_real_smul]
  have hval : (schrodingerUnitary hH t : Matrix (Fin N) (Fin N) ℂ)
      = NormedSpace.exp (t • ((-Complex.I) • H)) := by
    show NormedSpace.exp (schrodingerGen H t) = _
    rw [schrodingerGen_eq_real_smul]
  rw [hfun, hval]
  exact hasDerivAt_exp_smul_const' ((-Complex.I) • H) t

/-! ### The exponential instance -/

variable {G : Matrix (Fin N) (Fin N) ℂ}

/-- The rigidly rotated Hamiltonian `H(t) = e^{−itG} H₀ e^{itG}`. -/
def rotHam (hG : G.IsHermitian) (H₀ : Matrix (Fin N) (Fin N) ℂ) (t : ℝ) :
    Matrix (Fin N) (Fin N) ℂ :=
  (schrodingerUnitary hG t : Matrix (Fin N) (Fin N) ℂ) * H₀
    * (schrodingerUnitary hG t : Matrix (Fin N) (Fin N) ℂ)ᴴ

/-- The rotating-frame propagator `V(t) = e^{−itG} · e^{−it(H₀ − G)}`. -/
def rotProp (hG : G.IsHermitian) {H₀ : Matrix (Fin N) (Fin N) ℂ} (hH : H₀.IsHermitian) (t : ℝ) :
    Matrix (Fin N) (Fin N) ℂ :=
  (schrodingerUnitary hG t : Matrix (Fin N) (Fin N) ℂ)
    * (schrodingerUnitary (hH.sub hG) t : Matrix (Fin N) (Fin N) ℂ)

theorem rotHam_zero (hG : G.IsHermitian) (H₀ : Matrix (Fin N) (Fin N) ℂ) :
    rotHam hG H₀ 0 = H₀ := by
  rw [rotHam, (expNegITH_unitary_group hG).2]
  simp

theorem rotHam_isHermitian (hG : G.IsHermitian) {H₀ : Matrix (Fin N) (Fin N) ℂ}
    (hH : H₀.IsHermitian) (t : ℝ) : (rotHam hG H₀ t).IsHermitian := by
  show (rotHam hG H₀ t)ᴴ = rotHam hG H₀ t
  simp only [rotHam, Matrix.conjTranspose_mul, Matrix.conjTranspose_conjTranspose, hH.eq,
    ← Matrix.mul_assoc]

theorem rotProp_zero (hG : G.IsHermitian) {H₀ : Matrix (Fin N) (Fin N) ℂ}
    (hH : H₀.IsHermitian) : rotProp hG hH 0 = 1 := by
  rw [rotProp, (expNegITH_unitary_group hG).2, (expNegITH_unitary_group (hH.sub hG)).2]
  simp

theorem rotProp_mem_unitaryGroup (hG : G.IsHermitian) {H₀ : Matrix (Fin N) (Fin N) ℂ}
    (hH : H₀.IsHermitian) (t : ℝ) : rotProp hG hH t ∈ Matrix.unitaryGroup (Fin N) ℂ :=
  mul_mem (schrodingerUnitary hG t).2 (schrodingerUnitary (hH.sub hG) t).2

/-- ★★ **The rigidly rotated Hamiltonian has an exact propagator.** For Hermitian `G` and `H₀`,
the path `V(t) = e^{−itG} e^{−it(H₀−G)}` solves the time-dependent Schrödinger equation
`V′(t) = −i H(t) V(t)` of `H(t) = e^{−itG} H₀ e^{itG}`, with `V 0 = 1` (`rotProp_zero`) and `V t`
unitary (`rotProp_mem_unitaryGroup`). -/
theorem hasDerivAt_rotProp (hG : G.IsHermitian) {H₀ : Matrix (Fin N) (Fin N) ℂ}
    (hH : H₀.IsHermitian) (t : ℝ) :
    HasDerivAt (rotProp hG hH) ((-Complex.I) • (rotHam hG H₀ t * rotProp hG hH t)) t := by
  have hU : ((schrodingerUnitary hG t : Matrix (Fin N) (Fin N) ℂ))ᴴ
      * (schrodingerUnitary hG t : Matrix (Fin N) (Fin N) ℂ) = 1 := by
    have h := (schrodingerUnitary hG t).2
    rw [Matrix.mem_unitaryGroup_iff', Matrix.star_eq_conjTranspose] at h
    exact h
  have h := hasDerivAt_mul_of_gen (G := G) (H₀ := H₀)
    (Matrix.schrodingerUnitary_hasDerivAt G hG t)
    (schrodingerUnitary_hasDerivAt_left (H₀ - G) (hH.sub hG) t) hU
  exact h

/-- ★ **The state form.** The path `ψ(t) = V(t) ψ₀` of `ℂᴺ` solves `ψ′(t) = −i H(t) ψ(t)`. -/
theorem hasDerivAt_rotState (hG : G.IsHermitian) {H₀ : Matrix (Fin N) (Fin N) ℂ}
    (hH : H₀.IsHermitian) (ψ₀ : EuclideanSpace ℂ (Fin N)) (t : ℝ) :
    HasDerivAt (fun τ => Matrix.toEuclideanCLM (𝕜 := ℂ) (rotProp hG hH τ) ψ₀)
      ((-Complex.I) • Matrix.toEuclideanCLM (𝕜 := ℂ) (rotHam hG H₀ t)
        (Matrix.toEuclideanCLM (𝕜 := ℂ) (rotProp hG hH t) ψ₀)) t := by
  have h := ((Matrix.evalCLM ψ₀).restrictScalars ℝ).hasFDerivAt.comp_hasDerivAt t
    (hasDerivAt_rotProp hG hH t)
  refine h.congr_deriv ?_
  show Matrix.evalCLM ψ₀ ((-Complex.I) • (rotHam hG H₀ t * rotProp hG hH t)) = _
  rw [map_smul, Matrix.evalCLM_apply, Matrix.toEuclideanCLM_mul_apply]

/-! ### Inner products on `ℂᴺ`

The two facts the state-level analysis needs: a matrix moves across an inner product as its
conjugate transpose, and a unitary preserves the inner product. -/

theorem inner_toEuclideanCLM_left (A : Matrix (Fin N) (Fin N) ℂ)
    (x y : EuclideanSpace ℂ (Fin N)) :
    inner ℂ (Matrix.toEuclideanCLM (𝕜 := ℂ) A x) y
      = inner ℂ x (Matrix.toEuclideanCLM (𝕜 := ℂ) Aᴴ y) := by
  have hlin : ∀ (M : Matrix (Fin N) (Fin N) ℂ) (z : EuclideanSpace ℂ (Fin N)),
      Matrix.toEuclideanCLM (𝕜 := ℂ) M z = Matrix.toEuclideanLin M z := fun M z =>
    LinearMap.congr_fun (Matrix.coe_toEuclideanCLM_eq_toEuclideanLin M) z
  rw [hlin, hlin, ← LinearMap.adjoint_inner_right (Matrix.toEuclideanLin A),
    show (Matrix.toEuclideanLin A).adjoint = Matrix.toEuclideanLin Aᴴ from
      (Matrix.toEuclideanLin_conjTranspose_eq_adjoint A).symm]

/-- ★ **A unitary preserves the inner product of `ℂᴺ`.** -/
theorem inner_toEuclideanCLM_unitary {U : Matrix (Fin N) (Fin N) ℂ} (hU : Uᴴ * U = 1)
    (x y : EuclideanSpace ℂ (Fin N)) :
    inner ℂ (Matrix.toEuclideanCLM (𝕜 := ℂ) U x) (Matrix.toEuclideanCLM (𝕜 := ℂ) U y)
      = inner ℂ x y := by
  rw [inner_toEuclideanCLM_left, ← Matrix.toEuclideanCLM_mul_apply, hU, map_one,
    one_apply_eq_self]

end RotatingFrame

/-! ### The spin-½ calculus

The `2 × 2` layer the rotating-field application consumes: the Hermitian Pauli combination, the
rotations of `SU2Rotation.lean` in terms of it, and their derivative in the angle. -/

namespace SU2

/-- The Hermitian Pauli combination `pauliAxis a b c = a σ₁ + b σ₂ + c σ₃`. Its square is
`(a² + b² + c²) · 1` (★ `pauliAxis_mul_self`), so for a unit vector it is an involution with
eigenvalues `±1`, and `(B/2) · pauliAxis` is the Hamiltonian of a spin-½ in the field
`B·(a, b, c)`. -/
def pauliAxis (a b c : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  !![(c : ℂ), (a : ℂ) - Complex.I * (b : ℂ); (a : ℂ) + Complex.I * (b : ℂ), -(c : ℂ)]

theorem pauliAxis_isHermitian (a b c : ℝ) : (pauliAxis a b c).IsHermitian := by
  show (pauliAxis a b c)ᴴ = pauliAxis a b c
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [pauliAxis, Matrix.conjTranspose_apply, Complex.ext_iff]

/-- `su2 w x y z = w·1 − i(x σ₁ + y σ₂ + z σ₃)`, in terms of `pauliAxis`. -/
theorem su2_eq (w x y z : ℝ) :
    su2 w x y z = (w : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) - Complex.I • pauliAxis x y z := by
  ext i j
  fin_cases i <;> fin_cases j <;> simp [su2, pauliAxis]

/-- `pauliAxis` is `i` times a purely imaginary quaternion: this is how it inherits the quaternion
product `su2_mul`. -/
theorem pauliAxis_eq_smul_su2 (a b c : ℝ) : pauliAxis a b c = Complex.I • su2 0 a b c := by
  ext i j
  fin_cases i <;> fin_cases j <;> simp [pauliAxis, su2, Complex.ext_iff]

/-- A real quaternion is a scalar matrix. -/
theorem su2_scalar (w : ℝ) : su2 w 0 0 0 = (w : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) := by
  ext i j
  fin_cases i <;> fin_cases j <;> simp [su2]

/-- The square of a purely imaginary quaternion is the real scalar `−‖·‖²`. -/
theorem su2_mul_self_imaginary (a b c : ℝ) :
    su2 0 a b c * su2 0 a b c = su2 (-(a ^ 2 + b ^ 2 + c ^ 2)) 0 0 0 := by
  rw [su2_mul]
  congr 1 <;> ring

/-- `pauliAxis` is linear in the vector. -/
theorem pauliAxis_smul (s a b c : ℝ) :
    pauliAxis (a * s) (b * s) (c * s) = (s : ℂ) • pauliAxis a b c := by
  ext i j
  fin_cases i <;> fin_cases j <;> simp [pauliAxis] <;> ring

/-- ★ **`(n·σ)² = ‖n‖² · 1`.** -/
theorem pauliAxis_mul_self (a b c : ℝ) :
    pauliAxis a b c * pauliAxis a b c
      = ((a ^ 2 + b ^ 2 + c ^ 2 : ℝ) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) := by
  rw [pauliAxis_eq_smul_su2, Matrix.smul_mul, Matrix.mul_smul, smul_smul,
    su2_mul_self_imaginary, su2_scalar, smul_smul]
  congr 1
  rw [Complex.I_mul_I]
  push_cast
  ring

theorem pauliAxis_mul_self_of_unit {a b c : ℝ} (hu : a ^ 2 + b ^ 2 + c ^ 2 = 1) :
    pauliAxis a b c * pauliAxis a b c = 1 := by
  rw [pauliAxis_mul_self, hu]
  simp

/-- The axis rotation in terms of `pauliAxis`: `R_n(θ) = cos(θ/2)·1 − i sin(θ/2) n·σ`. Both
matrices on the right are *constant* in `θ`, which is what makes the derivative elementary. -/
theorem axisRot_eq (a b c θ : ℝ) :
    axisRot a b c θ = (Real.cos (θ / 2) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ)
      - (Complex.I * (Real.sin (θ / 2) : ℂ)) • pauliAxis a b c := by
  rw [axisRot, su2_eq, pauliAxis_smul, smul_smul]

theorem su2_conjTranspose (w x y z : ℝ) : (su2 w x y z)ᴴ = su2 w (-x) (-y) (-z) := by
  ext i j
  fin_cases i <;> fin_cases j <;> simp [su2, Matrix.conjTranspose_apply, Complex.ext_iff]

theorem axisRot_conjTranspose (a b c θ : ℝ) : (axisRot a b c θ)ᴴ = axisRot a b c (-θ) := by
  rw [axisRot, axisRot, su2_conjTranspose, neg_div, Real.cos_neg, Real.sin_neg]
  congr 1 <;> ring

theorem axisRot_mul_conjTranspose {a b c : ℝ} (hu : a ^ 2 + b ^ 2 + c ^ 2 = 1) (θ : ℝ) :
    axisRot a b c θ * (axisRot a b c θ)ᴴ = 1 := by
  rw [axisRot_conjTranspose, ← axisRot_add hu, add_neg_cancel, axisRot_zero]

/-- A `2π` rotation is `−1`: the sign that turns the phase accumulated around a closed loop into
the geometric phase. -/
theorem axisRot_two_pi (a b c : ℝ) : axisRot a b c (2 * π) = -1 := by
  rw [axisRot, show 2 * π / 2 = π by ring, Real.cos_pi, Real.sin_pi]
  ext i j
  fin_cases i <;> fin_cases j <;> simp [su2]

/-- ★ The algebraic heart of the derivative: `(−i(Ω/2) n·σ) · R_n(θ)` in `cos`/`sin` form, for a
unit axis. -/
theorem smul_pauliAxis_mul_axisRot {a b c : ℝ} (hu : a ^ 2 + b ^ 2 + c ^ 2 = 1) (Ω θ : ℝ) :
    (((-Complex.I) * ((Ω / 2 : ℝ) : ℂ)) • pauliAxis a b c) * axisRot a b c θ
      = ((-(Ω / 2) * Real.sin (θ / 2) : ℝ) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ)
        - (Complex.I * ((Ω / 2 * Real.cos (θ / 2) : ℝ) : ℂ)) • pauliAxis a b c := by
  rw [axisRot_eq, mul_sub, Matrix.smul_mul, Matrix.smul_mul, Matrix.mul_smul, Matrix.mul_smul,
    Matrix.mul_one, pauliAxis_mul_self_of_unit hu, smul_smul, smul_smul]
  have h1 : (-Complex.I) * ((Ω / 2 : ℝ) : ℂ) * ((Real.cos (θ / 2) : ℝ) : ℂ)
      = -(Complex.I * ((Ω / 2 * Real.cos (θ / 2) : ℝ) : ℂ)) := by
    rw [Complex.ofReal_mul]
    ring
  have h2 : (-Complex.I) * ((Ω / 2 : ℝ) : ℂ) * (Complex.I * ((Real.sin (θ / 2) : ℝ) : ℂ))
      = -(((-(Ω / 2) * Real.sin (θ / 2) : ℝ) : ℂ)) := by
    rw [Complex.ofReal_mul, Complex.ofReal_neg]
    linear_combination (-(((Ω / 2 : ℝ) : ℂ) * ((Real.sin (θ / 2) : ℝ) : ℂ))) * Complex.I_mul_I
  rw [h1, h2]
  module

/-- ★ **The derivative of an axis rotation.** `d/dt R_n(Ωt) = (−i(Ω/2) n·σ) · R_n(Ωt)`: the
rotation about a unit axis is the Schrödinger evolution generated by the constant Hamiltonian
`(Ω/2) n·σ`. No matrix exponential and no entrywise differentiation is involved — `R_n(Ωt)` is a
scalar combination of the two constant matrices `1` and `n·σ`. -/
theorem hasDerivAt_axisRot {a b c : ℝ} (hu : a ^ 2 + b ^ 2 + c ^ 2 = 1) (Ω t : ℝ) :
    HasDerivAt (fun τ : ℝ => axisRot a b c (Ω * τ))
      ((((-Complex.I) * ((Ω / 2 : ℝ) : ℂ)) • pauliAxis a b c) * axisRot a b c (Ω * t)) t := by
  have harg : HasDerivAt (fun τ : ℝ => Ω * τ / 2) (Ω / 2) t := by
    simpa using ((hasDerivAt_id t).const_mul Ω).div_const 2
  have hcos : HasDerivAt (fun τ : ℝ => ((Real.cos (Ω * τ / 2) : ℝ) : ℂ))
      (((-(Ω / 2) * Real.sin (Ω * t / 2) : ℝ) : ℂ)) t := by
    refine (((Real.hasDerivAt_cos (Ω * t / 2)).comp t harg).ofReal_comp).congr_deriv ?_
    rw [Complex.ofReal_mul, Complex.ofReal_mul]
    push_cast
    ring
  have hsin : HasDerivAt (fun τ : ℝ => ((Real.sin (Ω * τ / 2) : ℝ) : ℂ))
      (((Ω / 2 * Real.cos (Ω * t / 2) : ℝ) : ℂ)) t := by
    refine (((Real.hasDerivAt_sin (Ω * t / 2)).comp t harg).ofReal_comp).congr_deriv ?_
    rw [Complex.ofReal_mul, Complex.ofReal_mul]
    push_cast
    ring
  have hfun : (fun τ : ℝ => axisRot a b c (Ω * τ))
      = fun τ : ℝ => ((Real.cos (Ω * τ / 2) : ℝ) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ)
        - (Complex.I * ((Real.sin (Ω * τ / 2) : ℝ) : ℂ)) • pauliAxis a b c := by
    funext τ
    rw [axisRot_eq]
  rw [hfun, smul_pauliAxis_mul_axisRot hu]
  exact (hcos.smul_const (1 : Matrix (Fin 2) (Fin 2) ℂ)).sub
    ((hsin.const_mul Complex.I).smul_const (pauliAxis a b c))

/-- ★ **The Bloch rotation, quaternion form.** -/
theorem su2_z_conj (a b c φ : ℝ) :
    axisRot 0 0 1 φ * su2 0 a b c * (axisRot 0 0 1 φ)ᴴ
      = su2 0 (a * Real.cos φ - b * Real.sin φ) (a * Real.sin φ + b * Real.cos φ) c := by
  have hc : Real.cos (φ / 2) ^ 2 - Real.sin (φ / 2) ^ 2 = Real.cos φ := by
    rw [← Real.cos_two_mul', show 2 * (φ / 2) = φ by ring]
  have hs : 2 * Real.sin (φ / 2) * Real.cos (φ / 2) = Real.sin φ := by
    rw [← Real.sin_two_mul, show 2 * (φ / 2) = φ by ring]
  rw [← hc, ← hs, axisRot_conjTranspose, axisRot, axisRot, neg_div, Real.cos_neg, Real.sin_neg,
    su2_mul, su2_mul]
  congr 1 <;>
    first
      | ring1
      | linear_combination c * Real.sin_sq_add_cos_sq (φ / 2)

/-- ★ **The Bloch rotation.** Conjugating `n·σ` by the `z`-rotation `R_z(φ)` turns `n` about the
`z`-axis by `φ`. This is the `SU(2) → SO(3)` homomorphism on one axis, and it is what lets a
rotating field be written as a rigid rotation of a fixed Hamiltonian. -/
theorem axisRot_z_conj (a b c φ : ℝ) :
    axisRot 0 0 1 φ * pauliAxis a b c * (axisRot 0 0 1 φ)ᴴ
      = pauliAxis (a * Real.cos φ - b * Real.sin φ) (a * Real.sin φ + b * Real.cos φ) c := by
  rw [pauliAxis_eq_smul_su2, pauliAxis_eq_smul_su2, Matrix.mul_smul, Matrix.smul_mul, su2_z_conj]

theorem pauliAxis_add (a b c a' b' c' : ℝ) :
    pauliAxis a b c + pauliAxis a' b' c' = pauliAxis (a + a') (b + b') (c + c') := by
  ext i j
  fin_cases i <;> fin_cases j <;> simp [pauliAxis] <;> ring

theorem pauliAxis_sub (a b c a' b' c' : ℝ) :
    pauliAxis a b c - pauliAxis a' b' c' = pauliAxis (a - a') (b - b') (c - c') := by
  ext i j
  fin_cases i <;> fin_cases j <;> simp [pauliAxis] <;> ring

/-- `pauliAxis_smul` with the scalar on the left. -/
theorem smul_pauliAxis (s a b c : ℝ) :
    ((s : ℝ) : ℂ) • pauliAxis a b c = pauliAxis (s * a) (s * b) (s * c) := by
  rw [show s * a = a * s from mul_comm s a, show s * b = b * s from mul_comm s b,
    show s * c = c * s from mul_comm s c, pauliAxis_smul]

/-- `n·σ` commutes with every rotation about `n`. -/
theorem commute_smul_pauliAxis_axisRot (z : ℂ) (a b c θ : ℝ) :
    (z • pauliAxis a b c) * axisRot a b c θ = axisRot a b c θ * (z • pauliAxis a b c) := by
  have h : pauliAxis a b c * axisRot a b c θ = axisRot a b c θ * pauliAxis a b c := by
    simp only [axisRot_eq, mul_sub, sub_mul, Matrix.mul_smul, Matrix.smul_mul, Matrix.mul_one,
      Matrix.one_mul]
  rw [Matrix.smul_mul, Matrix.mul_smul, h]

/-- ★ `hasDerivAt_axisRot` with the generator on the right, the form the rotating-frame reduction
takes for the drive. -/
theorem hasDerivAt_axisRot_right {a b c : ℝ} (hu : a ^ 2 + b ^ 2 + c ^ 2 = 1) (Ω t : ℝ) :
    HasDerivAt (fun τ : ℝ => axisRot a b c (Ω * τ))
      (axisRot a b c (Ω * t) * (((-Complex.I) * ((Ω / 2 : ℝ) : ℂ)) • pauliAxis a b c)) t :=
  (hasDerivAt_axisRot hu Ω t).congr_deriv
    (commute_smul_pauliAxis_axisRot ((-Complex.I) * ((Ω / 2 : ℝ) : ℂ)) a b c (Ω * t))

end SU2

end QuantumInfo

end
