import Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Point
import Mathlib.GroupTheory.OrderOfElement

/-!
# Elliptic-curve scalar multiplication and the ECDLP  (ECDLP Tranche 5)

**Category:** 1-Mathlib (CSD-free; staged as a Mathlib-upstream candidate).

The elliptic-curve layer of the ECDLP resource-accounting programme
(`specs/ecdlp-resource-plan.md`). The group law is **entirely Mathlib's**
(`WeierstrassCurve.Affine.Point` + its `AddCommGroup` instance); this module does **not** reprove it.
It wraps that group into the two objects the rest of the programme needs:

* `scalarMul P k = k • P` — elliptic-curve scalar multiplication, the discrete-log map `[k]P`. Its
  structural lemmas (`zero`/`one`/`succ`/the **homomorphism** `[j+k]P = [j]P + [k]P`/periodicity at
  `addOrderOf P`) are the algebra that double-and-add (Tranche 6) and Shor period-finding consume.
* `IsDLog` / `Solvable` — the elliptic-curve discrete logarithm problem: given base `P` and target `Q`,
  find `k` with `[k]P = Q`. `Q` is solvable iff it lies in the cyclic subgroup generated by `P`.

Everything here is `nsmul`/`addOrderOf` on the Mathlib point group; the genuine increment is naming the
ECDLP precisely and exposing the scalar-mul algebra. The layer is non-vacuous abstractly (`W.Point`
always contains `0`, and fields exist — e.g. every statement instantiates over `Affine ℚ`); a concrete
`P ≠ 0` point needs a `Nonsingular` witness, deferred with the secp256k1 curve to **Tranche 7**.

Tranche-7 note: instantiate the base field via a single `Field`/`CommRing` instance path — over `ZMod p`
with a *free* curve variable the `AddCommGroup W.Point` synthesis can hit a `CommRing` diamond; the
abstract layer here is unaffected (it carries `[Field F] [DecidableEq F]`).
-/

namespace ECDLP

open WeierstrassCurve

variable {F : Type*} [Field F] [DecidableEq F] {W : Affine F}

/-- **Elliptic-curve scalar multiplication** `[k]P = k • P` (the iterated group operation): the
discrete-log map the ECDLP inverts and double-and-add (Tranche 6) realises. -/
def scalarMul (P : W.Point) (k : ℕ) : W.Point := k • P

@[simp] theorem scalarMul_zero (P : W.Point) : scalarMul P 0 = 0 := zero_nsmul P

@[simp] theorem scalarMul_one (P : W.Point) : scalarMul P 1 = P := one_nsmul P

/-- `[k+1]P = [k]P + P` — the recurrence double-and-add iterates. -/
theorem scalarMul_succ (P : W.Point) (k : ℕ) : scalarMul P (k + 1) = scalarMul P k + P :=
  succ_nsmul P k

/-- **The scalar-multiplication homomorphism** `[j+k]P = [j]P + [k]P` — the additive structure Shor's
period-finding and the double-and-add decomposition both exploit. -/
theorem scalarMul_add (P : W.Point) (j k : ℕ) :
    scalarMul P (j + k) = scalarMul P j + scalarMul P k :=
  add_nsmul P j k

/-- `[j·k]P = [j]([k]P)` — scalar multiplication composes (the basis for the windowed / double-and-add
exponent decomposition). -/
theorem scalarMul_mul (P : W.Point) (j k : ℕ) :
    scalarMul P (j * k) = scalarMul (scalarMul P k) j := by
  simp only [scalarMul, mul_nsmul']

/-- **Periodicity**: `[addOrderOf P]P = 0`. The order of the base point is the period Shor's algorithm
recovers; the discrete log is determined modulo it. -/
theorem scalarMul_addOrderOf (P : W.Point) : scalarMul P (addOrderOf P) = 0 :=
  addOrderOf_nsmul_eq_zero P

/-! ### The elliptic-curve discrete logarithm problem -/

/-- `k` is a discrete logarithm of `Q` to base `P`: `[k]P = Q`. -/
def IsDLog (P Q : W.Point) (k : ℕ) : Prop := scalarMul P k = Q

/-- `Q` is ECDLP-solvable to base `P`: some `k` has `[k]P = Q` (i.e. `Q` lies in the cyclic subgroup
generated by `P`). The ECDLP is the problem of *finding* such a `k`. -/
def Solvable (P Q : W.Point) : Prop := ∃ k : ℕ, IsDLog P Q k

/-- The base point always solves itself at `k = 1`. -/
theorem solvable_self (P : W.Point) : Solvable P P := ⟨1, scalarMul_one P⟩

/-- The identity is always solvable at `k = 0`. -/
theorem solvable_zero (P : W.Point) : Solvable P (0 : W.Point) := ⟨0, scalarMul_zero P⟩

/-- A solution stays a solution after shifting by the order of `P` — the ambiguity ECDLP solutions
carry, and exactly the period Shor's algorithm exposes. -/
theorem isDLog_add_addOrderOf {P Q : W.Point} {k : ℕ} (h : IsDLog P Q k) :
    IsDLog P Q (k + addOrderOf P) := by
  unfold IsDLog at h ⊢
  rw [scalarMul_add, scalarMul_addOrderOf, add_zero, h]

end ECDLP
