/-
Copyright (c) 2026 Zayn Blore. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zayn Blore
-/
module

public import CsdLean4.Mathlib.Geometry.Manifold.HamiltonianVectorField
public import CsdLean4.Mathlib.Geometry.Manifold.Instances.ProjectiveSpaceFubiniStudyMass
public import CsdLean4.LF4.MomentMap

/-!
# The moment map of the torus action on `ℂℙⁿ`, at manifold level

**TERM-SCOPE(Kahler)** **TERM-SCOPE(Hamiltonian)** **TERM-SCOPE(MomentMap)** — this module uses
the *restricted* senses of these words; `specs/TERMS.md` records what is backed and what is not.

**Category:** 1-Mathlib-staging in its mathematics; it consumes the corpus's `CSD.LF4.momentMap`
as the function whose manifold equation it proves.

Brick **G6** of `specs/generator-layer-scoping.md`. The torus `T^{n+1}` acts on `ℂℙⁿ` by
`p ↦ diag(e^{iθ}) • p`. This module proves the moment-map equation for that action on the
*manifold*: the velocity field of the action is the Hamiltonian vector field, for the
Fubini–Study form `fsForm`, of `2 ∑ₖ θₖ · momentMap p k`.

* `torusChartField i θ w` — the velocity in the affine chart `i`, `wⱼ ↦ i (θ_{sⱼ} − θᵢ) wⱼ`;
  `torusField θ` — the same as a family over `ℂℙⁿ`, read in the chart at each point;
* `torusUnitary θ` — `diag(e^{iθ})` as a unitary; `chartFun_torusUnitary_smul` (in the chart the
  action is the coordinatewise phase rotation); ★ `hasDerivAt_chartFun_torusUnitary` — **the field
  is the velocity of the action**: `torusChartField` is the `t`-derivative at `0` of
  `t ↦ diag(e^{itθ}) • p` read in the chart, so `torusField` is the fundamental vector field;
* `torusHamiltonian θ p = 2 ∑ₖ θₖ · momentMap p k`, its chart expression `torusChartHam = 2N/D`
  (`torusHamiltonian_chartInv`), the chart derivative (`hasFDerivAt_torusChartHam`, by the
  product and inverse rules from `hasFDerivAt_normSq_coord`), and ★ `hasMFDerivAt_torusHamiltonian`
  (the manifold derivative is the chart derivative);
* ★★ `fsModelForm_torusChartField` — the chart identity `ω_w (X_w, v) = dH_w v`, a real
  computation through `fsModelForm_apply`;
* ★★★ `torusField_isHamiltonianVectorField` — **`IsHamiltonianVectorField fsForm (torusField θ)
  (torusHamiltonian θ)`: the torus action on `ℂℙⁿ` is Hamiltonian, with `2 ∑ θₖ momentMap` as its
  Hamiltonian.** For `θ = eᵢ`: the `i`-th phase rotation is generated by `2 · momentMap · i`, on the
  symplectic manifold. This is the manifold form of the corpus's linear-level `IsPhaseHamiltonian`.

## Honest scope

⚠️ **The factor `2` is convention.** `fsChartForm` carries the `-4` of its potential
`log(1 + ‖z‖²)`; with that normalisation the generator of the phase rotation is `2 · momentMap`.
The linear-level statement (`IsPhaseHamiltonian`, `coordEnergy = ‖xᵢ‖²/2`) has its own
convention; nothing here rescales either, and the statement shows the factor.

⚠️ **A family, not a smooth section.** `torusField` is a vector-field family; its smoothness as a
section of the tangent bundle is not proved (that is brick G3's plumbing), and nothing here needs
it: `IsHamiltonianVectorField` is pointwise.

⚠️ **Not the moment polytope.** The Atiyah–Guillemin–Sternberg convexity of the image is not
touched; only the defining equation is.

⚠️ **The torus only.** The `U(n+1)` moment map `⟨z, iAz⟩/‖z‖²` for a general skew-Hermitian `A`
is not stated; the torus is what the corpus's `momentMap` is about.

References: `specs/generator-layer-scoping.md` (G6); `Geometry/Manifold/HamiltonianVectorField.lean`
(G1); `LF4/MomentMap.lean` (`momentMap`, `momentMap_mk`, `continuous_momentMap`);
`RecordLayer/CellLawForced.lean` (`IsPhaseHamiltonian`, the linear-level equation);
`Instances/ProjectiveSpaceFubiniStudyMass.lean` (`fsModelForm_apply`, `toLpCLM_apply`);
`Instances/ProjectiveSpaceUnitaryAction.lean` (`chartFun_smul_chartInv`); `specs/TERMS.md`
(moment map, Hamiltonian); `specs/future-work.md`.
-/

@[expose] public section

open scoped Manifold ContDiff LinearAlgebra.Projectivization Matrix
open Kahler DifferentialForm

noncomputable section

namespace Projectivization

variable {n : ℕ}

/-! ### Chart data -/

/-- The velocity of the torus action in the affine chart `i`: `wⱼ ↦ i (θ_{s j} − θ_i) wⱼ`. -/
def torusChartField (i : Fin (n + 1)) (θ : Fin (n + 1) → ℝ) (w : Fin n → ℂ) : Fin n → ℂ :=
  fun j => (Complex.I * ((θ (i.succAbove j) - θ i : ℝ) : ℂ)) * w j

/-- `N w = θ_i + ∑ⱼ θ_{s j} ‖wⱼ‖²`. -/
def torusChartNum (i : Fin (n + 1)) (θ : Fin (n + 1) → ℝ) (w : Fin n → ℂ) : ℝ :=
  θ i + ∑ j, θ (i.succAbove j) * ‖w j‖ ^ 2

/-- `D w = 1 + ∑ⱼ ‖wⱼ‖²`. -/
def chartDen (w : Fin n → ℂ) : ℝ := 1 + ∑ j, ‖w j‖ ^ 2

theorem chartDen_pos (w : Fin n → ℂ) : 0 < chartDen w := by
  unfold chartDen
  positivity

/-- The chart Hamiltonian `2 N / D`. -/
def torusChartHam (i : Fin (n + 1)) (θ : Fin (n + 1) → ℝ) (w : Fin n → ℂ) : ℝ :=
  2 * (torusChartNum i θ w * (chartDen w)⁻¹)

/-! ### Derivatives in the chart -/

/-- The derivative of `w ↦ ‖wⱼ‖²`. -/
def normSqCoordDeriv (j : Fin n) (w : Fin n → ℂ) : (Fin n → ℂ) →L[ℝ] ℝ :=
  (2 * (w j).re) • Complex.reCLM.comp (ContinuousLinearMap.proj j)
    + (2 * (w j).im) • Complex.imCLM.comp (ContinuousLinearMap.proj j)

theorem normSqCoordDeriv_apply (j : Fin n) (w v : Fin n → ℂ) :
    normSqCoordDeriv j w v = 2 * ((w j).re * (v j).re + (w j).im * (v j).im) := by
  simp [normSqCoordDeriv]
  ring

theorem hasFDerivAt_normSq_coord (j : Fin n) (w : Fin n → ℂ) :
    HasFDerivAt (fun w : Fin n → ℂ => ‖w j‖ ^ 2) (normSqCoordDeriv j w) w := by
  have hre : HasFDerivAt (fun w : Fin n → ℂ => (w j).re)
      (Complex.reCLM.comp (ContinuousLinearMap.proj j)) w :=
    Complex.reCLM.hasFDerivAt.comp w (hasFDerivAt_apply j w)
  have him : HasFDerivAt (fun w : Fin n → ℂ => (w j).im)
      (Complex.imCLM.comp (ContinuousLinearMap.proj j)) w :=
    Complex.imCLM.hasFDerivAt.comp w (hasFDerivAt_apply j w)
  have h := (hre.mul hre).add (him.mul him)
  refine (h.congr_fderiv ?_).congr_of_eventuallyEq (Filter.Eventually.of_forall fun w => ?_)
  · ext v
    simp [normSqCoordDeriv]
    ring
  · show ‖w j‖ ^ 2 = (w j).re * (w j).re + (w j).im * (w j).im
    rw [← Complex.normSq_eq_norm_sq, Complex.normSq_apply]

/-- The derivative of the numerator `N`. -/
def torusChartNumDeriv (i : Fin (n + 1)) (θ : Fin (n + 1) → ℝ) (w : Fin n → ℂ) :
    (Fin n → ℂ) →L[ℝ] ℝ :=
  ∑ j, θ (i.succAbove j) • normSqCoordDeriv j w

/-- The derivative of the denominator `D`. -/
def chartDenDeriv (w : Fin n → ℂ) : (Fin n → ℂ) →L[ℝ] ℝ := ∑ j, normSqCoordDeriv j w

theorem hasFDerivAt_torusChartNum (i : Fin (n + 1)) (θ : Fin (n + 1) → ℝ) (w : Fin n → ℂ) :
    HasFDerivAt (torusChartNum i θ) (torusChartNumDeriv i θ w) w := by
  unfold torusChartNum torusChartNumDeriv
  refine ((HasFDerivAt.sum (u := Finset.univ) fun j _ => (hasFDerivAt_normSq_coord j w).const_mul
    (θ (i.succAbove j))).const_add (θ i)).congr_of_eventuallyEq
    (Filter.Eventually.of_forall fun y => ?_)
  simp [Finset.sum_apply]

theorem hasFDerivAt_chartDen (w : Fin n → ℂ) : HasFDerivAt chartDen (chartDenDeriv w) w := by
  unfold chartDen chartDenDeriv
  refine ((HasFDerivAt.sum (u := Finset.univ) fun j _ => hasFDerivAt_normSq_coord j w).const_add
    1).congr_of_eventuallyEq (Filter.Eventually.of_forall fun y => ?_)
  simp [Finset.sum_apply]

/-- The derivative of the chart Hamiltonian `2 N / D`, by the product and inverse rules. -/
def torusChartHamDeriv (i : Fin (n + 1)) (θ : Fin (n + 1) → ℝ) (w : Fin n → ℂ) :
    (Fin n → ℂ) →L[ℝ] ℝ :=
  (2 : ℝ) • (torusChartNum i θ w
      • ((ContinuousLinearMap.toSpanSingleton ℝ (-(chartDen w ^ 2)⁻¹)).comp (chartDenDeriv w))
    + (chartDen w)⁻¹ • torusChartNumDeriv i θ w)

theorem hasFDerivAt_torusChartHam (i : Fin (n + 1)) (θ : Fin (n + 1) → ℝ) (w : Fin n → ℂ) :
    HasFDerivAt (torusChartHam i θ) (torusChartHamDeriv i θ w) w := by
  unfold torusChartHam torusChartHamDeriv
  have hinv : HasFDerivAt (fun w : Fin n → ℂ => (chartDen w)⁻¹)
      ((ContinuousLinearMap.toSpanSingleton ℝ (-(chartDen w ^ 2)⁻¹)).comp (chartDenDeriv w)) w :=
    (hasFDerivAt_inv (chartDen_pos w).ne').comp w (hasFDerivAt_chartDen w)
  exact ((hasFDerivAt_torusChartNum i θ w).mul hinv).const_mul 2

/-! ### The pointwise identity `ι_X ω = dH` in the chart -/

theorem torusChartHamDeriv_apply (i : Fin (n + 1)) (θ : Fin (n + 1) → ℝ) (w v : Fin n → ℂ) :
    torusChartHamDeriv i θ w v
      = 2 * (torusChartNum i θ w * (-(chartDen w ^ 2)⁻¹
            * ∑ j, 2 * ((w j).re * (v j).re + (w j).im * (v j).im))
          + (chartDen w)⁻¹ * ∑ j, θ (i.succAbove j)
            * (2 * ((w j).re * (v j).re + (w j).im * (v j).im))) := by
  simp only [torusChartHamDeriv, torusChartNumDeriv, chartDenDeriv, add_apply, smul_apply,
    ContinuousLinearMap.comp_apply, sum_apply, ContinuousLinearMap.toSpanSingleton_apply,
    normSqCoordDeriv_apply, smul_eq_mul]
  ring

/-- ★★ **The chart identity**: the Fubini–Study model form pairs the torus velocity with `v`
exactly as the derivative of the chart Hamiltonian does. -/
theorem fsModelForm_torusChartField (i : Fin (n + 1)) (θ : Fin (n + 1) → ℝ) (w v : Fin n → ℂ) :
    fsModelForm w ![torusChartField i θ w, v] = torusChartHamDeriv i θ w v := by
  rw [fsModelForm_apply, torusChartHamDeriv_apply]
  have hD : 1 + ‖toLpCLM w‖ ^ 2 = chartDen w := by
    rw [EuclideanSpace.norm_sq_eq, chartDen]
    simp only [toLpCLM_apply]
  rw [hD]
  -- the three inner products, in components
  set S1 : ℝ := ∑ j, θ (i.succAbove j) * ((w j).re * (v j).re + (w j).im * (v j).im) with hS1
  set S3 : ℝ := ∑ j, ((w j).re * (v j).re + (w j).im * (v j).im) with hS3
  set S2 : ℝ := ∑ j, θ (i.succAbove j) * ((w j).re * (w j).re + (w j).im * (w j).im) with hS2
  set S0 : ℝ := ∑ j, ((w j).re * (w j).re + (w j).im * (w j).im) with hS0
  set S4 : ℝ := ∑ j, ((w j).re * (v j).im - (w j).im * (v j).re) with hS4
  have hsub1 : S1 - θ i * S3
      = ∑ j, (θ (i.succAbove j) - θ i) * ((w j).re * (v j).re + (w j).im * (v j).im) := by
    rw [hS1, hS3, Finset.mul_sum, ← Finset.sum_sub_distrib]
    refine Finset.sum_congr rfl fun j _ => ?_
    ring
  have hsub2 : S2 - θ i * S0
      = ∑ j, (θ (i.succAbove j) - θ i) * ((w j).re * (w j).re + (w j).im * (w j).im) := by
    rw [hS2, hS0, Finset.mul_sum, ← Finset.sum_sub_distrib]
    refine Finset.sum_congr rfl fun j _ => ?_
    ring
  have e1 : (inner ℂ (toLpCLM (torusChartField i θ w)) (toLpCLM v)).im = -(S1 - θ i * S3) := by
    rw [PiLp.inner_apply, hsub1, Complex.im_sum, ← Finset.sum_neg_distrib]
    refine Finset.sum_congr rfl fun j _ => ?_
    simp only [toLpCLM_apply, RCLike.inner_apply, torusChartField, map_mul, Complex.conj_I,
      Complex.conj_ofReal, Complex.mul_im, Complex.mul_re, Complex.neg_re, Complex.neg_im,
      Complex.I_re, Complex.I_im, Complex.ofReal_re, Complex.ofReal_im, Complex.conj_re,
      Complex.conj_im]
    ring
  have e2 : inner ℂ (toLpCLM (torusChartField i θ w)) (toLpCLM w)
      = -(Complex.I * ((S2 - θ i * S0 : ℝ) : ℂ)) := by
    rw [PiLp.inner_apply, hsub2, Complex.ofReal_sum, Finset.mul_sum, ← Finset.sum_neg_distrib]
    refine Finset.sum_congr rfl fun j _ => ?_
    simp only [toLpCLM_apply, RCLike.inner_apply, torusChartField, map_mul, Complex.conj_I,
      Complex.conj_ofReal]
    apply Complex.ext
    · simp only [Complex.mul_re, Complex.mul_im, Complex.neg_re, Complex.I_re, Complex.I_im,
        Complex.ofReal_re, Complex.ofReal_im, Complex.conj_re, Complex.conj_im]
      ring
    · simp only [Complex.mul_re, Complex.mul_im, Complex.neg_im, Complex.I_re, Complex.I_im,
        Complex.ofReal_re, Complex.ofReal_im, Complex.conj_re, Complex.conj_im]
      ring
  have e3 : inner ℂ (toLpCLM w) (toLpCLM v) = ((S3 : ℝ) : ℂ) + Complex.I * ((S4 : ℝ) : ℂ) := by
    rw [PiLp.inner_apply, hS3, hS4, Complex.ofReal_sum, Complex.ofReal_sum, Finset.mul_sum,
      ← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl fun j _ => ?_
    simp only [toLpCLM_apply, RCLike.inner_apply]
    apply Complex.ext <;>
      simp only [Complex.mul_re, Complex.mul_im, Complex.add_re, Complex.add_im, Complex.I_re,
        Complex.I_im, Complex.ofReal_re, Complex.ofReal_im, Complex.conj_re, Complex.conj_im] <;>
      ring
  rw [e1, e2, e3]
  have hD0 : chartDen w = 1 + S0 := by
    rw [chartDen, hS0]
    congr 1
    refine Finset.sum_congr rfl fun j _ => ?_
    rw [← Complex.normSq_eq_norm_sq, Complex.normSq_apply]
  have hN : torusChartNum i θ w = θ i + S2 := by
    rw [torusChartNum, hS2]
    congr 1
    refine Finset.sum_congr rfl fun j _ => ?_
    rw [← Complex.normSq_eq_norm_sq, Complex.normSq_apply]
  have hsum3 : ∑ j, 2 * ((w j).re * (v j).re + (w j).im * (v j).im) = 2 * S3 := by
    rw [hS3, Finset.mul_sum]
  have hsum1 : ∑ j, θ (i.succAbove j) * (2 * ((w j).re * (v j).re + (w j).im * (v j).im))
      = 2 * S1 := by
    rw [hS1, Finset.mul_sum]
    refine Finset.sum_congr rfl fun j _ => ?_
    ring
  rw [hsum3, hsum1, hN]
  have hDpos : 0 < chartDen w := chartDen_pos w
  have hDne : chartDen w ≠ 0 := hDpos.ne'
  simp only [Complex.mul_im, Complex.neg_re, Complex.neg_im, Complex.mul_re, Complex.add_re,
    Complex.add_im, Complex.I_re, Complex.I_im, Complex.ofReal_re, Complex.ofReal_im]
  rw [hD0] at hDne ⊢
  field_simp
  ring

/-! ### The manifold statement -/

/-- The fundamental vector field of the torus action `p ↦ diag(e^{iθ}) • p` on `ℂℙⁿ`, read in
the chart at each point. -/
def torusField (θ : Fin (n + 1) → ℝ) (x : ℙ ℂ (Ambient n)) :
    TangentSpace (modelWithCornersSelf ℝ (Fin n → ℂ)) x :=
  torusChartField (idx x) θ (chartFun (idx x) x)

/-- The Hamiltonian of the torus action: `2 ∑ₖ θₖ · momentMap p k`. -/
def torusHamiltonian (θ : Fin (n + 1) → ℝ) (p : ℙ ℂ (Ambient n)) : ℝ :=
  2 * ∑ k, θ k * CSD.LF4.momentMap p k

theorem continuous_torusHamiltonian (θ : Fin (n + 1) → ℝ) :
    Continuous (torusHamiltonian (n := n) θ) :=
  continuous_const.mul (continuous_finsetSum _ fun k _ =>
    continuous_const.mul (CSD.LF4.continuous_momentMap k))

theorem torusHamiltonian_chartInv (θ : Fin (n + 1) → ℝ) (i : Fin (n + 1)) (w : Fin n → ℂ) :
    torusHamiltonian θ (chartInv i w) = torusChartHam i θ w := by
  unfold torusHamiltonian torusChartHam torusChartNum chartDen
  have hmk : ∀ k, CSD.LF4.momentMap (chartInv i w) k = ‖insertOne i w k‖ ^ 2 / ‖insertOne i w‖ ^ 2 :=
    fun k => CSD.LF4.momentMap_mk (insertOne i w) (insertOne_ne_zero i w) k
  have hden : ‖insertOne i w‖ ^ 2 = 1 + ∑ j, ‖w j‖ ^ 2 := by
    rw [CSD.LF4.euclidean_norm_sq_eq_sum, Fin.sum_univ_succAbove _ i]
    simp [insertOne_apply_same, insertOne_apply_succAbove]
  simp_rw [hmk, hden]
  rw [Fin.sum_univ_succAbove _ i]
  simp only [insertOne_apply_same, insertOne_apply_succAbove, norm_one, one_pow, div_eq_mul_inv,
    ← mul_assoc]
  rw [← Finset.sum_mul]
  ring

theorem hasMFDerivAt_torusHamiltonian (θ : Fin (n + 1) → ℝ) (x : ℙ ℂ (Ambient n)) :
    HasMFDerivAt (modelWithCornersSelf ℝ (Fin n → ℂ)) (modelWithCornersSelf ℝ ℝ)
      (torusHamiltonian θ) x (torusChartHamDeriv (idx x) θ (chartFun (idx x) x)) := by
  refine ⟨(continuous_torusHamiltonian θ).continuousAt, ?_⟩
  have hw : writtenInExtChartAt (modelWithCornersSelf ℝ (Fin n → ℂ)) (modelWithCornersSelf ℝ ℝ) x
      (torusHamiltonian θ) = torusChartHam (idx x) θ := by
    funext w
    simp only [writtenInExtChartAt, Function.comp, extChartAt_model_space_eq_id,
      PartialEquiv.refl_coe, id, extChartAt_coe_symm, modelWithCornersSelf_coe_symm]
    exact torusHamiltonian_chartInv θ (idx x) w
  rw [hw]
  exact (hasFDerivAt_torusChartHam (idx x) θ (chartFun (idx x) x)).hasFDerivWithinAt

/-- ★★★ **The torus action on `ℂℙⁿ` is Hamiltonian, with `2 ∑ θₖ momentMap` as its
Hamiltonian**: the moment-map equation `ι_X ω_FS = dH` on the manifold. -/
theorem torusField_isHamiltonianVectorField (θ : Fin (n + 1) → ℝ) :
    IsHamiltonianVectorField (fun x => fsForm x) (torusField θ) (torusHamiltonian θ) := by
  intro x v
  rw [(hasMFDerivAt_torusHamiltonian θ x).mfderiv]
  exact fsModelForm_torusChartField (idx x) θ (chartFun (idx x) x) v

/-! ### The torus action, and its velocity -/

/-- The phase matrix `diag(e^{iθₖ})` as a unitary. -/
def torusUnitary (θ : Fin (n + 1) → ℝ) : Matrix.unitaryGroup (Fin (n + 1)) ℂ :=
  ⟨Matrix.diagonal fun k => Complex.exp ((θ k : ℂ) * Complex.I), by
    rw [Matrix.mem_unitaryGroup_iff', Matrix.star_eq_conjTranspose, Matrix.diagonal_conjTranspose,
      Matrix.diagonal_mul_diagonal, ← Matrix.diagonal_one]
    congr 1
    funext k
    have h1 : Complex.normSq (Complex.exp ((θ k : ℂ) * Complex.I)) = 1 := by
      rw [Complex.normSq_eq_norm_sq, Complex.norm_exp_ofReal_mul_I, one_pow]
    rw [Pi.star_apply, Complex.star_def, ← Complex.normSq_eq_conj_mul_self, h1, Complex.ofReal_one]⟩

theorem torusUnitary_val (θ : Fin (n + 1) → ℝ) :
    (torusUnitary θ).val = Matrix.diagonal fun k => Complex.exp ((θ k : ℂ) * Complex.I) := rfl

/-- The torus action in the chart at `i`, coordinatewise. -/
theorem chartFun_torusUnitary_smul (θ : Fin (n + 1) → ℝ) (i : Fin (n + 1)) (w : Fin n → ℂ) :
    chartFun i (torusUnitary θ • chartInv i w)
      = fun j => Complex.exp ((θ (i.succAbove j) : ℂ) * Complex.I) * w j
          / Complex.exp ((θ i : ℂ) * Complex.I) := by
  rw [chartFun_smul_chartInv]
  funext j
  show ((torusUnitary θ).val *ᵥ (insertOne i w).ofLp) (i.succAbove j)
      / ((torusUnitary θ).val *ᵥ (insertOne i w).ofLp) i = _
  rw [torusUnitary_val, Matrix.mulVec_diagonal, Matrix.mulVec_diagonal, insertOne_apply_same,
    insertOne_apply_succAbove, mul_one]

/-- ★ **The field is the velocity of the action**: at every chart point, `torusChartField` is the
`t`-derivative at `0` of `t ↦ diag(e^{itθ}) • p`, read in the chart. -/
theorem hasDerivAt_chartFun_torusUnitary (θ : Fin (n + 1) → ℝ) (i : Fin (n + 1)) (w : Fin n → ℂ) :
    HasDerivAt (fun t : ℝ => chartFun i (torusUnitary (t • θ) • chartInv i w))
      (torusChartField i θ w) 0 := by
  simp_rw [chartFun_torusUnitary_smul]
  refine hasDerivAt_pi.2 fun j => ?_
  show HasDerivAt (fun t : ℝ => Complex.exp ((((t • θ) (i.succAbove j) : ℝ) : ℂ) * Complex.I) * w j
    / Complex.exp ((((t • θ) i : ℝ) : ℂ) * Complex.I)) (torusChartField i θ w j) 0
  have hlin : ∀ c : Fin (n + 1), HasDerivAt (fun t : ℝ => (((t • θ) c : ℝ) : ℂ) * Complex.I)
      ((θ c : ℂ) * Complex.I) 0 := by
    intro c
    have h0 : HasDerivAt (fun t : ℝ => ((t • θ) c : ℝ)) (θ c) 0 := by
      simp only [Pi.smul_apply, smul_eq_mul]
      simpa using (hasDerivAt_id (0 : ℝ)).mul_const (θ c)
    have h1 := Complex.ofRealCLM.hasFDerivAt.comp_hasDerivAt (0 : ℝ) h0
    simpa using h1.mul_const Complex.I
  have hnum := ((hlin (i.succAbove j)).cexp).mul_const (w j)
  have hden := (hlin i).cexp
  have hne : Complex.exp ((((0 : ℝ) • θ) i : ℝ) * Complex.I) ≠ 0 := Complex.exp_ne_zero _
  refine (hnum.div hden hne).congr_deriv ?_
  simp [torusChartField]
  ring

end Projectivization
