/-
Copyright (c) 2026 Zayn Blore. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zayn Blore
-/
module

public import CsdLean4.Mathlib.Geometry.Manifold.HamiltonianVectorField
public import CsdLean4.Mathlib.Geometry.Manifold.Instances.ProjectiveSpaceFubiniStudyMass
public import CsdLean4.Mathlib.LinearAlgebra.Projectivization.MomentMap
public import Mathlib.Analysis.Convex.StdSimplex

/-!
# The moment map of the torus action on `ℂℙⁿ`, at manifold level

**TERM-SCOPE(Kahler)** **TERM-SCOPE(Hamiltonian)** **TERM-SCOPE(MomentMap)** **TERM-SCOPE(Liouville)**
— this module uses the *restricted* senses of these words; the source repository's terms register records what is backed
and what is not.

**Category:** 1-Mathlib (CSD-free; the torus moment map of `ℂℙⁿ`).

The torus `T^{n+1}`
acts on `ℂℙⁿ` by `p ↦ diag(e^{iθ}) • p`. This module proves the moment-map equation for that
action on the *manifold*: the velocity field of the action is the Hamiltonian vector field, for
the Fubini–Study form `fsForm`, of `2 ∑ₖ θₖ · momentMap p k` — then its uniqueness, its image, and
the invariance of the Fubini–Study volume under the flow it generates.

* `torusChartField i θ w` — the velocity in the affine chart `i`, `wⱼ ↦ i (θ_{sⱼ} − θᵢ) wⱼ`;
  `torusField θ` — the same as a family over `ℂℙⁿ`, read in the chart at each point;
* `torusUnitary θ` — `diag(e^{iθ})` as a unitary; `chartFun_torusUnitary_smul` (in the chart the
  action is the coordinatewise phase rotation); ★ `hasDerivAt_chartFun_torusUnitary` — **the field
  is the velocity of the action**: `torusChartField` is the `t`-derivative at `0` of
  `t ↦ diag(e^{itθ}) • p` read in the chart, and ★★★ `isMIntegralCurve_torusUnitary_smul` — the
  orbit `t ↦ diag(e^{itθ}) • p` is a global integral curve of `torusField θ`, so `torusField` is the
  fundamental vector field;
* `torusHamiltonian θ p = 2 ∑ₖ θₖ · momentMap p k`, its chart expression `torusChartHam = 2N/D`
  (`torusHamiltonian_chartInv`), the chart derivative (`hasFDerivAt_torusChartHam`, by the
  product and inverse rules from `hasFDerivAt_normSq_coord`), and ★ `hasMFDerivAt_torusHamiltonian`
  (the manifold derivative is the chart derivative);
* ★★ `fsModelForm_torusChartField` — the chart identity `ω_w (X_w, v) = dH_w v`, a real
  computation through `fsModelForm_apply`;
* ★★★ `torusField_isHamiltonianVectorField` — **`IsHamiltonianVectorField fsForm (torusField θ)
  (torusHamiltonian θ)`: the torus action on `ℂℙⁿ` is Hamiltonian, with `2 ∑ θₖ momentMap` as its
  Hamiltonian.** For `θ = eᵢ`: the `i`-th phase rotation is generated by `2 · momentMap · i`, on the
  symplectic manifold. This is the manifold form of the linear-level statement that phase rotation is Hamiltonian;
* **G8, uniqueness.** `momentMap_origin_of_ne`, `torusHamiltonian_single`,
  ★★ `eq_add_const_of_isHamiltonianVectorField` — **a Hamiltonian is unique up to a constant on
  `ℂℙⁿ`**: two differentiable Hamiltonians of the same field for the same 2-form family differ by a
  constant. No connectedness lemma: every affine chart image is all of `ℂⁿ`
  (`is_const_of_fderiv_eq_zero`), and `[1 : ⋯ : 1]` (`allOnes`) lies in every chart; and
  ★★★ `eq_torusHamiltonian_of_nonneg_of_sum` — **the normalisation pins the constant**: a
  non-negative family of Hamiltonians for the phase fields summing to `2` is `2 · momentMap`. This
  is the standard symplectic argument, formalised;
* **G9, the image.** `momentMap_mem_stdSimplex`, `sqrtVec` (the vector `(√t₀, …, √tₙ)`),
  `momentMap_mk_sqrtVec`, and ★★ `range_momentMap` — **the image of the moment map is exactly the
  standard simplex** `stdSimplex ℝ (Fin (n + 1))`: `⊆` is the normalisation, `⊇` the ray of
  `(√t₀, …, √tₙ)`;
* **G10, the flow.** `torusUnitary_zero`, `torusUnitary_add`, `torusUnitary_add_smul` (the
  one-parameter group law of `t ↦ diag(e^{itθ})`), and ★ `fsVolume_map_torusUnitary_smul` /
  `measurePreserving_torusUnitary_smul` — **every time-`t` map of the torus flow preserves the
  Fubini–Study volume `fsVolume n`**, a corollary of the unitary invariance `fsVolume_map_smul`.

## Honest scope

⚠️ **G8 is about the map the action has.** It says that the map the torus action *has* is the
`momentMap`; whether some dynamics *generates* the torus action is a different question, which
nothing here addresses.

⚠️ **The factor `2` is convention.** `fsChartForm` carries the `-4` of its potential
`log(1 + ‖z‖²)`; with that normalisation the generator of the phase rotation is `2 · momentMap`.
The linear-level statement (`IsPhaseHamiltonian`, `coordEnergy = ‖xᵢ‖²/2`) has its own
convention; nothing here rescales either, and the statement shows the factor.

⚠️ **A family, not a smooth section.** `torusField` is a vector-field family; its smoothness as a
section of the tangent bundle is not proved (that is brick G3's plumbing), and nothing here needs
it: `IsHamiltonianVectorField` is pointwise.

⚠️ **The polytope by computation, not by convexity.** `range_momentMap` (G9) exhibits the image
as the simplex for *this* action; the Atiyah–Guillemin–Sternberg convexity theorem is neither used
nor proved.

⚠️ **Liouville for one flow only.** `fsVolume_map_torusUnitary_smul` (G10) is unitary invariance
specialised to `diag(e^{iθ})`. It is not a manifold-level Liouville theorem for Hamiltonian flows
(that is `HamiltonianFlowVolume.lean`'s job).

⚠️ **The torus here; the general generator in `ProjectiveSpaceSchrodingerFlow.lean` (G13).** For a
general Hermitian `H` the flow `exp(-itH) • p` is Hamiltonian with Hamiltonian `-2 ⟨H⟩`
(`schrodingerField_isHamiltonianVectorField`), and the torus is its diagonal case
(`schrodingerHamiltonian_neg_diagonal`); the torus is what `momentMap` is about.

**Provenance and references.** The generator-layer plan (G6, G8–G10);
`Geometry/Manifold/HamiltonianVectorField.lean`
(G1); `LinearAlgebra/Projectivization/MomentMap.lean` (`momentMap`, `momentMap_mk`, `continuous_momentMap`);
`RecordLayer/CellLawForced.lean` (`IsPhaseHamiltonian`, the linear-level equation);
`Instances/ProjectiveSpaceFubiniStudyMass.lean` (`fsModelForm_apply`, `toLpCLM_apply`);
`Instances/ProjectiveSpaceUnitaryAction.lean` (`chartFun_smul_chartInv`);
`Instances/ProjectiveSpaceFubiniStudyVolume.lean` (`fsVolume`, `fsVolume_map_smul`);
`Mathlib/Analysis/Convex/StdSimplex.lean` (`stdSimplex`); the terms register (moment map,
Hamiltonian, Liouville); the programme's posits (Posits 1 and 3); the completed-work ledger.
-/

@[expose] public section

open scoped Manifold ContDiff LinearAlgebra.Projectivization Matrix
open Kahler DifferentialForm MeasureTheory

noncomputable section

namespace Projectivization

variable {n : ℕ}

/-! ### Chart data -/

/-- The velocity of the torus action in the affine chart `i`: `wⱼ ↦ i (θ_{s j} − θ_i) wⱼ`. -/
def torusChartField (i : Fin (n + 1)) (θ : Fin (n + 1) → ℝ) (w : Fin n → ℂ) : Fin n → ℂ :=
  fun j => (Complex.I * ((θ (i.succAbove j) - θ i : ℝ) : ℂ)) * w j

/-- `N w = θ_i + ∑ⱼ θ_{s j} ‖wⱼ‖²`. -/
def torusChartNum (i : Fin (n + 1)) (θ : Fin (n + 1) → ℝ) (w : Fin n → ℂ) : ℝ :=
  θ i + ∑ j, θ (i.succAbove j) * ‖w j‖ ^ 2

/-- `D w = 1 + ∑ⱼ ‖wⱼ‖²`. -/
def chartDen (w : Fin n → ℂ) : ℝ := 1 + ∑ j, ‖w j‖ ^ 2

theorem chartDen_pos (w : Fin n → ℂ) : 0 < chartDen w := by
  unfold chartDen
  positivity

/-- The chart Hamiltonian `2 N / D`. -/
def torusChartHam (i : Fin (n + 1)) (θ : Fin (n + 1) → ℝ) (w : Fin n → ℂ) : ℝ :=
  2 * (torusChartNum i θ w * (chartDen w)⁻¹)

/-! ### Derivatives in the chart -/

/-- The derivative of `w ↦ ‖wⱼ‖²`. -/
def normSqCoordDeriv (j : Fin n) (w : Fin n → ℂ) : (Fin n → ℂ) →L[ℝ] ℝ :=
  (2 * (w j).re) • Complex.reCLM.comp (ContinuousLinearMap.proj j)
    + (2 * (w j).im) • Complex.imCLM.comp (ContinuousLinearMap.proj j)

theorem normSqCoordDeriv_apply (j : Fin n) (w v : Fin n → ℂ) :
    normSqCoordDeriv j w v = 2 * ((w j).re * (v j).re + (w j).im * (v j).im) := by
  simp [normSqCoordDeriv]
  ring

theorem hasFDerivAt_normSq_coord (j : Fin n) (w : Fin n → ℂ) :
    HasFDerivAt (fun w : Fin n → ℂ => ‖w j‖ ^ 2) (normSqCoordDeriv j w) w := by
  have hre : HasFDerivAt (fun w : Fin n → ℂ => (w j).re)
      (Complex.reCLM.comp (ContinuousLinearMap.proj j)) w :=
    Complex.reCLM.hasFDerivAt.comp w (hasFDerivAt_apply j w)
  have him : HasFDerivAt (fun w : Fin n → ℂ => (w j).im)
      (Complex.imCLM.comp (ContinuousLinearMap.proj j)) w :=
    Complex.imCLM.hasFDerivAt.comp w (hasFDerivAt_apply j w)
  have h := (hre.mul hre).add (him.mul him)
  refine (h.congr_fderiv ?_).congr_of_eventuallyEq (Filter.Eventually.of_forall fun w => ?_)
  · ext v
    simp [normSqCoordDeriv]
    ring
  · show ‖w j‖ ^ 2 = (w j).re * (w j).re + (w j).im * (w j).im
    rw [← Complex.normSq_eq_norm_sq, Complex.normSq_apply]

/-- The derivative of the numerator `N`. -/
def torusChartNumDeriv (i : Fin (n + 1)) (θ : Fin (n + 1) → ℝ) (w : Fin n → ℂ) :
    (Fin n → ℂ) →L[ℝ] ℝ :=
  ∑ j, θ (i.succAbove j) • normSqCoordDeriv j w

/-- The derivative of the denominator `D`. -/
def chartDenDeriv (w : Fin n → ℂ) : (Fin n → ℂ) →L[ℝ] ℝ := ∑ j, normSqCoordDeriv j w

theorem hasFDerivAt_torusChartNum (i : Fin (n + 1)) (θ : Fin (n + 1) → ℝ) (w : Fin n → ℂ) :
    HasFDerivAt (torusChartNum i θ) (torusChartNumDeriv i θ w) w := by
  unfold torusChartNum torusChartNumDeriv
  refine ((HasFDerivAt.sum (u := Finset.univ) fun j _ => (hasFDerivAt_normSq_coord j w).const_mul
    (θ (i.succAbove j))).const_add (θ i)).congr_of_eventuallyEq
    (Filter.Eventually.of_forall fun y => ?_)
  simp [Finset.sum_apply]

theorem hasFDerivAt_chartDen (w : Fin n → ℂ) : HasFDerivAt chartDen (chartDenDeriv w) w := by
  unfold chartDen chartDenDeriv
  refine ((HasFDerivAt.sum (u := Finset.univ) fun j _ => hasFDerivAt_normSq_coord j w).const_add
    1).congr_of_eventuallyEq (Filter.Eventually.of_forall fun y => ?_)
  simp [Finset.sum_apply]

/-- The derivative of the chart Hamiltonian `2 N / D`, by the product and inverse rules. -/
def torusChartHamDeriv (i : Fin (n + 1)) (θ : Fin (n + 1) → ℝ) (w : Fin n → ℂ) :
    (Fin n → ℂ) →L[ℝ] ℝ :=
  (2 : ℝ) • (torusChartNum i θ w
      • ((ContinuousLinearMap.toSpanSingleton ℝ (-(chartDen w ^ 2)⁻¹)).comp (chartDenDeriv w))
    + (chartDen w)⁻¹ • torusChartNumDeriv i θ w)

theorem hasFDerivAt_torusChartHam (i : Fin (n + 1)) (θ : Fin (n + 1) → ℝ) (w : Fin n → ℂ) :
    HasFDerivAt (torusChartHam i θ) (torusChartHamDeriv i θ w) w := by
  unfold torusChartHam torusChartHamDeriv
  have hinv : HasFDerivAt (fun w : Fin n → ℂ => (chartDen w)⁻¹)
      ((ContinuousLinearMap.toSpanSingleton ℝ (-(chartDen w ^ 2)⁻¹)).comp (chartDenDeriv w)) w :=
    (hasFDerivAt_inv (chartDen_pos w).ne').comp w (hasFDerivAt_chartDen w)
  exact ((hasFDerivAt_torusChartNum i θ w).mul hinv).const_mul 2

/-! ### The pointwise identity `ι_X ω = dH` in the chart -/

theorem torusChartHamDeriv_apply (i : Fin (n + 1)) (θ : Fin (n + 1) → ℝ) (w v : Fin n → ℂ) :
    torusChartHamDeriv i θ w v
      = 2 * (torusChartNum i θ w * (-(chartDen w ^ 2)⁻¹
            * ∑ j, 2 * ((w j).re * (v j).re + (w j).im * (v j).im))
          + (chartDen w)⁻¹ * ∑ j, θ (i.succAbove j)
            * (2 * ((w j).re * (v j).re + (w j).im * (v j).im))) := by
  simp only [torusChartHamDeriv, torusChartNumDeriv, chartDenDeriv, add_apply, smul_apply,
    ContinuousLinearMap.comp_apply, sum_apply, ContinuousLinearMap.toSpanSingleton_apply,
    normSqCoordDeriv_apply, smul_eq_mul]
  ring

/-- ★★ **The chart identity**: the Fubini–Study model form pairs the torus velocity with `v`
exactly as the derivative of the chart Hamiltonian does. -/
theorem fsModelForm_torusChartField (i : Fin (n + 1)) (θ : Fin (n + 1) → ℝ) (w v : Fin n → ℂ) :
    fsModelForm w ![torusChartField i θ w, v] = torusChartHamDeriv i θ w v := by
  rw [fsModelForm_apply, torusChartHamDeriv_apply]
  have hD : 1 + ‖toLpCLM w‖ ^ 2 = chartDen w := by
    rw [EuclideanSpace.norm_sq_eq, chartDen]
    simp only [toLpCLM_apply]
  rw [hD]
  -- the three inner products, in components
  set S1 : ℝ := ∑ j, θ (i.succAbove j) * ((w j).re * (v j).re + (w j).im * (v j).im) with hS1
  set S3 : ℝ := ∑ j, ((w j).re * (v j).re + (w j).im * (v j).im) with hS3
  set S2 : ℝ := ∑ j, θ (i.succAbove j) * ((w j).re * (w j).re + (w j).im * (w j).im) with hS2
  set S0 : ℝ := ∑ j, ((w j).re * (w j).re + (w j).im * (w j).im) with hS0
  set S4 : ℝ := ∑ j, ((w j).re * (v j).im - (w j).im * (v j).re) with hS4
  have hsub1 : S1 - θ i * S3
      = ∑ j, (θ (i.succAbove j) - θ i) * ((w j).re * (v j).re + (w j).im * (v j).im) := by
    rw [hS1, hS3, Finset.mul_sum, ← Finset.sum_sub_distrib]
    refine Finset.sum_congr rfl fun j _ => ?_
    ring
  have hsub2 : S2 - θ i * S0
      = ∑ j, (θ (i.succAbove j) - θ i) * ((w j).re * (w j).re + (w j).im * (w j).im) := by
    rw [hS2, hS0, Finset.mul_sum, ← Finset.sum_sub_distrib]
    refine Finset.sum_congr rfl fun j _ => ?_
    ring
  have e1 : (inner ℂ (toLpCLM (torusChartField i θ w)) (toLpCLM v)).im = -(S1 - θ i * S3) := by
    rw [PiLp.inner_apply, hsub1, Complex.im_sum, ← Finset.sum_neg_distrib]
    refine Finset.sum_congr rfl fun j _ => ?_
    simp only [toLpCLM_apply, RCLike.inner_apply, torusChartField, map_mul, Complex.conj_I,
      Complex.conj_ofReal, Complex.mul_im, Complex.mul_re, Complex.neg_re, Complex.neg_im,
      Complex.I_re, Complex.I_im, Complex.ofReal_re, Complex.ofReal_im, Complex.conj_re,
      Complex.conj_im]
    ring
  have e2 : inner ℂ (toLpCLM (torusChartField i θ w)) (toLpCLM w)
      = -(Complex.I * ((S2 - θ i * S0 : ℝ) : ℂ)) := by
    rw [PiLp.inner_apply, hsub2, Complex.ofReal_sum, Finset.mul_sum, ← Finset.sum_neg_distrib]
    refine Finset.sum_congr rfl fun j _ => ?_
    simp only [toLpCLM_apply, RCLike.inner_apply, torusChartField, map_mul, Complex.conj_I,
      Complex.conj_ofReal]
    apply Complex.ext
    · simp only [Complex.mul_re, Complex.mul_im, Complex.neg_re, Complex.I_re, Complex.I_im,
        Complex.ofReal_re, Complex.ofReal_im, Complex.conj_re, Complex.conj_im]
      ring
    · simp only [Complex.mul_re, Complex.mul_im, Complex.neg_im, Complex.I_re, Complex.I_im,
        Complex.ofReal_re, Complex.ofReal_im, Complex.conj_re, Complex.conj_im]
      ring
  have e3 : inner ℂ (toLpCLM w) (toLpCLM v) = ((S3 : ℝ) : ℂ) + Complex.I * ((S4 : ℝ) : ℂ) := by
    rw [PiLp.inner_apply, hS3, hS4, Complex.ofReal_sum, Complex.ofReal_sum, Finset.mul_sum,
      ← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl fun j _ => ?_
    simp only [toLpCLM_apply, RCLike.inner_apply]
    apply Complex.ext <;>
      simp only [Complex.mul_re, Complex.mul_im, Complex.add_re, Complex.add_im, Complex.I_re,
        Complex.I_im, Complex.ofReal_re, Complex.ofReal_im, Complex.conj_re, Complex.conj_im] <;>
      ring
  rw [e1, e2, e3]
  have hD0 : chartDen w = 1 + S0 := by
    rw [chartDen, hS0]
    congr 1
    refine Finset.sum_congr rfl fun j _ => ?_
    rw [← Complex.normSq_eq_norm_sq, Complex.normSq_apply]
  have hN : torusChartNum i θ w = θ i + S2 := by
    rw [torusChartNum, hS2]
    congr 1
    refine Finset.sum_congr rfl fun j _ => ?_
    rw [← Complex.normSq_eq_norm_sq, Complex.normSq_apply]
  have hsum3 : ∑ j, 2 * ((w j).re * (v j).re + (w j).im * (v j).im) = 2 * S3 := by
    rw [hS3, Finset.mul_sum]
  have hsum1 : ∑ j, θ (i.succAbove j) * (2 * ((w j).re * (v j).re + (w j).im * (v j).im))
      = 2 * S1 := by
    rw [hS1, Finset.mul_sum]
    refine Finset.sum_congr rfl fun j _ => ?_
    ring
  rw [hsum3, hsum1, hN]
  have hDpos : 0 < chartDen w := chartDen_pos w
  have hDne : chartDen w ≠ 0 := hDpos.ne'
  simp only [Complex.mul_im, Complex.neg_re, Complex.neg_im, Complex.mul_re, Complex.add_re,
    Complex.add_im, Complex.I_re, Complex.I_im, Complex.ofReal_re, Complex.ofReal_im]
  rw [hD0] at hDne ⊢
  field_simp
  ring

/-! ### The manifold statement -/

/-- The fundamental vector field of the torus action `p ↦ diag(e^{iθ}) • p` on `ℂℙⁿ`, read in
the chart at each point. -/
def torusField (θ : Fin (n + 1) → ℝ) (x : ℙ ℂ (Ambient n)) :
    TangentSpace (modelWithCornersSelf ℝ (Fin n → ℂ)) x :=
  torusChartField (idx x) θ (chartFun (idx x) x)

/-- The Hamiltonian of the torus action: `2 ∑ₖ θₖ · momentMap p k`. -/
def torusHamiltonian (θ : Fin (n + 1) → ℝ) (p : ℙ ℂ (Ambient n)) : ℝ :=
  2 * ∑ k, θ k * momentMap p k

theorem continuous_torusHamiltonian (θ : Fin (n + 1) → ℝ) :
    Continuous (torusHamiltonian (n := n) θ) :=
  continuous_const.mul (continuous_finsetSum _ fun k _ =>
    continuous_const.mul (continuous_momentMap k))

theorem torusHamiltonian_chartInv (θ : Fin (n + 1) → ℝ) (i : Fin (n + 1)) (w : Fin n → ℂ) :
    torusHamiltonian θ (chartInv i w) = torusChartHam i θ w := by
  unfold torusHamiltonian torusChartHam torusChartNum chartDen
  have hmk : ∀ k, momentMap (chartInv i w) k = ‖insertOne i w k‖ ^ 2 / ‖insertOne i w‖ ^ 2 :=
    fun k => momentMap_mk (insertOne i w) (insertOne_ne_zero i w) k
  have hden : ‖insertOne i w‖ ^ 2 = 1 + ∑ j, ‖w j‖ ^ 2 := by
    rw [EuclideanSpace.norm_sq_eq, Fin.sum_univ_succAbove _ i]
    simp [insertOne_apply_same, insertOne_apply_succAbove]
  simp_rw [hmk, hden]
  rw [Fin.sum_univ_succAbove _ i]
  simp only [insertOne_apply_same, insertOne_apply_succAbove, norm_one, one_pow, div_eq_mul_inv,
    ← mul_assoc]
  rw [← Finset.sum_mul]
  ring

theorem hasMFDerivAt_torusHamiltonian (θ : Fin (n + 1) → ℝ) (x : ℙ ℂ (Ambient n)) :
    HasMFDerivAt (modelWithCornersSelf ℝ (Fin n → ℂ)) (modelWithCornersSelf ℝ ℝ)
      (torusHamiltonian θ) x (torusChartHamDeriv (idx x) θ (chartFun (idx x) x)) := by
  refine ⟨(continuous_torusHamiltonian θ).continuousAt, ?_⟩
  have hw : writtenInExtChartAt (modelWithCornersSelf ℝ (Fin n → ℂ)) (modelWithCornersSelf ℝ ℝ) x
      (torusHamiltonian θ) = torusChartHam (idx x) θ := by
    funext w
    simp only [writtenInExtChartAt, Function.comp, extChartAt_model_space_eq_id,
      PartialEquiv.refl_coe, id, extChartAt_coe_symm, modelWithCornersSelf_coe_symm]
    exact torusHamiltonian_chartInv θ (idx x) w
  rw [hw]
  exact (hasFDerivAt_torusChartHam (idx x) θ (chartFun (idx x) x)).hasFDerivWithinAt

/-- ★★★ **The torus action on `ℂℙⁿ` is Hamiltonian, with `2 ∑ θₖ momentMap` as its
Hamiltonian**: the moment-map equation `ι_X ω_FS = dH` on the manifold. -/
theorem torusField_isHamiltonianVectorField (θ : Fin (n + 1) → ℝ) :
    IsHamiltonianVectorField (fun x => fsForm x) (torusField θ) (torusHamiltonian θ) := by
  intro x v
  rw [(hasMFDerivAt_torusHamiltonian θ x).mfderiv]
  exact fsModelForm_torusChartField (idx x) θ (chartFun (idx x) x) v

/-! ### The torus action, and its velocity -/

/-- The phase matrix `diag(e^{iθₖ})` as a unitary. -/
def torusUnitary (θ : Fin (n + 1) → ℝ) : Matrix.unitaryGroup (Fin (n + 1)) ℂ :=
  ⟨Matrix.diagonal fun k => Complex.exp ((θ k : ℂ) * Complex.I), by
    rw [Matrix.mem_unitaryGroup_iff', Matrix.star_eq_conjTranspose, Matrix.diagonal_conjTranspose,
      Matrix.diagonal_mul_diagonal, ← Matrix.diagonal_one]
    congr 1
    funext k
    have h1 : Complex.normSq (Complex.exp ((θ k : ℂ) * Complex.I)) = 1 := by
      rw [Complex.normSq_eq_norm_sq, Complex.norm_exp_ofReal_mul_I, one_pow]
    rw [Pi.star_apply, Complex.star_def, ← Complex.normSq_eq_conj_mul_self, h1, Complex.ofReal_one]⟩

theorem torusUnitary_val (θ : Fin (n + 1) → ℝ) :
    (torusUnitary θ).val = Matrix.diagonal fun k => Complex.exp ((θ k : ℂ) * Complex.I) := rfl

/-- The torus action in the chart at `i`, coordinatewise. -/
theorem chartFun_torusUnitary_smul (θ : Fin (n + 1) → ℝ) (i : Fin (n + 1)) (w : Fin n → ℂ) :
    chartFun i (torusUnitary θ • chartInv i w)
      = fun j => Complex.exp ((θ (i.succAbove j) : ℂ) * Complex.I) * w j
          / Complex.exp ((θ i : ℂ) * Complex.I) := by
  rw [chartFun_smul_chartInv]
  funext j
  show ((torusUnitary θ).val *ᵥ (insertOne i w).ofLp) (i.succAbove j)
      / ((torusUnitary θ).val *ᵥ (insertOne i w).ofLp) i = _
  rw [torusUnitary_val, Matrix.mulVec_diagonal, Matrix.mulVec_diagonal, insertOne_apply_same,
    insertOne_apply_succAbove, mul_one]

/-- ★ **The field is the velocity of the action**: at every chart point, `torusChartField` is the
`t`-derivative at `0` of `t ↦ diag(e^{itθ}) • p`, read in the chart. -/
theorem hasDerivAt_chartFun_torusUnitary (θ : Fin (n + 1) → ℝ) (i : Fin (n + 1)) (w : Fin n → ℂ) :
    HasDerivAt (fun t : ℝ => chartFun i (torusUnitary (t • θ) • chartInv i w))
      (torusChartField i θ w) 0 := by
  simp_rw [chartFun_torusUnitary_smul]
  refine hasDerivAt_pi.2 fun j => ?_
  show HasDerivAt (fun t : ℝ => Complex.exp ((((t • θ) (i.succAbove j) : ℝ) : ℂ) * Complex.I) * w j
    / Complex.exp ((((t • θ) i : ℝ) : ℂ) * Complex.I)) (torusChartField i θ w j) 0
  have hlin : ∀ c : Fin (n + 1), HasDerivAt (fun t : ℝ => (((t • θ) c : ℝ) : ℂ) * Complex.I)
      ((θ c : ℂ) * Complex.I) 0 := by
    intro c
    have h0 : HasDerivAt (fun t : ℝ => ((t • θ) c : ℝ)) (θ c) 0 := by
      simp only [Pi.smul_apply, smul_eq_mul]
      simpa using (hasDerivAt_id (0 : ℝ)).mul_const (θ c)
    have h1 := Complex.ofRealCLM.hasFDerivAt.comp_hasDerivAt (0 : ℝ) h0
    simpa using h1.mul_const Complex.I
  have hnum := ((hlin (i.succAbove j)).cexp).mul_const (w j)
  have hden := (hlin i).cexp
  have hne : Complex.exp ((((0 : ℝ) • θ) i : ℝ) * Complex.I) ≠ 0 := Complex.exp_ne_zero _
  refine (hnum.div hden hne).congr_deriv ?_
  simp [torusChartField]
  ring

/-! ### Uniqueness: the normalisation pins the moment map (G8) -/

theorem chartAt_origin_target (i : Fin (n + 1)) :
    (chartAt (Fin n → ℂ) (origin i)).target = Set.univ := by
  show (chartAtIdx (idx (origin i))).target = Set.univ
  rw [idx_origin]
  rfl

/-- The point `[1 : 1 : ⋯ : 1]`, which lies in every affine chart. -/
def allOnes (n : ℕ) : Ambient n := WithLp.toLp 2 fun _ => 1

theorem allOnes_ne_zero (n : ℕ) : allOnes n ≠ 0 := by
  intro h
  have := congrArg (fun v : Ambient n => v.ofLp 0) h
  simp [allOnes] at this

theorem mk_allOnes_mem_chartSource (i : Fin (n + 1)) :
    Projectivization.mk ℂ (allOnes n) (allOnes_ne_zero n) ∈ chartSource i :=
  (mem_chartSource_mk i _ _).2 (by
    show (1 : ℂ) ≠ 0
    exact one_ne_zero)

/-- The `k`-th moment-map coordinate vanishes at the `j`-th chart origin, `k ≠ j`. -/
theorem momentMap_origin_of_ne (j k : Fin (n + 1)) (h : k ≠ j) :
    momentMap (origin j) k = 0 := by
  obtain ⟨a, -, hk⟩ := rep_origin j
  obtain ⟨m, hm⟩ := Fin.exists_succAbove_eq h
  unfold momentMap
  rw [hk k, ← hm, insertOne_apply_succAbove]
  simp

theorem torusHamiltonian_single (k : Fin (n + 1)) (p : ℙ ℂ (Ambient n)) :
    torusHamiltonian (Pi.single k (1 : ℝ)) p = 2 * momentMap p k := by
  unfold torusHamiltonian
  simp only [Pi.single_apply, ite_mul, one_mul, zero_mul, Finset.sum_ite_eq', Finset.mem_univ,
    if_true]

theorem mdifferentiable_torusHamiltonian (θ : Fin (n + 1) → ℝ) :
    MDifferentiable (modelWithCornersSelf ℝ (Fin n → ℂ)) (modelWithCornersSelf ℝ ℝ)
      (torusHamiltonian (n := n) θ) :=
  fun x => (hasMFDerivAt_torusHamiltonian θ x).mdifferentiableAt

/-- ★★ **A Hamiltonian is unique up to a constant on `ℂℙⁿ`**: two differentiable Hamiltonians of
the same field for the same 2-form family differ by a constant. No connectedness lemma is used:
every affine chart image is all of `ℂⁿ`, and `[1 : ⋯ : 1]` lies in every chart. -/
theorem eq_add_const_of_isHamiltonianVectorField
    {α : ∀ x : ℙ ℂ (Ambient n), TangentSpace (modelWithCornersSelf ℝ (Fin n → ℂ)) x [⋀^Fin 2]→L[ℝ]
      Bundle.Trivial (ℙ ℂ (Ambient n)) ℝ x}
    {X : ∀ x : ℙ ℂ (Ambient n), TangentSpace (modelWithCornersSelf ℝ (Fin n → ℂ)) x}
    {H K : ℙ ℂ (Ambient n) → ℝ}
    (hH : MDifferentiable (modelWithCornersSelf ℝ (Fin n → ℂ)) (modelWithCornersSelf ℝ ℝ) H)
    (hK : MDifferentiable (modelWithCornersSelf ℝ (Fin n → ℂ)) (modelWithCornersSelf ℝ ℝ) K)
    (h : IsHamiltonianVectorField α X H) (h' : IsHamiltonianVectorField α X K) :
    ∃ c : ℝ, ∀ p, H p = K p + c := by
  set D : ℙ ℂ (Ambient n) → ℝ := H - K with hDdef
  have hD : MDifferentiable (modelWithCornersSelf ℝ (Fin n → ℂ)) (modelWithCornersSelf ℝ ℝ) D :=
    hH.sub hK
  have hzero : ∀ q, mfderiv (modelWithCornersSelf ℝ (Fin n → ℂ)) (modelWithCornersSelf ℝ ℝ) D q
      = 0 := fun q => by
    rw [hDdef, mfderiv_sub (hH q) (hK q), h.mfderiv_eq h' q]
    exact sub_self _
  have hchart : ∀ (i : Fin (n + 1)) (w w' : Fin n → ℂ), D (chartInv i w) = D (chartInv i w') := by
    intro i w w'
    have hsymm : ∀ w : Fin n → ℂ, MDifferentiableAt (modelWithCornersSelf ℝ (Fin n → ℂ))
        (modelWithCornersSelf ℝ (Fin n → ℂ)) (chartAt (Fin n → ℂ) (origin i)).symm w := fun w =>
      mdifferentiableAt_atlas_symm (chart_mem_atlas _ _) (by rw [chartAt_origin_target]; trivial)
    have hfun : D ∘ chartInv i = D ∘ (chartAt (Fin n → ℂ) (origin i)).symm := by
      funext v
      simp only [Function.comp, chartAt_origin_symm]
    have hcomp : Differentiable ℝ (D ∘ chartInv i) := by
      intro v
      rw [hfun, ← mdifferentiableAt_iff_differentiableAt]
      exact (hD _).comp v (hsymm v)
    have hfd : ∀ v, fderiv ℝ (D ∘ chartInv i) v = 0 := fun v => by
      rw [hfun, ← mfderiv_eq_fderiv, mfderiv_comp v (hD _) (hsymm v), hzero,
        ContinuousLinearMap.zero_comp]
      rfl
    exact is_const_of_fderiv_eq_zero hcomp hfd w w'
  refine ⟨D (Projectivization.mk ℂ (allOnes n) (allOnes_ne_zero n)), fun p => ?_⟩
  have h1 : D p = D (Projectivization.mk ℂ (allOnes n) (allOnes_ne_zero n)) := by
    have e1 := chartInv_chartFun (idx p) p (idx_spec p)
    have e2 := chartInv_chartFun (idx p) _ (mk_allOnes_mem_chartSource (idx p))
    have := hchart (idx p) (chartFun (idx p) p)
      (chartFun (idx p) (Projectivization.mk ℂ (allOnes n) (allOnes_ne_zero n)))
    rwa [e1, e2] at this
  have h2 : D p = H p - K p := rfl
  linarith

/-- ★★★ **The normalisation pins the constant.** A family of Hamiltonians for the phase fields
that is non-negative and sums to `2` (the form's scale) is `2 · momentMap`: the Hamiltonian family
of the torus action, and with it the moment map, is unique. -/
theorem eq_torusHamiltonian_of_nonneg_of_sum (H : Fin (n + 1) → ℙ ℂ (Ambient n) → ℝ)
    (hdiff : ∀ k, MDifferentiable (modelWithCornersSelf ℝ (Fin n → ℂ)) (modelWithCornersSelf ℝ ℝ)
      (H k))
    (hham : ∀ k, IsHamiltonianVectorField (fun x => fsForm x) (torusField (Pi.single k 1)) (H k))
    (hnn : ∀ k p, 0 ≤ H k p) (hsum : ∀ p, ∑ k, H k p = 2) :
    ∀ k p, H k p = torusHamiltonian (Pi.single k 1) p := by
  have hc : ∀ k, ∃ c : ℝ, ∀ p, H k p = torusHamiltonian (Pi.single k 1) p + c := fun k =>
    eq_add_const_of_isHamiltonianVectorField (hdiff k) (mdifferentiable_torusHamiltonian _)
      (hham k) (torusField_isHamiltonianVectorField _)
  choose c hc using hc
  have hsum0 : ∑ k, c k = 0 := by
    have hs := hsum (origin 0)
    simp_rw [hc, torusHamiltonian_single] at hs
    rw [Finset.sum_add_distrib, ← Finset.mul_sum, momentMap_sum_eq_one] at hs
    linarith
  have hcnn : ∀ k, 0 ≤ c k := by
    intro k
    rcases Nat.eq_zero_or_pos n with hn | hn
    · subst hn
      have hk : k = 0 := Fin.ext (by omega)
      rw [Fin.sum_univ_one] at hsum0
      rw [hk, hsum0]
    · have : Nontrivial (Fin (n + 1)) := Fin.nontrivial_iff_two_le.2 (by omega)
      obtain ⟨j, hj⟩ := exists_ne k
      have := hnn k (origin j)
      rwa [hc k, torusHamiltonian_single, momentMap_origin_of_ne j k hj.symm, mul_zero,
        zero_add] at this
  have hall : ∀ k, c k = 0 := fun k =>
    (Finset.sum_eq_zero_iff_of_nonneg fun k _ => hcnn k).1 hsum0 k (Finset.mem_univ k)
  intro k p
  rw [hc k, hall k, add_zero]


/-! ### The image of the moment map is the standard simplex (G9) -/

/-- Every value of the moment map lies in the standard simplex: `momentMap_nonneg` and
`momentMap_sum_eq_one`. -/
theorem momentMap_mem_stdSimplex (p : ℙ ℂ (Ambient n)) :
    momentMap p ∈ stdSimplex ℝ (Fin (n + 1)) :=
  ⟨momentMap_nonneg p, momentMap_sum_eq_one p⟩

/-- The vector `(√t₀, …, √tₙ)`: the representative whose ray realises the simplex point `t`. -/
def sqrtVec (t : Fin (n + 1) → ℝ) : Ambient n :=
  WithLp.toLp 2 fun k => ((Real.sqrt (t k) : ℝ) : ℂ)

theorem norm_sqrtVec_apply_sq (t : Fin (n + 1) → ℝ) (k : Fin (n + 1)) (ht : 0 ≤ t k) :
    ‖sqrtVec t k‖ ^ 2 = t k := by
  show ‖((Real.sqrt (t k) : ℝ) : ℂ)‖ ^ 2 = t k
  rw [Complex.norm_of_nonneg (Real.sqrt_nonneg _), Real.sq_sqrt ht]

theorem norm_sqrtVec_sq (t : Fin (n + 1) → ℝ) (ht : t ∈ stdSimplex ℝ (Fin (n + 1))) :
    ‖sqrtVec t‖ ^ 2 = 1 := by
  rw [EuclideanSpace.norm_sq_eq,
    Finset.sum_congr rfl fun k _ => norm_sqrtVec_apply_sq t k (ht.1 k)]
  exact ht.2

theorem sqrtVec_ne_zero (t : Fin (n + 1) → ℝ) (ht : t ∈ stdSimplex ℝ (Fin (n + 1))) :
    sqrtVec t ≠ 0 := by
  intro h
  have h1 := norm_sqrtVec_sq t ht
  rw [h, norm_zero] at h1
  norm_num at h1

/-- The ray of `(√t₀, …, √tₙ)` maps to `t`. -/
theorem momentMap_mk_sqrtVec (t : Fin (n + 1) → ℝ) (ht : t ∈ stdSimplex ℝ (Fin (n + 1))) :
    momentMap (Projectivization.mk ℂ (sqrtVec t) (sqrtVec_ne_zero t ht)) = t := by
  funext k
  rw [momentMap_mk, norm_sqrtVec_sq t ht, norm_sqrtVec_apply_sq t k (ht.1 k), div_one]

/-- ★★ **The image of the moment map is exactly the standard simplex** — the moment polytope of
the torus action on `ℂℙⁿ`, by direct computation: `⊆` is the normalisation, `⊇` is the ray of
`(√t₀, …, √tₙ)`. The Atiyah–Guillemin–Sternberg convexity theorem is neither used nor proved. -/
theorem range_momentMap :
    Set.range (momentMap (N := n + 1)) = stdSimplex ℝ (Fin (n + 1)) :=
  Set.Subset.antisymm (Set.range_subset_iff.2 momentMap_mem_stdSimplex)
    fun t ht => ⟨_, momentMap_mk_sqrtVec t ht⟩

/-! ### The torus flow preserves the Fubini–Study volume (G10) -/

theorem torusUnitary_zero : torusUnitary (0 : Fin (n + 1) → ℝ) = 1 := by
  apply Subtype.ext
  rw [torusUnitary_val, Matrix.UnitaryGroup.one_val, ← Matrix.diagonal_one]
  congr 1
  funext k
  simp

theorem torusUnitary_add (θ θ' : Fin (n + 1) → ℝ) :
    torusUnitary (θ + θ') = torusUnitary θ * torusUnitary θ' := by
  apply Subtype.ext
  rw [Matrix.UnitaryGroup.mul_val, torusUnitary_val, torusUnitary_val, torusUnitary_val,
    Matrix.diagonal_mul_diagonal]
  congr 1
  funext k
  rw [Pi.add_apply, Complex.ofReal_add, add_mul, Complex.exp_add]

/-- The one-parameter group law of the torus flow `t ↦ diag(e^{itθ})`: the maps `torusUnitary
(t • θ)` compose as a flow. -/
theorem torusUnitary_add_smul (θ : Fin (n + 1) → ℝ) (s t : ℝ) :
    torusUnitary ((s + t) • θ) = torusUnitary (s • θ) * torusUnitary (t • θ) := by
  rw [add_smul, torusUnitary_add]

/-! ### The torus orbits are integral curves of the torus field (G16) -/

/-- The torus flow `t ↦ diag(e^{itθ})` is continuous in time. -/
theorem continuous_torusUnitary_smul (θ : Fin (n + 1) → ℝ) :
    Continuous fun t : ℝ => torusUnitary (t • θ) := by
  have h : (fun t : ℝ => (torusUnitary (t • θ) : Matrix (Fin (n + 1)) (Fin (n + 1)) ℂ))
      = fun t : ℝ => Matrix.diagonal fun k => Complex.exp ((((t • θ) k : ℝ) : ℂ) * Complex.I) :=
    funext fun t => torusUnitary_val _
  have hmat : Continuous
      fun t : ℝ => (torusUnitary (t • θ) : Matrix (Fin (n + 1)) (Fin (n + 1)) ℂ) := by
    rw [h]
    exact (continuous_pi fun k => Complex.continuous_exp.comp
      ((Complex.continuous_ofReal.comp ((continuous_apply k).comp
        (continuous_id.smul continuous_const))).mul continuous_const)).matrix_diagonal
  exact hmat.subtype_mk _

/-- ★★★ **The torus orbit is the integral curve of the torus field**: `t ↦ diag(e^{itθ}) • p` is a
global integral curve of `torusField θ`, for every `p`. The route of
`isMIntegralCurve_schrodingerUnitary_smul`: in the chart at `diag(e^{itθ}) • p` the curve is
`s ↦ chartFun (diag(e^{i(s-t)θ}) • q)`, whose derivative at `s = t` is the chart velocity
(`hasDerivAt_chartFun_torusUnitary`, shifted by the group law `torusUnitary_add_smul`). -/
theorem isMIntegralCurve_torusUnitary_smul (θ : Fin (n + 1) → ℝ) (p : ℙ ℂ (Ambient n)) :
    IsMIntegralCurve (fun t : ℝ => torusUnitary (t • θ) • p) (torusField θ) := by
  have hcont : Continuous fun t : ℝ => torusUnitary (t • θ) • p :=
    (continuous_torusUnitary_smul θ).smul continuous_const
  intro t
  refine ⟨hcont.continuousAt, ?_⟩
  have hq : chartInv (idx (torusUnitary (t • θ) • p))
      (chartFun (idx (torusUnitary (t • θ) • p)) (torusUnitary (t • θ) • p))
      = torusUnitary (t • θ) • p :=
    chartInv_chartFun _ _ (idx_spec _)
  have hfun : (fun s : ℝ => chartFun (idx (torusUnitary (t • θ) • p)) (torusUnitary (s • θ) • p))
      = fun s : ℝ => chartFun (idx (torusUnitary (t • θ) • p))
        (torusUnitary ((s - t) • θ) • chartInv (idx (torusUnitary (t • θ) • p))
          (chartFun (idx (torusUnitary (t • θ) • p)) (torusUnitary (t • θ) • p))) := by
    funext s
    rw [hq, ← mul_smul, ← torusUnitary_add_smul, sub_add_cancel]
  have hd : HasDerivAt
      (fun s : ℝ => chartFun (idx (torusUnitary (t • θ) • p)) (torusUnitary (s • θ) • p))
      (torusField θ (torusUnitary (t • θ) • p)) t := by
    rw [hfun]
    show HasDerivAt _ (torusChartField (idx (torusUnitary (t • θ) • p)) θ
      (chartFun (idx (torusUnitary (t • θ) • p)) (torusUnitary (t • θ) • p))) t
    have h0 := hasDerivAt_chartFun_torusUnitary θ (idx (torusUnitary (t • θ) • p))
      (chartFun (idx (torusUnitary (t • θ) • p)) (torusUnitary (t • θ) • p))
    have h1 : HasDerivAt (fun s : ℝ => s - t) 1 t :=
      (hasDerivAt_sub_const_iff t).2 (hasDerivAt_id' t)
    have h0' : HasDerivAt (fun τ : ℝ => chartFun (idx (torusUnitary (t • θ) • p))
        (torusUnitary (τ • θ) • chartInv (idx (torusUnitary (t • θ) • p))
          (chartFun (idx (torusUnitary (t • θ) • p)) (torusUnitary (t • θ) • p))))
        (torusChartField (idx (torusUnitary (t • θ) • p)) θ
          (chartFun (idx (torusUnitary (t • θ) • p)) (torusUnitary (t • θ) • p))) (t - t) := by
      rw [sub_self]
      exact h0
    have h2 := HasDerivAt.scomp (h := fun s : ℝ => s - t) (x := t) h0' h1
    exact h2.congr_deriv (one_smul ℝ _)
  have hw : writtenInExtChartAt (modelWithCornersSelf ℝ ℝ) (modelWithCornersSelf ℝ (Fin n → ℂ)) t
      (fun s : ℝ => torusUnitary (s • θ) • p)
      = fun s : ℝ => chartFun (idx (torusUnitary (t • θ) • p)) (torusUnitary (s • θ) • p) := by
    funext s
    simp only [writtenInExtChartAt, Function.comp, extChartAt_model_space_eq_id,
      PartialEquiv.refl_symm, PartialEquiv.refl_coe, id, extChartAt_coe, modelWithCornersSelf_coe]
    rfl
  rw [hw]
  exact hd.hasFDerivAt.hasFDerivWithinAt

/-- ★ **The torus flow preserves the Fubini–Study volume**: every map `p ↦ diag(e^{iθ}) • p` — in
particular every time-`t` map `diag(e^{itθ})` of the flow of `torusField`
(`isMIntegralCurve_torusUnitary_smul`) — preserves
`fsVolume n`. A corollary of the unitary invariance `fsVolume_map_smul`: Liouville in the dynamics
sense for this one flow, with no manifold-level flow theory (G5) involved. -/
theorem fsVolume_map_torusUnitary_smul (θ : Fin (n + 1) → ℝ) :
    Measure.map (fun p : ℙ ℂ (Ambient n) => torusUnitary θ • p) (fsVolume n) = fsVolume n :=
  fsVolume_map_smul (torusUnitary θ)

/-- The same, as a measure-preserving map. -/
theorem measurePreserving_torusUnitary_smul (θ : Fin (n + 1) → ℝ) :
    MeasurePreserving (fun p : ℙ ℂ (Ambient n) => torusUnitary θ • p) (fsVolume n) (fsVolume n) :=
  ⟨(continuous_const_smul (torusUnitary θ)).measurable, fsVolume_map_smul (torusUnitary θ)⟩

end Projectivization
