/-
Copyright (c) 2026 Zayn Blore. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Zayn Blore
-/
module

public import CsdLean4.Mathlib.LinearAlgebra.Projectivization.WignerRigidity
public import CsdLean4.Mathlib.LinearAlgebra.Projectivization.Unitary

/-!
# The Floquet-evolution interface (quantum-chaos workstream, H2)

**Category:** Special (incubator — CSD-free; `upstream-candidate(physlib)`).

The small abstract interface the CSD quantum-chaos theorems bind to (BACKLOG §H2;
policy in `specs/external-library-map.md`): one stroboscopic period of a
periodically driven finite quantum system, as a **linear isometry equivalence** —
an equivalence, not merely an isometry, because reversibility is load-bearing for
the CSD reading (global information preservation, records).

Four-way classification (checked 2026-08-07 against the actual repositories):
Mathlib has the matrix exponential and unitary machinery but no Floquet notion;
Physlib (`leanprover-community/physlib`, Lean 4.32.0, 690 modules) has a genuine
`QuantumMechanics/HilbertSpaces/FiniteTarget` layer — a structure *wrapping*
`EuclideanSpace ℂ d`, so future adapters are `.val`-thin — but **no Floquet,
kicked-model, or chaos-diagnostic modules**. Hence class 3: implemented locally
behind this interface, marked `upstream-candidate(physlib)`; when Physlib grows
the generic notion (or this file moves there), adapters in `CsdLean4/Interop/`
replace it and the CSD theorems downstream are untouched.

## API

* `FloquetEvolution H` — the interface: `step : H ≃ₗᵢ[ℂ] H`.
* `iterate n = step ^ n` — `n` stroboscopic periods (the group structure on
  `H ≃ₗᵢ[ℂ] H` supplies the power), with `iterate_zero/one/succ_apply` and the
  ★ information-preservation lemmas `norm_iterate_apply` /
  `inner_iterate_iterate` (global norms and overlaps are exact invariants of
  arbitrarily many periods — the "preserves global information" clause of the
  §H3 pilot statement).
* `projStep` / `projIterate` — the induced ray dynamics on `ℙ ℂ H`
  (`Projectivization.projMap`), with functoriality
  (`projIterate_succ`, via `projMap_trans`) and, on `ℂℙ^{N-1}`, transition-
  probability preservation (`projStep_transProbPreserving`,
  `projIterate_transProbPreserving`) — the "induces projective dynamics" clause,
  in exactly the vocabulary `wigner_rigidity` consumes.
* `refl` and `ofUnitary` — inhabitation and the matrix-dynamics adapter seam:
  one period generated by a unitary matrix on `ℂ^N` (kicked models are products
  of such steps), through the staged `toEuclideanLinearEquiv` +
  `inner_toEuclideanLin_unitary`.

The CSD-side content (ontic lift, Σ-volume preservation, record persistence)
deliberately does NOT live here: it binds to this interface from
`Empirical/CSD/QuantumChaos/` (§H3).
-/

@[expose] public section

open scoped LinearAlgebra.Projectivization

namespace QuantumChaos

/-- **The Floquet-evolution interface**: one stroboscopic period of a
periodically driven system on the state space `H`, as a linear isometry
equivalence. CSD theorems bind to this structure; adapters instantiate it
(local matrix dynamics now, Physlib finite-system dynamics later). -/
structure FloquetEvolution (H : Type*)
    [NormedAddCommGroup H] [InnerProductSpace ℂ H] where
  /-- One period of the drive. An equivalence: the evolution is reversible. -/
  step : H ≃ₗᵢ[ℂ] H

namespace FloquetEvolution

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  (F : FloquetEvolution H)

/-- `n` stroboscopic periods: the `n`-th power of the step in the group of
linear isometry equivalences. -/
noncomputable def iterate (n : ℕ) : H ≃ₗᵢ[ℂ] H := F.step ^ n

@[simp] lemma iterate_zero : F.iterate 0 = 1 := pow_zero _

@[simp] lemma iterate_one : F.iterate 1 = F.step := pow_one _

/-- Peeling one period at the start: `iterate (n+1) ψ = iterate n (step ψ)`. -/
lemma iterate_succ_apply (n : ℕ) (ψ : H) :
    F.iterate (n + 1) ψ = F.iterate n (F.step ψ) := by
  rw [iterate, iterate, pow_succ]
  rfl

/-- Peeling one period at the end: `iterate (n+1) ψ = step (iterate n ψ)`. -/
lemma iterate_succ_apply' (n : ℕ) (ψ : H) :
    F.iterate (n + 1) ψ = F.step (F.iterate n ψ) := by
  rw [iterate, iterate, pow_succ']
  rfl

/-- ★ **Global information preservation (norms).** The norm is an exact
invariant of arbitrarily many periods. -/
@[simp] lemma norm_iterate_apply (n : ℕ) (ψ : H) :
    ‖F.iterate n ψ‖ = ‖ψ‖ :=
  (F.iterate n).norm_map ψ

/-- ★ **Global information preservation (overlaps).** Inner products are exact
invariants of arbitrarily many periods: no global information is lost, however
scrambled the local accessibility becomes. -/
@[simp] lemma inner_iterate_iterate (n : ℕ) (u v : H) :
    (inner ℂ (F.iterate n u) (F.iterate n v) : ℂ) = inner ℂ u v :=
  (F.iterate n).inner_map_map u v

/-! ### The induced projective (ray) dynamics -/

/-- The ray dynamics of one period on `ℙ ℂ H`. -/
noncomputable def projStep : ℙ ℂ H → ℙ ℂ H :=
  Projectivization.projMap F.step

/-- The ray dynamics of `n` periods. -/
noncomputable def projIterate (n : ℕ) : ℙ ℂ H → ℙ ℂ H :=
  Projectivization.projMap (F.iterate n)

@[simp] lemma projIterate_zero : F.projIterate 0 = id := by
  rw [projIterate, iterate_zero]
  exact Projectivization.projMap_refl

/-- The ray dynamics iterates with the vector dynamics: `n+1` periods on rays
is one ray period after `n` (functoriality of `projMap`). -/
lemma projIterate_succ (n : ℕ) :
    F.projIterate (n + 1) = F.projStep ∘ F.projIterate n := by
  rw [projIterate, projIterate, projStep, iterate, iterate, pow_succ',
    show F.step * F.step ^ n = (F.step ^ n).trans F.step from rfl,
    Projectivization.projMap_trans]

end FloquetEvolution

/-! ### Transition-probability preservation on `ℂℙ^{N-1}` -/

variable {N : ℕ}

/-- The one-period ray dynamics preserves transition probabilities — the
hypothesis `wigner_rigidity` consumes. -/
theorem FloquetEvolution.projStep_transProbPreserving
    (F : FloquetEvolution (EuclideanSpace ℂ (Fin N))) :
    Projectivization.TransProbPreserving F.projStep :=
  Projectivization.projMap_transProbPreserving F.step

/-- The `n`-period ray dynamics preserves transition probabilities. -/
theorem FloquetEvolution.projIterate_transProbPreserving
    (F : FloquetEvolution (EuclideanSpace ℂ (Fin N))) (n : ℕ) :
    Projectivization.TransProbPreserving (F.projIterate n) :=
  Projectivization.projMap_transProbPreserving (F.iterate n)

/-! ### Inhabitation and the matrix-dynamics adapter seam -/

/-- The free (identity) evolution: inhabitation of the interface over any
state space. -/
noncomputable def FloquetEvolution.refl
    (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℂ H] :
    FloquetEvolution H :=
  ⟨1⟩

/-- **The matrix-dynamics adapter**: one period generated by a unitary matrix
on `ℂ^N`. Kicked models (kicked Ising, kicked rotor) are products of such
steps, so this seam is what the §H3 pilot instantiates; a future Physlib
adapter replaces it without touching downstream theorems. -/
noncomputable def FloquetEvolution.ofUnitary
    (U : Matrix.unitaryGroup (Fin N) ℂ) :
    FloquetEvolution (EuclideanSpace ℂ (Fin N)) where
  step :=
    { Matrix.UnitaryGroup.toEuclideanLinearEquiv U with
      norm_map' := fun v => by
        rw [← Real.sqrt_sq (norm_nonneg _), ← Real.sqrt_sq (norm_nonneg v)]
        congr 1
        rw [← @inner_self_eq_norm_sq ℂ, ← @inner_self_eq_norm_sq ℂ]
        exact congrArg RCLike.re
          (Projectivization.inner_toEuclideanLin_unitary U v v) }

@[simp] lemma FloquetEvolution.ofUnitary_step_apply
    (U : Matrix.unitaryGroup (Fin N) ℂ) (ψ : EuclideanSpace ℂ (Fin N)) :
    (FloquetEvolution.ofUnitary U).step ψ = Matrix.toEuclideanLin U.val ψ :=
  Matrix.UnitaryGroup.toEuclideanLinearEquiv_apply U ψ

end QuantumChaos
